const staticDanceQuestions = [
{ id: 'static-dance-001', category: 'Classical Dance', question: 'Kamala Lakshmi Narayanan is known worldwide as a leading exponent of which South Indian classical dance form?', options: ['Kuchipudi', 'Mohiniyattam', 'Bharatanatyam', 'Kathak'], answer: 2, explanation: 'Kamala Lakshmi Narayanan is associated with Bharatanatyam. Extra Detail → Bharatanatyam is a major classical dance tradition of Tamil Nadu and is known for expressive abhinaya, geometric body positions and rhythmic footwork.' },

{ id: 'static-dance-002', category: 'Dance-State Matching', question: 'Which of the following correctly matches Bharatanatyam, Mohiniyattam, Garba and Sattriya with their respective states?', options: ['Tamil Nadu, Kerala, Gujarat, Assam', 'Kerala, Tamil Nadu, Assam, Gujarat', 'Tamil Nadu, Gujarat, Kerala, Assam', 'Gujarat, Kerala, Tamil Nadu, Assam'], answer: 0, explanation: 'Correct mapping → Bharatanatyam–Tamil Nadu, Mohiniyattam–Kerala, Garba–Gujarat and Sattriya–Assam. Extra Detail → Bharatanatyam, Mohiniyattam and Sattriya are classical dances, while Garba is a famous folk dance of Gujarat.' },

{ id: 'static-dance-003', category: 'Classical Dance Personalities', question: 'Which Indian classical dancer is associated with Kuchipudi?', options: ['Malavika Sarukkai', 'Vempati Chinna Satyam', 'Meenakshi Medhi', 'Sanjukta Panigrahi'], answer: 1, explanation: 'Vempati Chinna Satyam is associated with Kuchipudi. Extra Detail → He was one of the major modern gurus of Kuchipudi and played an important role in systematising and popularising the dance form.' },

{ id: 'static-dance-004', category: 'Dance Institutions', question: 'Jawaharlal Nehru Manipur Dance Academy is located in which city of Manipur?', options: ['Imphal', 'Thoubal', 'Ukhrul', 'Chandel'], answer: 0, explanation: 'The academy is located in Imphal. Extra Detail → It is an important institution for the preservation and teaching of Manipuri dance and related traditions.' },

{ id: 'static-dance-005', category: 'Awards & Dance', question: 'Who was the first dancer from Odisha to be honoured with the Padma Vibhushan?', options: ['Kelucharan Mohapatra', 'Guru Bipin Singh', 'Uday Shankar', 'Pandit Birju Maharaj'], answer: 0, explanation: 'Kelucharan Mohapatra was the first dancer from Odisha to receive the Padma Vibhushan. Extra Detail → He was one of the most important revivalists and gurus of Odissi dance.' },

{ id: 'static-dance-006', category: 'Mohiniyattam', question: 'Mohiniyattam is associated with which traditional dance style?', options: ['Chowk', 'Lasya style', 'Tribhanga', 'Samapadam'], answer: 1, explanation: 'Mohiniyattam is strongly associated with the graceful Lasya style. Extra Detail → Lasya emphasises soft, graceful and feminine movements, which are central to Mohiniyattam.' },

{ id: 'static-dance-007', category: 'Odissi Personalities', question: 'Ranjana Gauhar received the Padma Shri in 2003 for her contribution to which Indian classical dance style?', options: ['Kuchipudi', 'Sattriya', 'Manipuri', 'Odissi'], answer: 3, explanation: 'Ranjana Gauhar is associated with Odissi. Extra Detail → She is a noted Odissi dancer and was awarded the Padma Shri in 2003.' },

{ id: 'static-dance-008', category: 'Kathak Personalities', question: 'Which Indian classical dancer is associated with Kathak?', options: ['Vedantam Satyanarayana Sarma', 'Rohini Bhate', 'Kelucharan Mohapatra', 'Sharodi Saikia'], answer: 1, explanation: 'Rohini Bhate was a prominent Kathak exponent. Extra Detail → Vedantam Satyanarayana Sarma is linked with Kuchipudi, Kelucharan Mohapatra with Odissi and Sharodi Saikia with Sattriya.' },

{ id: 'static-dance-009', category: 'Bharatanatyam Personalities', question: 'Yamini Krishnamurthy is associated with which classical dance form in the question?', options: ['Mohiniyattam', 'Sattriya', 'Bharatanatyam', 'Odissi'], answer: 2, explanation: 'Yamini Krishnamurthy is strongly associated with Bharatanatyam. Extra Detail → She became one of the best-known Indian classical dancers and helped popularise Indian dance nationally and internationally.' },

{ id: 'static-dance-010', category: 'Odissi Personalities', question: 'Which of the following classical dancers is NOT associated with Odissi?', options: ['Kumkum Mohanty', 'Geetanjali Lal', 'Kiran Segal', 'Mayadhar Raut'], answer: 1, explanation: 'Geetanjali Lal is primarily associated with Kathak, not Odissi. Extra Detail → Kumkum Mohanty, Kiran Segal and Mayadhar Raut are associated with the Odissi tradition.' },

{ id: 'static-dance-011', category: 'Bharatanatyam Personalities', question: 'Tanjore Balasaraswati was a renowned dancer of which classical dance form?', options: ['Kathak', 'Mohiniyattam', 'Bharatanatyam', 'Kuchipudi'], answer: 2, explanation: 'Tanjore Balasaraswati was one of the greatest exponents of Bharatanatyam. Extra Detail → She belonged to the traditional hereditary dance-music lineage of Tamil Nadu.' },

{ id: 'static-dance-012', category: 'Mohiniyattam Personalities', question: 'Kalamandalam Kalyanikutty Amma is associated with which dance style?', options: ['Kathak', 'Mohiniyattam', 'Kuchipudi', 'Bharatanatyam'], answer: 1, explanation: 'Kalamandalam Kalyanikutty Amma is closely associated with Mohiniyattam. Extra Detail → She is often remembered as one of the key figures in the modern revival and teaching of Mohiniyattam.' },

{ id: 'static-dance-013', category: 'Odissi Personalities', question: 'Madhavi Mudgal is a famous dancer of which classical dance form?', options: ['Manipuri', 'Odissi', 'Bharatanatyam', 'Kathak'], answer: 1, explanation: 'Madhavi Mudgal is a celebrated Odissi dancer. Extra Detail → She is known for refined technique and has contributed significantly to the contemporary presentation of Odissi.' },

{ id: 'static-dance-014', category: 'Maharashtra Folk Dance', question: 'Which of the following is a folk dance of Maharashtra?', options: ['Ghoomar', 'Bhangra', 'Garba', 'Dhangari Gaja'], answer: 3, explanation: 'Dhangari Gaja is associated with Maharashtra. Extra Detail → Ghoomar is associated with Rajasthan, Bhangra with Punjab and Garba with Gujarat.' },

{ id: 'static-dance-015', category: 'Chhau', question: 'Which folk dance of the Jharkhand-Odisha-West Bengal region is included in the Representative List of the Intangible Cultural Heritage of Humanity?', options: ['Dadar', 'Kummi', 'Karma Naach', 'Chhau'], answer: 3, explanation: 'Chhau is the correct answer. Extra Detail → Chhau has major traditions in Seraikella, Purulia and Mayurbhanj and is famous for martial movements, masks in some styles and dramatic presentation.' },

{ id: 'static-dance-016', category: 'Assam Folk Dance', question: 'Which folk dance is performed during the Bwisagu festival?', options: ['Bhortal', 'Bihu', 'Jhumur', 'Bagurumba'], answer: 3, explanation: 'Bagurumba is associated with the Bodo community and is performed during Bwisagu. Extra Detail → It is often described as a graceful nature-inspired dance.' },

{ id: 'static-dance-017', category: 'Tribal Dance', question: 'Padma awardee Arjun Singh Dhurve is associated with which folk dance?', options: ['Raasleela', 'Chhau', 'Baiga', 'Garba'], answer: 2, explanation: 'Arjun Singh Dhurve is associated with the Baiga dance tradition. Extra Detail → Baiga dance is linked with the Baiga tribal community, especially in central India.' },

{ id: 'static-dance-018', category: 'Karnataka Folk Dance', question: 'Kurki dance is a folk dance mainly performed in which state?', options: ['Uttar Pradesh', 'Karnataka', 'Rajasthan', 'Nagaland'], answer: 1, explanation: 'Kurki dance is associated with Karnataka according to the PDF. Extra Detail → Karnataka has a rich range of folk traditions, including Yakshagana and several regional community dances.' },

{ id: 'static-dance-019', category: 'Karnataka Folk Dance', question: 'Yakshagana is a folk dance-theatre tradition of which state?', options: ['West Bengal', 'Madhya Pradesh', 'Odisha', 'Karnataka'], answer: 3, explanation: 'Yakshagana is a famous dance-theatre tradition of Karnataka. Extra Detail → It combines dance, music, dialogue, elaborate costumes and mythological storytelling.' },

{ id: 'static-dance-020', category: 'Rajasthan Folk Dance', question: 'Terah Taali folk dance is mainly related to which state?', options: ['Rajasthan', 'Assam', 'Madhya Pradesh', 'Haryana'], answer: 0, explanation: 'Terah Taali is associated with Rajasthan. Extra Detail → It is known for the use of multiple manjiras or small cymbals tied to the body and played rhythmically.' },

{ id: 'static-dance-021', category: 'Madhya Pradesh Folk Dance', question: 'Matki dance is a famous folk dance of which state?', options: ['Gujarat', 'Maharashtra', 'Madhya Pradesh', 'Punjab'], answer: 2, explanation: 'Matki dance is associated with Madhya Pradesh. Extra Detail → It is traditionally performed by women and often involves balancing earthen pots.' },

{ id: 'static-dance-022', category: 'Folk Dance Matching', question: 'Which of the following folk dance-state combinations is INCORRECT?', options: ['Dhangari Gaja–Maharashtra', 'Dandiya Raas–Gujarat', 'Paika–Kerala', 'Dollu Kunitha–Karnataka'], answer: 2, explanation: 'Paika is not a folk dance of Kerala. Extra Detail → Paika is associated with eastern India, especially Odisha; Dandiya Raas belongs to Gujarat and Dollu Kunitha to Karnataka.' },

{ id: 'static-dance-023', category: 'Odisha Folk Dance', question: 'Dalkhai is a popular folk dance of which state?', options: ['Odisha', 'Bihar', 'Uttar Pradesh', 'Punjab'], answer: 0, explanation: 'Dalkhai is a popular folk dance of Odisha. Extra Detail → It is especially associated with western Odisha and is commonly performed during festivals.' },

{ id: 'static-dance-024', category: 'Goa Folk Dance', question: 'Which of the following folk dances is NOT associated with Goa?', options: ['Ghumura', 'Dekhni', 'Dashavatar', 'Dhangar'], answer: 0, explanation: 'Ghumura is associated with Odisha rather than Goa. Extra Detail → Dekhni and traditional Dhangar dances are associated with Goa, while Dashavatar is also performed in the Konkan-Goa cultural belt.' },

{ id: 'static-dance-025', category: 'Dance-State Matching', question: 'Which state-folk dance pair is incorrect?', options: ['Chhattisgarh–Dagla', 'Uttarakhand–Tapali', 'Assam–Bihu', 'Gujarat–Garba'], answer: 1, explanation: 'The PDF marks Uttarakhand–Tapali as the incorrect pair. Extra Detail → Bihu is strongly associated with Assam and Garba with Gujarat.' },

{ id: 'static-dance-026', category: 'Sattriya', question: 'Which is the traditional classical dance of Assam?', options: ['Sattriya', 'Bihu', 'Kathak', 'Chhau'], answer: 0, explanation: 'Sattriya is the classical dance tradition of Assam. Extra Detail → It developed in the Vaishnav monasteries or Sattras of Assam.' },

{ id: 'static-dance-027', category: 'Sattriya History', question: 'Who is known as the founder of Assam\'s Sattriya dance tradition?', options: ['Chaitanya', 'Tara Devi', 'Birju Maharaj', 'Shankaradeva'], answer: 3, explanation: 'Srimanta Shankaradeva is regarded as the founder of Sattriya. Extra Detail → He was a 15th-16th century saint-reformer who used dance, drama and music to spread the neo-Vaishnavite movement in Assam.' },

{ id: 'static-dance-028', category: 'Mohiniyattam', question: 'Which dance style is known as the \'Mohini dance\'?', options: ['Kathak', 'Mohiniyattam', 'Bharatanatyam', 'Odissi'], answer: 1, explanation: 'Mohiniyattam literally refers to the dance of Mohini. Extra Detail → Mohini is the female incarnation of Lord Vishnu in Hindu tradition, and the dance is associated with Kerala.' },

{ id: 'static-dance-029', category: 'Dance Theory', question: 'Which Indian art form is related to Nritya, Natya and Nritta?', options: ['Music', 'Nritya Kala (Dance Art)', 'Puppetry', 'Martial Art'], answer: 1, explanation: 'Nritya, Natya and Nritta are fundamental concepts of Indian dance. Extra Detail → Nritta means pure dance, Nritya combines expression with rhythm, and Natya refers to dramatic representation.' },

{ id: 'static-dance-030', category: 'Dance Festivals', question: 'In which state is the Khajuraho Dance Festival celebrated?', options: ['Madhya Pradesh', 'Himachal Pradesh', 'Uttar Pradesh', 'Andhra Pradesh'], answer: 0, explanation: 'The Khajuraho Dance Festival is held in Madhya Pradesh. Extra Detail → It showcases major Indian classical dance traditions against the backdrop of the Khajuraho temple complex.' },

{ id: 'static-dance-031', category: 'Kerala Classical Dance', question: 'Which classical dance is popular in Kerala?', options: ['Kathakali', 'Kuchipudi', 'Kathak', 'Bharatanatyam'], answer: 0, explanation: 'Kathakali is a major classical dance-drama tradition of Kerala. Extra Detail → It is famous for elaborate makeup, costumes, codified gestures and dramatic storytelling.' },

{ id: 'static-dance-032', category: 'Rajasthan Folk Dance', question: 'Which of the following is a folk dance of Rajasthan?', options: ['Bhangra', 'Gaba', 'Nati', 'Ghoomar'], answer: 3, explanation: 'Ghoomar is a famous folk dance of Rajasthan. Extra Detail → It is traditionally performed by women in circular formations and is widely associated with Rajasthani celebrations.' },

{ id: 'static-dance-033', category: 'Sattriya Personalities', question: 'Meeranalini Barthakur is a famous dancer of which form?', options: ['Manipuri', 'Kuchipudi', 'Kathak', 'Sattriya'], answer: 3, explanation: 'The PDF associates Meeranalini Barthakur with Sattriya. Extra Detail → Sattriya is one of the recognised classical dance traditions of India and is rooted in Assam\'s monastic Vaishnav culture.' },

{ id: 'static-dance-034', category: 'Gujarat Folk Dance', question: 'Which dance depicts a mock battle between Durga and Mahishasura?', options: ['Dandiya Raas', 'Tarangamel', 'Kalbelia', 'Ghoomar'], answer: 0, explanation: 'Dandiya Raas is identified in the PDF. Extra Detail → Dandiya Raas is a vibrant Gujarati folk dance performed with sticks and is especially popular during Navratri.' },

{ id: 'static-dance-035', category: 'Kathak', question: 'Which dance style is often performed with the song form \'Thumri\'?', options: ['Sattriya', 'Kathak', 'Kuchipudi', 'Chhau'], answer: 1, explanation: 'Kathak is closely associated with Thumri in its expressive abhinaya repertoire. Extra Detail → Thumri is a semi-classical vocal form often used for romantic and devotional expression.' },

{ id: 'static-dance-036', category: 'Kuchipudi', question: 'Which classical dance style\'s music is related to the Carnatic music system?', options: ['Kuchipudi', 'Odissi', 'Chhau', 'Kathak'], answer: 0, explanation: 'Kuchipudi uses the Carnatic music tradition. Extra Detail → Kuchipudi originated in Andhra Pradesh and combines dance, drama and expressive storytelling.' },

{ id: 'static-dance-037', category: 'Odissi History', question: 'Which classical dance style was historically performed by Maharis as part of temple service?', options: ['Kathak', 'Kathakali', 'Odissi', 'Kuchipudi'], answer: 2, explanation: 'Odissi was historically connected with the Mahari tradition of temple dancers. Extra Detail → Maharis served in the Jagannath temple tradition and are an important part of Odissi\'s historical development.' },

{ id: 'static-dance-038', category: 'Manipuri', question: 'Which classical dance style has Jagoi and Cholom as its two main branches?', options: ['Kuchipudi', 'Kathak', 'Odissi', 'Manipuri'], answer: 3, explanation: 'Manipuri has Jagoi and Cholom as major branches. Extra Detail → Jagoi is associated with graceful dance, while Cholom includes vigorous drum-based traditions such as Pung Cholom.' },

{ id: 'static-dance-039', category: 'Rajasthan Folk Dance', question: 'Which of the following dances is NOT related to Rajasthan?', options: ['Kalbelia', 'Ghoomar', 'Kacho Ghodi', 'Tarangamel'], answer: 3, explanation: 'Tarangamel is associated with Goa, not Rajasthan. Extra Detail → Kalbelia, Ghoomar and Kachhi Ghodi are major Rajasthani folk dance traditions.' },

{ id: 'static-dance-040', category: 'Folk Dance Matching', question: 'Which dance-state pair is correctly matched?', options: ['Dandiya–Uttar Pradesh', 'Gaur–Chhattisgarh', 'Lavani–Kerala', 'Ghoomar–Gujarat'], answer: 1, explanation: 'Gaur dance is associated with Chhattisgarh. Extra Detail → Dandiya belongs to Gujarat, Lavani to Maharashtra and Ghoomar to Rajasthan.' },

{ id: 'static-dance-041', category: 'Gujarat Folk Dance', question: 'Dandiya is the traditional folk dance of which Indian state?', options: ['West Bengal', 'Bihar', 'Gujarat', 'Assam'], answer: 2, explanation: 'Dandiya is associated with Gujarat. Extra Detail → Dandiya Raas is commonly performed during Navratri using decorated sticks.' },

{ id: 'static-dance-042', category: 'Bharatanatyam', question: 'Which dance form is also known as Ekaharya, where one dancer performs multiple roles in a single performance?', options: ['Kathakali', 'Sattriya', 'Kathak', 'Bharatanatyam'], answer: 3, explanation: 'The PDF identifies Bharatanatyam with Ekaharya. Extra Detail → In Ekaharya abhinaya, a single performer can portray different characters through expression, gesture and body language.' },

{ id: 'static-dance-043', category: 'Ladakh Folk Dance', question: 'Spao is the folk dance of which region?', options: ['Ladakh', 'Puducherry', 'Assam', 'Maharashtra'], answer: 0, explanation: 'Spao is associated with Ladakh. Extra Detail → Ladakh has a rich tradition of ceremonial and community dances connected with festivals and local cultural life.' },

{ id: 'static-dance-044', category: 'Kathak Personalities', question: 'Gauri Diwakar is a famous dancer of which classical dance form?', options: ['Manipuri', 'Kathakali', 'Odissi', 'Kathak'], answer: 3, explanation: 'Gauri Diwakar is associated with Kathak. Extra Detail → Kathak is a North Indian classical dance known for spins, intricate footwork, storytelling and rhythmic improvisation.' },

{ id: 'static-dance-045', category: 'Bharatanatyam Personalities', question: 'Rukmini Devi Arundale was a pioneer in which classical dance field?', options: ['Bharatanatyam', 'Manipuri', 'Odissi', 'Kathak'], answer: 0, explanation: 'Rukmini Devi Arundale was a pioneer of Bharatanatyam. Extra Detail → She played a major role in reviving and institutionalising Bharatanatyam and founded Kalakshetra.' },

{ id: 'static-dance-046', category: 'Uttarakhand Folk Dance', question: 'In which Indian state does the Jagard dance form have its primary roots?', options: ['Himachal Pradesh', 'Bihar', 'Jammu and Kashmir', 'Uttarakhand'], answer: 3, explanation: 'Jagard or Jagar is associated with Uttarakhand. Extra Detail → Jagar is a ritual tradition involving invocation, music and community performance.' },

{ id: 'static-dance-047', category: 'Odissi History', question: 'The early form of Odissi dance was performed by women serving in temples. What was their traditional title?', options: ['Devadasis', 'Mahibs', 'Maharis', 'Maharani'], answer: 2, explanation: 'The temple women associated with early Odissi were called Maharis. Extra Detail → The Mahari tradition is closely linked with the Jagannath temple and the historical evolution of Odissi.' },

{ id: 'static-dance-048', category: 'Tribal Dance', question: 'Which of the following is a tribal dance of India?', options: ['Ghusadi', 'Lavani', 'Bhangra', 'Kathak'], answer: 0, explanation: 'Ghusadi is identified as a tribal dance. Extra Detail → The PDF notes its association with Andhra Pradesh and tribal communities.' },

{ id: 'static-dance-049', category: 'Kathak Personalities', question: 'Shambhu Maharaj, honoured with the Sangeet Natak Akademi Fellowship in 1967, was famous for his contribution to which art form?', options: ['Carnatic Music', 'Bharatanatyam', 'Hindustani Classical Music', 'Kathak'], answer: 3, explanation: 'Shambhu Maharaj was a legendary Kathak exponent. Extra Detail → He belonged to the Lucknow gharana and was especially celebrated for expressive abhinaya.' },

{ id: 'static-dance-050', category: 'Bharatanatyam Personalities', question: 'Who is known for popularising Bharatanatyam on the global stage?', options: ['Mallika Sarabhai', 'Sonal Mansingh', 'Hema Malini', 'Rukmini Devi Arundale'], answer: 3, explanation: 'The PDF marks Rukmini Devi Arundale. Extra Detail → Through Kalakshetra and her reformist work, she helped bring Bharatanatyam into modern institutional and international visibility.' },

{ id: 'static-dance-051', category: 'Odissi Personalities', question: 'Minati Mishra is associated with which dance form?', options: ['Odissi', 'Manipuri', 'Bharatanatyam', 'Kathakali'], answer: 0, explanation: 'Minati Mishra is associated with Odissi. Extra Detail → She was an important Odissi exponent and helped popularise the form through stage and film performances.' },

{ id: 'static-dance-052', category: 'Manipuri Personalities', question: 'Famous dance guru Rajkumar Singhajit Singh is associated with which dance style?', options: ['Kathak', 'Manipuri', 'Odissi', 'Kathakali'], answer: 1, explanation: 'Rajkumar Singhajit Singh is associated with Manipuri dance. Extra Detail → He has been a major teacher and exponent of the Manipuri classical tradition.' },

{ id: 'static-dance-053', category: 'Mizoram Folk Dance', question: 'Cheraw, popularly known as the bamboo dance, is the traditional cultural dance of which state?', options: ['Jharkhand', 'Uttarakhand', 'Mizoram', 'Manipur'], answer: 2, explanation: 'Cheraw is the famous bamboo dance of Mizoram. Extra Detail → Performers step rhythmically between moving bamboo staves, making timing and coordination essential.' },

{ id: 'static-dance-054', category: 'Kathak Personalities', question: 'Pandit Birju Maharaj was a famous dancer of which Indian dance style?', options: ['Odissi', 'Bharatanatyam', 'Kuchipudi', 'Kathak'], answer: 3, explanation: 'Pandit Birju Maharaj was one of India\'s most celebrated Kathak dancers. Extra Detail → He belonged to the Lucknow Kalka-Bindadin gharana and was renowned for rhythm, expression and storytelling.' },

{ id: 'static-dance-055', category: 'Dance Institutions', question: 'Where is Sangeet Natak Akademi located?', options: ['Bengaluru', 'Mumbai', 'New Delhi', 'Bhopal'], answer: 2, explanation: 'Sangeet Natak Akademi is located in New Delhi. Extra Detail → It is India\'s national academy for music, dance and drama.' },

{ id: 'static-dance-056', category: 'Kathak Personalities', question: 'Famous classical dancer Shovana Narayan is associated with which dance style?', options: ['Bharatanatyam', 'Kuchipudi', 'Kathak', 'Kathakali'], answer: 2, explanation: 'Shovana Narayan is a renowned Kathak dancer. Extra Detail → She is particularly associated with the Lucknow tradition of Kathak.' },

{ id: 'static-dance-057', category: 'Kathakali', question: 'Which South Indian classical dance form literally means \'story-play\'?', options: ['Kathakali', 'Bharatanatyam', 'Kathak', 'Mohiniyattam'], answer: 0, explanation: 'Kathakali literally combines \'katha\' (story) and \'kali\' (play/performance). Extra Detail → It is a highly stylised dance-drama tradition of Kerala.' },

{ id: 'static-dance-058', category: 'Manipuri', question: 'Manipuri dance style is mainly based on which subject?', options: ['Lord Shiva', 'Lord Brahma', 'Krishna-Gopis', 'Lord Vishnu'], answer: 2, explanation: 'Manipuri is strongly centred on Krishna-Radha and Krishna-Gopi devotional themes. Extra Detail → Ras Leela is one of its best-known devotional dance traditions.' },

{ id: 'static-dance-059', category: 'Festivals & Dance', question: 'Which festival is celebrated with dances like Dandiya and Garba?', options: ['Baisakhi', 'Navratri', 'Bihu', 'Shivratri'], answer: 1, explanation: 'Navratri is celebrated with Garba and Dandiya, especially in Gujarat. Extra Detail → The dances are performed over the nine-night festival dedicated to the Goddess.' },

{ id: 'static-dance-060', category: 'Himachal Pradesh Folk Dance', question: 'Which state is known for the Jhoori dance, related to Jhumar and performed by both men and women?', options: ['Punjab', 'Assam', 'Himachal Pradesh', 'Rajasthan'], answer: 2, explanation: 'The PDF associates Jhoori with Himachal Pradesh. Extra Detail → Himachal Pradesh has a rich folk-dance tradition including Nati and other regional forms.' },

{ id: 'static-dance-061', category: 'Punjab Folk Dance', question: 'What is the female counterpart of men\'s Bhangra called?', options: ['Ghoomar', 'Kalbelia', 'Garba', 'Giddha'], answer: 3, explanation: 'Giddha is the famous women\'s folk dance of Punjab, often treated as the female counterpart of Bhangra. Extra Detail → It features clapping, expressive gestures and traditional boliyan.' },

{ id: 'static-dance-062', category: 'Chhau', question: 'In which of the following dance styles is singing not used?', options: ['Chhau', 'Bharatanatyam', 'Odissi', 'Kathak'], answer: 0, explanation: 'The PDF identifies Chhau. Extra Detail → Chhau performances rely heavily on instrumental music, vigorous movement and dramatic choreography rather than sung text by the dancers.' },

{ id: 'static-dance-063', category: 'Sattriya', question: 'Independent dances like Chali, Ramdani and Jhumura belong to which dance style?', options: ['Sattriya', 'Bharatanatyam', 'Chhau', 'Manipuri'], answer: 0, explanation: 'Chali, Ramdani and Jhumura are associated with Sattriya. Extra Detail → These are part of Assam\'s classical Vaishnav dance repertoire.' },

{ id: 'static-dance-064', category: 'Raasleela', question: 'Which dance style depicts the love stories of Radha and Krishna?', options: ['Raasleela', 'Kalbelia', 'Giddha', 'Matki'], answer: 0, explanation: 'Raasleela depicts the devotional love of Radha and Krishna. Extra Detail → It is especially associated with the Braj tradition and Krishna bhakti.' },

{ id: 'static-dance-065', category: 'Kuchipudi', question: 'Kuchipudi gets its name from Kuchelapuram village, located in which state?', options: ['Andhra Pradesh', 'Kerala', 'Karnataka', 'Tamil Nadu'], answer: 0, explanation: 'Kuchipudi derives its name from the village of Kuchelapuram/Kuchipudi in Andhra Pradesh. Extra Detail → It developed as a dance-drama tradition with strong links to Telugu culture.' },

{ id: 'static-dance-066', category: 'Tamil Nadu Folk Dance', question: 'What is the most popular folk dance of Tamil Nadu according to the PDF?', options: ['Karagattam', 'Koodiyattam', 'Yakshagana', 'Kathakali'], answer: 0, explanation: 'Karagattam is identified as a popular folk dance of Tamil Nadu. Extra Detail → It is known for performers balancing decorated pots on their heads.' },

{ id: 'static-dance-067', category: 'Dance Classification', question: 'Which of the following is NOT a folk dance of India?', options: ['Mohiniyattam', 'Lavani', 'Kalbelia', 'Rouf'], answer: 0, explanation: 'Mohiniyattam is a classical dance of Kerala, not a folk dance. Extra Detail → Lavani is associated with Maharashtra, Kalbelia with Rajasthan and Rouf with Jammu and Kashmir.' },

{ id: 'static-dance-068', category: 'Kathak Personalities', question: 'Who among the following is a famous Kathak dancer?', options: ['Josyula Seetharamaiah', 'Padma Subrahmanyam', 'Birju Maharaj', 'Geeta Chandran'], answer: 2, explanation: 'Pandit Birju Maharaj was a legendary Kathak dancer. Extra Detail → Padma Subrahmanyam and Geeta Chandran are primarily associated with Bharatanatyam.' },

{ id: 'static-dance-069', category: 'Uttarakhand Folk Dance', question: 'Chholiya dance is associated with which state?', options: ['Haryana', 'Rajasthan', 'Bihar', 'Uttarakhand'], answer: 3, explanation: 'Chholiya is a traditional sword dance of Uttarakhand, especially the Kumaon region. Extra Detail → It is commonly performed during wedding processions.' },

{ id: 'static-dance-070', category: 'Bharatanatyam', question: 'Which statements about Bharatanatyam are correct: it is traditionally a solo form, Rukmini Devi Arundale played a major role in its revival, and Alarippu is the final concluding item?', options: ['Only 1 and 2', 'Only 2 and 3', 'Only 1 and 3', '1, 2 and 3'], answer: 0, explanation: 'Statements 1 and 2 are correct. Extra Detail → Alarippu is generally an opening item in Bharatanatyam repertoire, not the final concluding item.' },

{ id: 'static-dance-071', category: 'Dance Personality Matching', question: 'Which dance-personality pair is NOT correctly matched?', options: ['Sattriya–Srimanta Sankardeva', 'Kuchipudi–Siddhendra Yogi', 'Mohiniyattam–Vallathol Narayana Menon', 'Kathak–Chatur Panigrahi'], answer: 3, explanation: 'Kathak–Chatur Panigrahi is incorrect. Extra Detail → Chatur Panigrahi was associated with Odissi; Srimanta Sankardeva with Sattriya and Siddhendra Yogi with Kuchipudi.' },

{ id: 'static-dance-072', category: 'Kathakali', question: 'Which statements regarding Kathakali are correct: it is mainly performed by men, green facial makeup represents noble/heroic characters, and the lead singer is called Bhagavathar?', options: ['Only 1 and 2', 'Only 1 and 3', 'Only 2 and 3', '1, 2 and 3'], answer: 1, explanation: 'According to the PDF, statements 1 and 3 are correct. Extra Detail → Kathakali is a Kerala dance-drama tradition with elaborate character-specific makeup and a strong vocal-instrumental accompaniment.' },

{ id: 'static-dance-073', category: 'Dance-State Matching', question: 'Which is the correct matching of Chhau, Yakshagana, Bhavai and Theyyam with their regions?', options: ['Chhau–WB/Jharkhand/Odisha; Yakshagana–Karnataka; Bhavai–Rajasthan/Gujarat; Theyyam–Kerala', 'Chhau–Karnataka; Yakshagana–Kerala; Bhavai–WB; Theyyam–Gujarat', 'Chhau–Kerala; Yakshagana–Rajasthan; Bhavai–Karnataka; Theyyam–Odisha', 'Chhau–Odisha only; Yakshagana–Tamil Nadu; Bhavai–Punjab; Theyyam–Assam'], answer: 0, explanation: 'Correct mapping → Chhau–West Bengal/Jharkhand/Odisha, Yakshagana–Karnataka, Bhavai–Rajasthan/Gujarat and Theyyam–Kerala. Extra Detail → These forms represent diverse regional folk and ritual performance traditions.' },

{ id: 'static-dance-074', category: 'Manipuri', question: 'Jagoi and Cholom are two major components of which classical dance?', options: ['Odissi', 'Manipuri', 'Sattriya', 'Kathak'], answer: 1, explanation: 'Jagoi and Cholom are major components of Manipuri. Extra Detail → Cholom includes vigorous drum dances such as Pung Cholom, while Jagoi refers to graceful dance forms.' },

{ id: 'static-dance-075', category: 'Odissi', question: 'Which statement is incorrect regarding Odissi dance?', options: ['Tribhanga represents three bends', 'It is associated with the Mahari tradition of Jagannath Temple', 'Dancers traditionally wear wooden ornaments and headgear', 'Kelucharan Mohapatra was a prominent revivalist'], answer: 2, explanation: 'The incorrect statement is that Odissi dancers wear wooden ornaments. Extra Detail → Odissi is known for silver jewellery, characteristic head ornaments, Tribhanga posture and strong links with the Jagannath temple tradition.' },

{ id: 'static-dance-076', category: 'Kuchipudi', question: 'Tarangam and Jala-Chitra Nrityam are key features of which dance?', options: ['Bharatanatyam', 'Kuchipudi', 'Mohiniyattam', 'Kathakali'], answer: 1, explanation: 'These are associated with Kuchipudi. Extra Detail → Tarangam is famous for dancing on the edges of a brass plate, while Jala-Chitra involves drawing patterns with the toes.' },

{ id: 'static-dance-077', category: 'Classical Dance Classification', question: 'According to the PDF, how many classical dances are recognised in India and which dance is mentioned as an additional classical dance by the Ministry of Culture?', options: ['7; Kalbelia', '8; Chhau', '9; Yakshagana', '8; Bihu'], answer: 1, explanation: 'The PDF gives the answer as 8 recognised classical dances with Chhau mentioned as an additional classical dance in the question framing. Extra Detail → This explanation preserves the source PDF\'s wording.' },

{ id: 'static-dance-078', category: 'Dance-State Matching', question: 'Which of the following folk dances is NOT associated with Rajasthan?', options: ['Chari', 'Ghoomar', 'Terah Taali', 'Maach'], answer: 3, explanation: 'Maach is associated with Madhya Pradesh, not Rajasthan. Extra Detail → Chari, Ghoomar and Terah Taali are well-known folk traditions of Rajasthan.' },

{ id: 'static-dance-079', category: 'Sattriya', question: 'Consider Sattriya: it developed in Vaishnav monasteries called Sattras, includes classical devotional themes and mudras, and its Lasya part is called Tandava. Which statements are correct?', options: ['Only 1 and 2', 'Only 2 and 3', 'Only 1 and 3', '1, 2 and 3'], answer: 0, explanation: 'Only statements 1 and 2 are correct. Extra Detail → Sattriya arose in Assam\'s Sattras and was shaped by the Vaishnavite tradition of Srimanta Sankardeva.' },

{ id: 'static-dance-080', category: 'Jammu & Kashmir Folk Dance', question: 'Rouf and Hikat are famous folk dances of which State/UT?', options: ['Ladakh', 'Jammu and Kashmir', 'Himachal Pradesh', 'Uttarakhand'], answer: 1, explanation: 'Rouf and Hikat are associated with Jammu and Kashmir. Extra Detail → Rouf is especially known as a graceful group dance traditionally performed by women.' },

{ id: 'static-dance-081', category: 'Kathak Gharanas', question: 'Which set correctly matches major Kathak gharanas with their features?', options: ['Lucknow–delicacy, grace and abhinaya; Jaipur–strong tatkar and complex rhythm; Banaras–Thumri and expressive bhava', 'Lucknow–martial masks; Jaipur–temple Mahari; Banaras–bamboo dance', 'Lucknow–Carnatic music; Jaipur–Jagoi; Banaras–Cholom', 'Lucknow–Bihu; Jaipur–Garba; Banaras–Lavani'], answer: 0, explanation: 'The PDF treats all three gharana-feature pairs as correct. Extra Detail → Lucknow is celebrated for nazakat and abhinaya, Jaipur for vigorous rhythm and footwork, and Banaras for distinctive expressive and rhythmic traditions.' },

{ id: 'static-dance-082', category: 'Kalbelia', question: 'Which statement is NOT correct regarding Kalbelia dance?', options: ['It is performed by women of Rajasthan\'s snake-charmer community', 'It was inscribed on UNESCO\'s Intangible Cultural Heritage list in 2010', 'Pungi and Daf are important instruments', 'Men and women rotate only at a slow pace'], answer: 3, explanation: 'The incorrect statement is the claim that men and women rotate only at a slow pace. Extra Detail → Kalbelia is known for energetic, swirling movements and is associated with Rajasthan\'s Kalbelia community.' },

{ id: 'static-dance-083', category: 'Chhattisgarh Folk Theatre', question: 'Pandavani folk dance-theatre belongs to which state and who is a famous exponent of its Kapalik style?', options: ['Jharkhand; Mukund Nayak', 'Madhya Pradesh; Teejan Bai', 'Chhattisgarh; Teejan Bai', 'Odisha; Sanjukta Panigrahi'], answer: 2, explanation: 'Pandavani is associated with Chhattisgarh and Teejan Bai is its most famous exponent. Extra Detail → Pandavani narrates episodes from the Mahabharata, especially stories centred on the Pandavas.' },

{ id: 'static-dance-084', category: 'Classical Dance Personalities', question: 'Which matching of dancers with dance forms is correct: Birju Maharaj, Yamini Krishnamurthy, Vempati Chinna Satyam and Kalyanikutty Amma?', options: ['Kathak, Bharatanatyam, Kuchipudi, Mohiniyattam', 'Kathak, Mohiniyattam, Bharatanatyam, Kuchipudi', 'Odissi, Bharatanatyam, Kathak, Mohiniyattam', 'Kuchipudi, Kathak, Odissi, Bharatanatyam'], answer: 0, explanation: 'Correct mapping → Birju Maharaj–Kathak, Yamini Krishnamurthy–Bharatanatyam, Vempati Chinna Satyam–Kuchipudi and Kalyanikutty Amma–Mohiniyattam.' },

{ id: 'static-dance-085', category: 'Nagaland Folk Dance', question: 'Chang Lo or Sua Lua dance is performed by which tribe of Nagaland?', options: ['Angami', 'Chang', 'Konyak', 'Ao'], answer: 1, explanation: 'Chang Lo is associated with the Chang tribe of Nagaland. Extra Detail → It is performed during traditional community celebrations and is also known as Sua Lua.' },

{ id: 'static-dance-086', category: 'Kathak', question: 'Which classical dance integrates both Tandava and Lasya aspects and uses terms such as Tatkar, Toda and Tukda?', options: ['Bharatanatyam', 'Kathak', 'Odissi', 'Kuchipudi'], answer: 1, explanation: 'Kathak is the correct answer. Extra Detail → Tatkar refers to footwork, while Toda and Tukda are important rhythmic compositions in Kathak.' },

{ id: 'static-dance-087', category: 'Chhau', question: 'Which statements are correct about Mayurbhanj Chhau: it is prevalent in Odisha\'s Mayurbhanj region, does not use masks, and presents martial art movements, animal-bird movements and everyday activities?', options: ['Only 1 and 2', 'Only 1 and 3', 'Only 2 and 3', '1, 2 and 3'], answer: 3, explanation: 'All three statements are correct according to the PDF. Extra Detail → Mayurbhanj Chhau is distinctive because, unlike some other Chhau traditions, it is performed without masks.' },

{ id: 'static-dance-088', category: 'Kerala Theatre', question: 'Which statement is NOT correct regarding Koodiyattam?', options: ['It is a traditional Sanskrit theatre and dance form of Kerala', 'It was declared India\'s first UNESCO ICH masterpiece', 'It is performed by Chakyar and Nambiar communities', 'Female roles are performed exclusively by male actors'], answer: 3, explanation: 'The incorrect statement is that female roles are performed exclusively by male actors. Extra Detail → Koodiyattam is a classical Sanskrit theatre tradition of Kerala with specialised hereditary performer communities.' },

{ id: 'static-dance-089', category: 'Garba', question: 'Which statements regarding Garba are correct: it is a Gujarati folk dance performed during Navratri around a lamp or symbolic centre, the word is linked with \'garbha\', and UNESCO inscribed Garba on the ICH Representative List in December 2023?', options: ['Only 1 and 2', 'Only 2 and 3', 'Only 1 and 3', '1, 2 and 3'], answer: 3, explanation: 'All three statements are correct according to the PDF. Extra Detail → Garba\'s circular movement symbolises continuity of life around the divine centre.' },

{ id: 'static-dance-090', category: 'Dance-State Matching', question: 'Which of the following folk dance-state pairs is correctly matched?', options: ['Cheraw–Mizoram', 'Bihu–Manipur', 'Lava–Sikkim', 'Fugdi–Himachal Pradesh'], answer: 0, explanation: 'Cheraw–Mizoram is correctly matched. Extra Detail → Cheraw is the famous bamboo dance of Mizoram.' },

{ id: 'static-dance-091', category: 'Mohiniyattam', question: 'Which statement is NOT correct regarding Mohiniyattam?', options: ['It is a solo Lasya dance traditionally performed by women', 'The costume commonly includes an off-white Kasavu sari with golden border', 'It prominently features fast, jerky and sharp foot movements', 'It is inspired by Lord Vishnu\'s Mohini incarnation'], answer: 2, explanation: 'The incorrect statement is that Mohiniyattam prominently uses fast, jerky and sharp foot movements. Extra Detail → Mohiniyattam is known for soft, swaying, graceful Lasya movements.' },

{ id: 'static-dance-092', category: 'Natya Shastra', question: 'Who is the author of the Natya Shastra, and which rasa was not part of the original eight and was added later?', options: ['Nandikeshvara; Bhayanaka', 'Bharata Muni; Shanta', 'Abhinavagupta; Raudra', 'Sarangadeva; Karuna'], answer: 1, explanation: 'Bharata Muni is traditionally credited with the Natya Shastra, and Shanta Rasa is regarded as the later addition to the original eight rasas. Extra Detail → The nine rasas together are known as Navarasa.' },

{ id: 'static-dance-093', category: 'Bihar Folk Theatre', question: 'Jat-Jatin and Bidesia are prominent folk dance/theatre forms of which state?', options: ['Uttar Pradesh', 'Bihar', 'West Bengal', 'Jharkhand'], answer: 1, explanation: 'Jat-Jatin and Bidesia are associated with Bihar. Extra Detail → Both reflect regional social life and storytelling traditions of Bihar.' },

{ id: 'static-dance-094', category: 'Northeast Folk Dance', question: 'Mattukong and Bardo Chham folk dances belong to which northeastern state?', options: ['Arunachal Pradesh', 'Meghalaya', 'Tripura', 'Nagaland'], answer: 0, explanation: 'The pair is associated with Arunachal Pradesh according to the question. Extra Detail → Bardo Chham is a masked Buddhist dance tradition of Arunachal Pradesh.' },

{ id: 'static-dance-095', category: 'Dance-State Matching', question: 'Which of the following pairs is NOT correctly matched?', options: ['Yakshagana–Karnataka', 'Karma Dance–Madhya Pradesh/Chhattisgarh', 'Danda Nata–Odisha', 'Karagattam–Andhra Pradesh'], answer: 3, explanation: 'Karagattam–Andhra Pradesh is incorrect. Extra Detail → Karagattam is a folk dance of Tamil Nadu; Yakshagana belongs to Karnataka and Danda Nata to Odisha.' },

{ id: 'static-dance-096', category: 'Uttar Pradesh Folk Dance', question: 'Consider Charkula dance: it is a major folk dance of the Braj region of Uttar Pradesh; women balance large multi-tiered lamps on their heads; and it is performed around the birth celebrations of Radha/Krishna traditions. Which statements are correct?', options: ['Only 1 and 2', 'Only 2 and 3', 'Only 1 and 3', '1, 2 and 3'], answer: 3, explanation: 'All three statements are treated as correct in the PDF. Extra Detail → Charkula is especially associated with the Braj cultural region and spectacular balancing of lamp structures.' },

{ id: 'static-dance-097', category: 'Tripura Folk Dance', question: 'Hojagiri folk dance is performed by the Reang (Bru) tribe of which state?', options: ['Assam', 'Tripura', 'Meghalaya', 'Manipur'], answer: 1, explanation: 'Hojagiri is associated with the Reang or Bru community of Tripura. Extra Detail → It is known for remarkable balance and controlled body movements.' },

{ id: 'static-dance-098', category: 'Maharashtra Folk Theatre', question: 'According to the PDF, which statements regarding Lavani and Tamasha are correct: Lavani is a traditional dance-song form of Maharashtra often accompanied by Dholki, it received royal patronage during the Peshwa period, and Tamasha consists only of serious classical music with no humour or satire?', options: ['Only 1 and 2', 'Only 2 and 3', 'Only 1 and 3', '1, 2 and 3'], answer: 0, explanation: 'Only statements 1 and 2 are correct. Extra Detail → Tamasha is a lively folk theatre tradition that includes music, dance, humour and satire.' },

{ id: 'static-dance-099', category: 'Martial Dance Matching', question: 'Which is the correct matching of traditional martial arts/dances with states: Kalaripayattu, Thang-Ta, Silambam and Gatka?', options: ['Kerala, Manipur, Tamil Nadu, Punjab', 'Manipur, Kerala, Punjab, Tamil Nadu', 'Kerala, Tamil Nadu, Manipur, Punjab', 'Punjab, Manipur, Tamil Nadu, Kerala'], answer: 0, explanation: 'Correct mapping → Kalaripayattu–Kerala, Thang-Ta–Manipur, Silambam–Tamil Nadu and Gatka–Punjab. Extra Detail → These traditions combine physical discipline, weapons training and performance elements.' },
{ id: 'static-dance-100', category: 'Rajasthan Folk Dance', question: 'What does the word \'Ghoomar\' mean in Rajasthani?', options: ['Twirl or circular movement', 'Harvest song', 'Warrior march', 'Temple procession'], answer: 0, explanation: 'Ghoomar refers to a twirling or circular movement. Extra Detail → The transcript explains the name through the idea of \'ghoomna\' or turning around, which reflects the circular style of the dance.' },

{ id: 'static-dance-101', category: 'Rajasthan Folk Dance', question: 'Which tribal community is described in the transcript as the earliest performer of Ghoomar?', options: ['Bhil', 'Gond', 'Bodo', 'Baiga'], answer: 0, explanation: 'The transcript identifies the Bhil tribe as the earliest performers of Ghoomar. Extra Detail → It says the dance was later adopted by the Rajput community and is performed during festivals such as Teej and Gangaur.' },

{ id: 'static-dance-102', category: 'South Indian Folk Dance', question: 'Kolattam is popularly known by which name?', options: ['Stick Dance', 'Peacock Dance', 'Butterfly Dance', 'Dance of Warriors'], answer: 0, explanation: 'Kolattam is described as the \'Stick Dance\'. Extra Detail → The transcript associates it broadly with South India, especially Andhra Pradesh, Tamil Nadu and Karnataka, and notes that women commonly perform it with sticks.' },

{ id: 'static-dance-103', category: 'Telangana Folk Dance', question: 'Perini Shiva Tandavam is popularly known as which type of dance?', options: ['Dance of Warriors', 'Temple Lamp Dance', 'Harvest Dance', 'Peacock Dance'], answer: 0, explanation: 'Perini Shiva Tandavam is described as the \'Dance of Warriors\'. Extra Detail → The transcript links it with Telangana and the Kakatiya period, describing it as a vigorous pre-battle performance dedicated to Lord Shiva.' },

{ id: 'static-dance-104', category: 'Chhattisgarh Tribal Dance', question: 'Bison Horn Maria dance is primarily associated with which tribal community?', options: ['Maria or Dandami Maria', 'Bodo', 'Reang', 'Kalbelia'], answer: 0, explanation: 'Bison Horn Maria dance is performed by the Maria or Dandami Maria community. Extra Detail → The transcript describes the community as a subgroup of the Gond tribe and places the dance mainly in the Bastar region of Chhattisgarh.' },

{ id: 'static-dance-105', category: 'Chhattisgarh Tribal Dance', question: 'What does the Bison Horn Maria dance mainly imitate?', options: ['Movements of a wild bison', 'Flight of butterflies', 'Peacock movements', 'Sword combat'], answer: 0, explanation: 'The dance imitates the movements of a wild bison. Extra Detail → The transcript explains the name through the bison\'s horns and notes that male performers wear distinctive headgear.' },

{ id: 'static-dance-106', category: 'Himachal Pradesh Folk Dance', question: 'Gaddi Nati is associated with which state?', options: ['Himachal Pradesh', 'Assam', 'Odisha', 'Gujarat'], answer: 0, explanation: 'Gaddi Nati is associated with Himachal Pradesh. Extra Detail → The transcript particularly mentions the Chamba valley and Bharmour region while discussing this dance tradition.' },

{ id: 'static-dance-107', category: 'Baiga Tribal Dance', question: 'Baiga Pardhoni is especially performed on which occasion?', options: ['Marriage ceremonies', 'Navratri', 'Bihu', 'Onam'], answer: 0, explanation: 'The transcript describes Baiga Pardhoni as an energetic wedding dance. Extra Detail → It is performed by the Baiga community, especially when welcoming the bride\'s family, and is associated with areas of Madhya Pradesh and Chhattisgarh.' },

{ id: 'static-dance-108', category: 'Assam Folk Dance', question: 'Bagurumba is primarily performed by which community of Assam?', options: ['Bodo', 'Naga', 'Mizo', 'Reang'], answer: 0, explanation: 'Bagurumba is performed by the Bodo community of Assam. Extra Detail → The transcript also calls it a nature-inspired or \'butterfly\' dance because its movements evoke butterflies, birds and other elements of nature.' },

{ id: 'static-dance-109', category: 'Kerala Ritual Dance', question: 'Theyyam is mainly associated with which region of Kerala?', options: ['North Malabar', 'Central Travancore', 'Palakkad plains', 'Kuttanad'], answer: 0, explanation: 'Theyyam is mainly associated with the North Malabar region. Extra Detail → The transcript specifically mentions Kannur and Kasaragod districts and describes Theyyam as an intense ritual performance in which the performer embodies a deity or sacred figure.' },

{ id: 'static-dance-110', category: 'Manipuri Dance', question: 'Pung Cholom is mainly performed using which musical instrument?', options: ['Drum', 'Flute', 'Veena', 'Shehnai'], answer: 0, explanation: 'Pung Cholom is a drum-based Manipuri dance. Extra Detail → The transcript explains that \'Pung\' is a type of drum and describes the performance as beginning slowly before becoming highly energetic.' },

{ id: 'static-dance-111', category: 'Manipuri Dance', question: 'Pung Cholom is commonly performed during which Manipuri festival mentioned in the transcript?', options: ['Yaoshang', 'Onam', 'Baisakhi', 'Hornbill Festival'], answer: 0, explanation: 'The transcript links Pung Cholom with Yaoshang, the Manipuri celebration of Holi. Extra Detail → It also states that the dance is mainly performed by men and becomes increasingly vigorous as it progresses.' },

{ id: 'static-dance-112', category: 'Punjab Folk Dance', question: 'Which traditional poetic form is sung during Giddha performances?', options: ['Boliyan', 'Thumri', 'Dhrupad', 'Tarana'], answer: 0, explanation: 'Giddha performers sing Boliyan. Extra Detail → The transcript describes women performing Giddha in a circle, clapping rhythmically, especially during occasions such as Teej and Lohri.' },

{ id: 'static-dance-113', category: 'Tripura Folk Dance', question: 'Hojagiri is performed by which community of Tripura?', options: ['Reang (Bru)', 'Bodo', 'Gond', 'Siddi'], answer: 0, explanation: 'Hojagiri is performed by the Reang or Bru community of Tripura. Extra Detail → The transcript links it with the Hojagiri festival and says it is performed to please Goddess Mailuma and Goddess Lakshmi during the harvest season.' },

{ id: 'static-dance-114', category: 'Tripura Folk Dance', question: 'Which feature is especially highlighted in the transcript for Hojagiri dance?', options: ['Balancing objects while mainly moving the lower body', 'Using swords in mock combat', 'Dancing only with sticks', 'Wearing large warrior masks'], answer: 0, explanation: 'The transcript highlights Hojagiri\'s difficult balancing movements, with performers balancing items such as pots and bottles while making controlled lower-body movements.' },

{ id: 'static-dance-115', category: 'Kerala Folk Dance', question: 'Oppana is traditionally performed by which community of Kerala?', options: ['Mappila Muslim community', 'Nair community', 'Toda community', 'Bodo community'], answer: 0, explanation: 'Oppana is performed by Kerala\'s Mappila Muslim community. Extra Detail → The transcript links it mainly with weddings in the Malabar region.' },

{ id: 'static-dance-116', category: 'Kerala Folk Dance', question: 'Which form of Oppana is described as involving rhythmic clapping?', options: ['Oppana Murukkam', 'Oppana Chayal', 'Pung Cholom', 'Thiruvathira'], answer: 0, explanation: 'The transcript distinguishes two forms of Oppana: Oppana Chayal without clapping and Oppana Murukkam with continuous rhythmic clapping.' },

{ id: 'static-dance-117', category: 'Gujarat Folk Dance', question: 'Dhamaal dance in Gujarat is mainly associated with which community?', options: ['Siddi community', 'Bhil community', 'Bodo community', 'Reang community'], answer: 0, explanation: 'The Gujarat form of Dhamaal is associated with the Siddi community. Extra Detail → The transcript describes the Siddis as a community of African origin settled in Gujarat.' },

{ id: 'static-dance-118', category: 'Jammu & Kashmir Folk Dance', question: 'Dhoomal dance of Jammu and Kashmir is associated with which community mentioned in the transcript?', options: ['Vattal community', 'Bodo community', 'Maria tribe', 'Mappila community'], answer: 0, explanation: 'The transcript associates Dhoomal with men of the Vattal community in Jammu and Kashmir. Extra Detail → It also connects the tradition with a Sufi saint.' },

{ id: 'static-dance-119', category: 'Kerala Folk Dance', question: 'Thiruvathirakali is mainly performed by whom?', options: ['Women', 'Only male warriors', 'Monks', 'Children only'], answer: 0, explanation: 'Thiruvathirakali is described as a women\'s group dance. Extra Detail → The transcript notes white Kasavu saris, circular dancing around a central lamp, and performance during Thiruvathira and Onam in Kerala.' },

{ id: 'static-dance-120', category: 'Kerala Folk Dance', question: 'Which costume is specifically associated with women performing Thiruvathirakali in the transcript?', options: ['Kasavu sari', 'Mekhela Chador', 'Phanek', 'Ghagra with mirror work'], answer: 0, explanation: 'Women performing Thiruvathirakali are described as wearing the white Kasavu sari. Extra Detail → The dance is performed in a circle around a central lamp and is associated with Kerala.' },

{ id: 'static-dance-121', category: 'Odisha Folk Dance', question: 'Saila dance is associated with which state according to the transcript?', options: ['Odisha', 'Punjab', 'Kerala', 'Assam'], answer: 0, explanation: 'The transcript associates Saila with Odisha. Extra Detail → It appears in the state-dance matching discussion alongside Thiruvathirakali of Kerala and Rouf of Kashmir.' },

{ id: 'static-dance-122', category: 'Jammu & Kashmir Folk Dance', question: 'Rouf is mainly performed by which group according to the transcript?', options: ['Kashmiri women', 'Only male warriors', 'Bodo women', 'Siddi men'], answer: 0, explanation: 'Rouf is mainly performed by Kashmiri women. Extra Detail → The transcript contrasts it with Dhoomal, which it associates with men of the Vattal community.' },

{ id: 'static-dance-123', category: 'Assam Festivals & Dance', question: 'Which of the following correctly matches the three major Bihu festivals with their alternative names?', options: ['Bohag–Rongali, Kati–Kangali, Magh–Bhogali', 'Bohag–Bhogali, Kati–Rongali, Magh–Kangali', 'Bohag–Kangali, Kati–Bhogali, Magh–Rongali', 'Bohag–Onam, Kati–Baisakhi, Magh–Lohri'], answer: 0, explanation: 'Correct mapping → Bohag Bihu is Rongali Bihu, Kati Bihu is Kangali Bihu and Magh Bihu is Bhogali Bihu. Extra Detail → The transcript connects them broadly with April/New Year, October and January respectively.' },

{ id: 'static-dance-124', category: 'Assam Folk Dance', question: 'Which traditional costume is worn by women while performing Bihu dance?', options: ['Mekhela Chador', 'Kasavu sari', 'Phanek', 'Pheran'], answer: 0, explanation: 'Women performing Bihu wear the Mekhela Chador. Extra Detail → The transcript mentions this costume while explaining the three major Bihu festivals of Assam.' },

{ id: 'static-dance-125', category: 'Haryana Folk Dance', question: 'Which dance, though strongly associated with Rajasthan, is also described in the transcript as being performed in Haryana?', options: ['Ghoomar', 'Garba', 'Kuchipudi', 'Giddha'], answer: 0, explanation: 'The transcript states that Ghoomar is performed not only in Rajasthan but also in Haryana. Extra Detail → This illustrates how some folk dances can cross present-day state boundaries, unlike many classical forms that are strongly tied to one region.' },

{ id: 'static-dance-126', category: 'South Indian Folk Dance', question: 'Mailattam is popularly known as which dance?', options: ['Peacock Dance', 'Butterfly Dance', 'Bison Dance', 'Warrior Dance'], answer: 0, explanation: 'Mailattam is described as the Peacock Dance. Extra Detail → The transcript says performers use peacock feathers and associates the dance with Kerala and Tamil Nadu.' },

{ id: 'static-dance-127', category: 'South Indian Folk Dance', question: 'Mailattam is performed in honour of which deity according to the transcript?', options: ['Lord Murugan', 'Lord Krishna', 'Lord Jagannath', 'Goddess Saraswati'], answer: 0, explanation: 'The transcript says Mailattam is performed to honour Lord Murugan. Extra Detail → It also mentions its performance during the Arattu festival and notes that Murugan is especially revered in South India.' },
]