const staticGeographyQuestions = [

  // ===================== RIVERS =====================
  { id: 'rivers-001', category: 'Rivers', question: "The Ganga River, considered sacred by millions and central to India's cultural and religious heritage, originates from a glacier in the Himalayas before flowing across the Indo-Gangetic Plain. In which Indian state does its source glacier lie?", options: ['Uttarakhand', 'Himachal Pradesh', 'Uttar Pradesh', 'Sikkim'], answer: 0, explanation: 'The Ganga originates from the Gangotri Glacier (Gaumukh) in Uttarakhand.' },
  { id: 'rivers-002', category: 'Rivers', question: 'The Yangtze River is the longest river in Asia and has historically supported dense agricultural settlement along its banks. It flows entirely within, and finally empties into the sea off the coast of, which country?', options: ['Japan', 'China', 'Vietnam', 'South Korea'], answer: 1, explanation: 'The Yangtze flows entirely within China and empties into the East China Sea.' },
  { id: 'rivers-003', category: 'Rivers', question: 'The Mississippi River, along with its tributary the Missouri, forms one of the largest river systems in the world and was historically vital for trade and transport in North America. Into which body of water does it empty?', options: ['Atlantic Ocean', 'Pacific Ocean', 'Gulf of Mexico', 'Hudson Bay'], answer: 1, explanation: 'The Mississippi River empties into the Gulf of Mexico.' },
  { id: 'rivers-004', category: 'Rivers', question: 'The Indus River gave its name to the Indian subcontinent and nurtured one of the earliest urban civilizations. Rising in Tibet and flowing largely through Pakistan, into which sea does it finally drain?', options: ['Arabian Sea', 'Bay of Bengal', 'Caspian Sea', 'Persian Gulf'], answer: 1, explanation: 'The Indus River empties into the Arabian Sea near Karachi.' },
  { id: 'rivers-005', category: 'Rivers', question: 'The Volga is the longest river in Europe and has long served as a major inland waterway for Russia. Into which body of water does the Volga eventually drain?', options: ['Black Sea', 'Baltic Sea', 'Caspian Sea', 'Sea of Azov'], answer: 0, explanation: 'The Volga River drains into the landlocked Caspian Sea.' },

  // ===================== MOUNTAINS & PEAKS =====================
  { id: 'mountains-001', category: 'Mountains & Peaks', question: "Mount Everest, the world's highest peak above sea level, straddles the border of Nepal and the Tibet Autonomous Region of China. It forms part of which major mountain range?", options: ['Karakoram', 'Himalayas', 'Hindu Kush', 'Pamirs'], answer: 1, explanation: 'Mount Everest is part of the Himalayan mountain range.' },
  { id: 'mountains-002', category: 'Mountains & Peaks', question: 'K2, the second-highest mountain on Earth, is notorious among climbers for its extreme difficulty and high fatality rate. It is located in which mountain range on the border of Pakistan and China?', options: ['Himalayas', 'Karakoram', 'Hindu Kush', 'Zagros'], answer: 1, explanation: 'K2 lies in the Karakoram range.' },
  { id: 'mountains-003', category: 'Mountains & Peaks', question: 'The Andes form the longest continental mountain range in the world, running along the western edge of a continent and influencing the climate and culture of many nations. On which continent are the Andes located?', options: ['North America', 'South America', 'Africa', 'Asia'], answer: 1, explanation: 'The Andes run along the western coast of South America.' },
  { id: 'mountains-004', category: 'Mountains & Peaks', question: 'The Alps are a major mountain range stretching across several European countries and are popular for both winter sports and mountaineering. What is the name of the highest peak of the Alps, located near the France-Italy border?', options: ['Matterhorn', 'Mont Blanc', 'Eiger', 'Zugspitze'], answer: 1, explanation: 'Mont Blanc, on the France-Italy border, is the highest peak of the Alps.' },
  { id: 'mountains-005', category: 'Mountains & Peaks', question: 'The Ural Mountains run in a roughly north-south direction and are traditionally regarded as a natural boundary. Which two continents do the Urals separate?', options: ['Asia and Africa', 'Europe and Asia', 'Europe and Africa', 'Asia and North America'], answer: 1, explanation: 'The Ural Mountains form part of the conventional boundary between Europe and Asia.' },

  // ===================== LAKES =====================
  { id: 'lakes-001', category: 'Lakes', question: 'The Caspian Sea, despite its name, is classified as the largest lake in the world by area and is bordered by five countries. Which of the following countries does NOT border the Caspian Sea?', options: ['Russia', 'Iran', 'Turkey', 'Kazakhstan'], answer: 2, explanation: 'The Caspian Sea is bordered by Russia, Kazakhstan, Turkmenistan, Iran, and Azerbaijan; Turkey does not border it.' },
  { id: 'lakes-002', category: 'Lakes', question: 'Lake Superior is the largest of the Great Lakes by surface area and is considered the largest freshwater lake in the world by area. It lies on the border between the United States and which other country?', options: ['Mexico', 'Canada', 'None, it is entirely in the USA', 'Greenland'], answer: 1, explanation: 'Lake Superior lies on the border between the USA and Canada.' },
  { id: 'lakes-003', category: 'Lakes', question: 'The Dead Sea is renowned for its extremely high salinity, which allows swimmers to float effortlessly, and for being the lowest point on the land surface of the Earth. It lies on the border between Jordan and which other country?', options: ['Israel', 'Syria', 'Lebanon', 'Egypt'], answer: 0, explanation: 'The Dead Sea lies on the border between Jordan and Israel.' },
  { id: 'lakes-004', category: 'Lakes', question: 'Lake Victoria is the largest lake in Africa by area and serves as a major source for one of the world\'s great rivers. Which river flows out of Lake Victoria?', options: ['Congo River', 'Niger River', 'Nile River', 'Zambezi River'], answer: 2, explanation: 'Lake Victoria is a principal source of the Nile River.' },
  { id: 'lakes-005', category: 'Lakes', question: 'Lake Titicaca, set high in the Andes, is often cited as the highest navigable lake in the world and holds deep cultural significance for Andean civilizations. It straddles the border between Peru and which other country?', options: ['Chile', 'Bolivia', 'Ecuador', 'Colombia'], answer: 1, explanation: 'Lake Titicaca lies on the border between Peru and Bolivia.' },

  // ===================== WATERFALLS =====================
  { id: 'waterfalls-001', category: 'Waterfalls', question: "Angel Falls is recognized as the world's tallest uninterrupted waterfall, plunging from the edge of a tabletop mountain in a remote rainforest region. In which country is Angel Falls located?", options: ['Brazil', 'Venezuela', 'Colombia', 'Guyana'], answer: 1, explanation: 'Angel Falls is located in Canaima National Park, Venezuela.' },
  { id: 'waterfalls-002', category: 'Waterfalls', question: 'Niagara Falls, a major tourist attraction and source of hydroelectric power, actually consists of three separate falls. It lies on the border between the United States and which other country?', options: ['Mexico', 'Canada', 'None, it is entirely in the USA', 'Cuba'], answer: 1, explanation: 'Niagara Falls straddles the border between the USA and Canada.' },
  { id: 'waterfalls-003', category: 'Waterfalls', question: 'Victoria Falls, known locally as "the Smoke that Thunders," is one of the largest waterfalls in the world by combined width and height. It is formed by which African river?', options: ['Congo River', 'Zambezi River', 'Limpopo River', 'Orange River'], answer: 1, explanation: 'Victoria Falls is formed by the Zambezi River.' },
  { id: 'waterfalls-004', category: 'Waterfalls', question: 'Iguazu Falls consists of a vast system of hundreds of individual waterfalls set within a lush subtropical rainforest and is a UNESCO World Heritage Site. It lies on the border between Brazil and which other country?', options: ['Uruguay', 'Paraguay', 'Argentina', 'Bolivia'], answer: 2, explanation: 'Iguazu Falls lies on the border of Brazil and Argentina (with Paraguay nearby).' },
  { id: 'waterfalls-005', category: 'Waterfalls', question: 'Yosemite Falls is the tallest waterfall in North America and is a centerpiece attraction of a famous national park known for its granite cliffs. In which US state is Yosemite Falls located?', options: ['Oregon', 'California', 'Washington', 'Nevada'], answer: 1, explanation: 'Yosemite Falls is located in Yosemite National Park, California.' },

  // ===================== DESERTS =====================
  { id: 'deserts-001', category: 'Deserts', question: 'The Sahara is the largest hot desert in the world, covering much of the northern part of a continent and experiencing extreme temperature variations between day and night. On which continent is the Sahara located?', options: ['Asia', 'Africa', 'Australia', 'South America'], answer: 1, explanation: 'The Sahara Desert spans much of North Africa.' },
  { id: 'deserts-002', category: 'Deserts', question: 'The Thar Desert, also known as the Great Indian Desert, is a large arid region characterized by sand dunes and sparse vegetation. It lies primarily in which Indian state, extending into Pakistan?', options: ['Gujarat', 'Rajasthan', 'Punjab', 'Haryana'], answer: 1, explanation: 'The Thar Desert lies mainly in Rajasthan, extending into Pakistan.' },
  { id: 'deserts-003', category: 'Deserts', question: 'The Kalahari Desert is a semi-arid sandy region in southern Africa known for its unique wildlife adapted to scarce water. Which of the following countries does the Kalahari NOT extend into?', options: ['Botswana', 'Namibia', 'South Africa', 'Kenya'], answer: 3, explanation: 'The Kalahari Desert spans Botswana, Namibia and South Africa, but not Kenya.' },
  { id: 'deserts-004', category: 'Deserts', question: 'The Arabian Desert covers most of the Arabian Peninsula and includes the Rub al Khali, one of the largest continuous sand deserts in the world. In which region of the world is it located?', options: ['East Asia', 'Middle East', 'Central Asia', 'North Africa'], answer: 1, explanation: 'The Arabian Desert lies in the Middle East, covering most of the Arabian Peninsula.' },
  { id: 'deserts-005', category: 'Deserts', question: 'Although often not pictured as a desert due to its ice cover, a continent qualifies as the largest desert in the world by area because of its extremely low precipitation. Which continent is this?', options: ['Africa', 'Asia', 'Antarctica', 'Australia'], answer: 2, explanation: 'Antarctica is classified as the largest desert in the world due to its minimal precipitation, despite being ice-covered.' },

  // ===================== GRASSLANDS =====================
  { id: 'grasslands-001', category: 'Grasslands', question: 'The Prairies are extensive temperate grasslands that historically supported vast herds of bison and later became a major agricultural region for wheat cultivation. On which continent are the Prairies located?', options: ['South America', 'North America', 'Africa', 'Europe'], answer: 1, explanation: 'The Prairies are temperate grasslands of North America, spanning the USA and Canada.' },
  { id: 'grasslands-002', category: 'Grasslands', question: 'The Steppes are vast, largely treeless grassland plains that historically served as migration routes for nomadic peoples. They stretch across which continent, from Eastern Europe into Central Asia?', options: ['Africa', 'Eurasia', 'South America', 'Australia'], answer: 1, explanation: 'The Steppes extend across Eurasia, from Eastern Europe through Central Asia.' },
  { id: 'grasslands-003', category: 'Grasslands', question: 'The Savanna is a tropical grassland ecosystem characterized by scattered trees and seasonal rainfall, and it supports large populations of grazing animals and predators. On which continent is the Savanna most extensively found?', options: ['Africa', 'Asia', 'South America', 'Europe'], answer: 0, explanation: 'The Savanna biome is most extensively found in Africa, though it also occurs elsewhere.' },
  { id: 'grasslands-004', category: 'Grasslands', question: 'The Pampas are fertile lowland grasslands renowned for cattle ranching and grain production, and they are strongly associated with a South American country. Which country?', options: ['Brazil', 'Chile', 'Argentina', 'Peru'], answer: 2, explanation: 'The Pampas are grasslands primarily located in Argentina, extending into Uruguay.' },
  { id: 'grasslands-005', category: 'Grasslands', question: 'The Veld refers to open, elevated grassland regions in a southern African country, used extensively for grazing and agriculture. In which country is the Veld located?', options: ['South Africa', 'Namibia', 'Zimbabwe', 'Botswana'], answer: 0, explanation: 'The Veld is a term used for grassland regions in South Africa.' },

  // ===================== OCEANS & SEAS =====================
  { id: 'oceans-001', category: 'Oceans & Seas', question: 'The Pacific Ocean is the largest and deepest of the world\'s oceanic divisions, extending from the Arctic in the north to the Southern Ocean in the south. Which ocean is the second largest in the world?', options: ['Indian Ocean', 'Atlantic Ocean', 'Arctic Ocean', 'Southern Ocean'], answer: 1, explanation: 'The Atlantic Ocean is the second-largest ocean after the Pacific.' },
  { id: 'oceans-002', category: 'Oceans & Seas', question: 'The Mediterranean Sea is an almost fully enclosed sea bordered by Europe, North Africa, and the Middle East, and it has been central to trade and civilization for millennia. Which ocean does the Mediterranean Sea connect to via the Strait of Gibraltar?', options: ['Indian Ocean', 'Pacific Ocean', 'Atlantic Ocean', 'Arctic Ocean'], answer: 2, explanation: 'The Mediterranean Sea connects to the Atlantic Ocean through the Strait of Gibraltar.' },
  { id: 'oceans-003', category: 'Oceans & Seas', question: 'The Red Sea is a narrow, elongated seawater body known for its high salinity and vibrant coral reefs. It separates the Arabian Peninsula from which continent?', options: ['Asia', 'Africa', 'Europe', 'Australia'], answer: 1, explanation: 'The Red Sea separates the Arabian Peninsula from Africa.' },
  { id: 'oceans-004', category: 'Oceans & Seas', question: 'The Arctic Ocean is the smallest and shallowest of the world\'s oceans, largely covered by sea ice for much of the year. It surrounds which geographic pole?', options: ['South Pole', 'North Pole', 'Equator', 'Tropic of Cancer'], answer: 1, explanation: 'The Arctic Ocean surrounds the North Pole.' },
  { id: 'oceans-005', category: 'Oceans & Seas', question: 'The Indian Ocean is the third-largest of the world\'s oceanic divisions and plays a critical role in global trade routes connecting Africa, Asia, and Australia. Which country lies at its northern boundary, giving it its name?', options: ['India', 'Sri Lanka', 'Indonesia', 'Pakistan'], answer: 0, explanation: 'The Indian Ocean is named after India, which lies along its northern edge.' },

  // ===================== STRAITS & GULFS =====================
  { id: 'straits-001', category: 'Straits & Gulfs', question: 'The Strait of Malacca is one of the busiest and most strategically important shipping lanes in the world, linking the Indian Ocean to the Pacific Ocean. It lies between Sumatra (Indonesia) and which country?', options: ['Thailand', 'Malaysia', 'Singapore only', 'Myanmar'], answer: 1, explanation: 'The Strait of Malacca lies between the Indonesian island of Sumatra and Malaysia (with Singapore at its southern end).' },
  { id: 'straits-002', category: 'Straits & Gulfs', question: 'The Palk Strait separates two South Asian nations and connects the Palk Bay with the Bay of Bengal. Which two countries does it lie between?', options: ['India and Bangladesh', 'India and Sri Lanka', 'India and Myanmar', 'Sri Lanka and Maldives'], answer: 1, explanation: 'The Palk Strait lies between India and Sri Lanka.' },
  { id: 'straits-003', category: 'Straits & Gulfs', question: 'The Persian Gulf is a vital waterway for global oil transport, bordered by Iran on one side and several Arab nations on the other. Which country lies to the north of the Persian Gulf?', options: ['Iran', 'Iraq', 'Saudi Arabia', 'Oman'], answer: 0, explanation: 'The Persian Gulf is bordered to the north and east by Iran.' },
  { id: 'straits-004', category: 'Straits & Gulfs', question: 'The Strait of Hormuz is one of the most strategically significant chokepoints in the world due to the volume of oil shipped through it daily. Which two water bodies does it connect?', options: ['Red Sea and Arabian Sea', 'Persian Gulf and Gulf of Oman', 'Persian Gulf and Red Sea', 'Arabian Sea and Gulf of Aden'], answer: 1, explanation: 'The Strait of Hormuz connects the Persian Gulf with the Gulf of Oman.' },
  { id: 'straits-005', category: 'Straits & Gulfs', question: 'The Gulf of Mexico is a large ocean basin bordered by the southeastern United States, eastern Mexico, and Cuba, and it is significant for oil production and fisheries. Which of the following countries does NOT border the Gulf of Mexico?', options: ['United States', 'Mexico', 'Cuba', 'Colombia'], answer: 3, explanation: 'The Gulf of Mexico is bordered by the USA, Mexico, and Cuba, but not Colombia.' },

  // ===================== ISLANDS =====================
  { id: 'islands-001', category: 'Islands', question: "Greenland, largely covered by an ice sheet, is recognized as the world's largest island (as Australia is classified as a continent rather than an island). It is an autonomous territory of which country?", options: ['Iceland', 'Norway', 'Denmark', 'Canada'], answer: 2, explanation: 'Greenland is an autonomous territory of Denmark.' },
  { id: 'islands-002', category: 'Islands', question: 'Madagascar, known for its exceptional biodiversity and many endemic species, is the largest island off the coast of Africa. It lies in which ocean?', options: ['Atlantic Ocean', 'Pacific Ocean', 'Indian Ocean', 'Southern Ocean'], answer: 2, explanation: 'Madagascar lies in the Indian Ocean, off the southeastern coast of Africa.' },
  { id: 'islands-003', category: 'Islands', question: "Borneo is the third-largest island in the world and is politically divided among three countries. Which of the following is NOT one of the countries that share Borneo?", options: ['Indonesia', 'Malaysia', 'Brunei', 'Philippines'], answer: 3, explanation: "Largest island → Greenland\n2nd largest → New Guinea\n3rd largest → Borneo\nLargest island in Africa → Madagascar\nLargest island of Japan → Honshu\nLargest island of Indonesia → Sumatra\nBorneo → shared by 3 countries: Indonesia + Malaysia + Brunei"},
  { id: 'islands-004', category: 'Islands', question: 'Sri Lanka is an island nation in the Indian Ocean, separated from the Indian subcontinent by the Palk Strait and known for its tea plantations. What is the capital city of Sri Lanka?', options: ['Colombo', 'Sri Jayawardenepura Kotte', 'Kandy', 'Galle'], answer: 1, explanation: 'Sri Jayawardenepura Kotte is the official administrative capital of Sri Lanka, though Colombo is the largest city and commercial hub.' },
  { id: 'islands-005', category: 'Islands', question: 'The Maldives is an island nation made up of a chain of atolls in the Indian Ocean and is known as the lowest-lying country in the world. It is located to the southwest of which larger South Asian country?', options: ['Sri Lanka', 'India', 'Pakistan', 'Bangladesh'], answer: 1, explanation: 'The Maldives lies to the southwest of India in the Indian Ocean.' },

  // ===================== INDIAN GEOGRAPHY =====================
  { id: 'india-001', category: 'Indian Geography', question: 'Kangchenjunga, the third-highest mountain in the world, is the highest peak located entirely within India. In which Indian state is Kangchenjunga situated?', options: ['Arunachal Pradesh', 'Sikkim', 'Himachal Pradesh', 'Uttarakhand'], answer: 1, explanation: 'Kangchenjunga is located on the border of Sikkim and Nepal, making it India\'s highest peak.' },
  { id: 'india-002', category: 'Indian Geography', question: 'The Godavari River, often referred to as the "Ganga of the South," is the longest river flowing entirely within peninsular India. In which Indian state does the Godavari originate?', options: ['Karnataka', 'Madhya Pradesh', 'Maharashtra', 'Chhattisgarh'], answer: 2, explanation: 'The Godavari originates near Trimbakeshwar in Maharashtra.' },
  { id: 'india-003', category: 'Indian Geography', question: 'Rajasthan is the largest Indian state by area and is home to much of the Thar Desert as well as the historic Aravalli Range. Which city serves as the capital of Rajasthan?', options: ['Jodhpur', 'Udaipur', 'Jaipur', 'Ajmer'], answer: 2, explanation: 'Jaipur is the capital of Rajasthan.' },
  { id: 'india-004', category: 'Indian Geography', question: "Indira Point, located in the Andaman and Nicobar Islands, is recognized as India's southernmost point. On which island is Indira Point situated?", options: ['Car Nicobar', 'Great Nicobar', 'Little Andaman', 'South Andaman'], answer: 1, explanation: 'Indira Point is located on Great Nicobar Island.' },
  { id: 'india-005', category: 'Indian Geography', question: "Sambhar Lake is India's largest saline (inland saltwater) lake and has historically been an important source of salt production. In which Indian state is Sambhar Lake located?", options: ['Gujarat', 'Rajasthan', 'Madhya Pradesh', 'Haryana'], answer: 1, explanation: 'Sambhar Lake is located in Rajasthan.' },

  // ===================== WORLD GEOGRAPHY =====================
  { id: 'world-001', category: 'World Geography', question: 'Russia spans two continents and is by far the largest country in the world by land area, stretching across eleven time zones. Which country is the second-largest in the world by area?', options: ['China', 'Canada', 'United States', 'Brazil'], answer: 1, explanation: 'Canada is the second-largest country in the world by land area, after Russia.' },
  { id: 'world-002', category: 'World Geography', question: 'Vatican City is an independent city-state entirely surrounded by the city of Rome and is recognized as the smallest country in the world by both area and population. Within which country is Vatican City enclaved?', options: ['France', 'Spain', 'Italy', 'Switzerland'], answer: 2, explanation: 'Vatican City is enclaved within Rome, Italy.' },
  { id: 'world-003', category: 'World Geography', question: 'Asia is the largest and most populous continent, covering roughly one-third of the Earth\'s land area. Which continent is the second-largest by area?', options: ['Africa', 'North America', 'South America', 'Europe'], answer: 0, explanation: 'Africa is the second-largest continent by area after Asia.' },
  { id: 'world-004', category: 'World Geography', question: 'The Equator is an imaginary line that divides the Earth into the Northern and Southern Hemispheres and passes through several countries and oceans. Through which of the following countries does the Equator pass?', options: ['Kenya', 'South Africa', 'Egypt', 'Morocco'], answer: 0, explanation: "South America\n\n🇪🇨 Ecuador\n🇨🇴 Colombia\n🇧🇷 Brazil\n\nAfrica\n\n🇸🇹 São Tomé and Príncipe\n🇬🇦 Gabon\n🇨🇬 Republic of the Congo\n🇨🇩 Democratic Republic of the Congo (DRC)\n🇺🇬 Uganda\n🇰🇪 Kenya\n🇸🇴 Somalia\n\nAsia / Indian & Pacific region\n\n🇲🇻 Maldives\n🇮🇩 Indonesia\n🇰🇮 Kiribati" ,
    notes: ["Tropic of Cancer → 23½° N ✅\n\nYe India ke 8 states se pass hota hai:\n\nGujarat → Rajasthan → Madhya Pradesh → Chhattisgarh → Jharkhand → West Bengal → Tripura → Mizoram"],},
  { id: 'world-005', category: 'World Geography', question: 'The Prime Meridian, which marks zero degrees longitude and is the reference for Greenwich Mean Time, passes through the Royal Observatory in which city?', options: ['Paris', 'London (Greenwich)', 'Edinburgh', 'Dublin'], answer: 1, explanation: 'The Prime Meridian passes through Greenwich, London.' },

  // ===================== CLIMATE =====================
  { id: 'climate-001', category: 'Climate', question: 'The Köppen climate classification system is the most widely used method for classifying the world\'s climates, based on temperature and precipitation patterns. Who developed this classification system?', options: ['Alfred Wegener', 'Wladimir Köppen', 'Alexander von Humboldt', 'Vidal de la Blache'], answer: 1, explanation: 'The Köppen climate classification system was developed by German climatologist Wladimir Köppen.' },
  { id: 'climate-002', category: 'Climate', question: 'The Indian monsoon is a seasonal reversal of wind direction that brings the bulk of India\'s annual rainfall between June and September. From which general direction do the monsoon winds primarily blow during this season?', options: ['Northeast', 'Southwest', 'Northwest', 'Southeast'], answer: 1, explanation: 'The southwest monsoon winds bring the majority of India\'s rainfall between June and September.' },
  { id: 'climate-003', category: 'Climate', question: 'El Niño is a climate pattern characterized by the periodic warming of sea surface temperatures, which affects weather patterns worldwide. In which ocean does El Niño primarily originate?', options: ['Atlantic Ocean', 'Indian Ocean', 'Pacific Ocean', 'Arctic Ocean'], answer: 2, explanation: 'El Niño originates in the equatorial Pacific Ocean.' },
  { id: 'climate-004', category: 'Climate', question: 'The Tropic of Cancer marks the northernmost point at which the sun can appear directly overhead and passes through several countries, including India. Through how many Indian states does the Tropic of Cancer pass?', options: ['6', '7', '8', '9'], answer: 2, explanation: 'The Tropic of Cancer passes through 8 Indian states, from Gujarat to Mizoram.' },
  { id: 'climate-005', category: 'Climate', question: 'A Mediterranean climate is characterized by hot, dry summers and mild, wet winters, and is found not only around the Mediterranean Sea but also in parts of California and Chile. Which of the following regions is famous for this type of climate?', options: ['Amazon Basin', 'California', 'Siberia', 'Sahel'], answer: 1, explanation: 'California experiences a Mediterranean-type climate with hot, dry summers and mild, wet winters.' },

  // ===================== SOILS =====================
  { id: 'soils-001', category: 'Soils', question: 'Black soil, also known as regur soil, is renowned for its high moisture retention and is particularly well-suited for growing cotton. It is predominantly found in which Indian plateau region?', options: ['Chota Nagpur Plateau', 'Deccan Plateau', 'Malwa Plateau', 'Shillong Plateau'], answer: 1, explanation: 'Black soil (regur) is predominantly found in the Deccan Plateau and is ideal for cotton cultivation.' },
  { id: 'soils-002', category: 'Soils', question: 'Alluvial soil is the most extensive and agriculturally important soil type in India, formed by sediment deposits from rivers. It is most extensively found in which region of India?', options: ['Deccan Plateau', 'Indo-Gangetic Plain', 'Western Ghats', 'Thar Desert'], answer: 1, explanation: 'Alluvial soil is most extensively found in the fertile Indo-Gangetic Plain.' },
  { id: 'soils-003', category: 'Soils', question: 'Laterite soil forms in regions with heavy rainfall and high temperatures, leading to leaching of soluble minerals, and it is generally less fertile. In which climatic zones is laterite soil typically found?', options: ['Arid zones', 'Tropical, high-rainfall zones', 'Polar zones', 'Temperate zones'], answer: 1, explanation: 'Laterite soil forms in tropical regions with heavy rainfall due to intense leaching.' },
  { id: 'soils-004', category: 'Soils', question: 'Desert soil is typically sandy, low in humus, and often high in soluble salts, making it generally unsuitable for agriculture without irrigation. In which Indian state is desert soil most predominant?', options: ['Punjab', 'Rajasthan', 'Bihar', 'Kerala'], answer: 1, explanation: 'Desert soil is most predominant in Rajasthan, especially in the Thar Desert region.' },
  { id: 'soils-005', category: 'Soils', question: 'Red soil develops from the weathering of ancient crystalline and metamorphic rocks and owes its color to iron oxide content. It is commonly found in which part of India?', options: ['Northern plains', 'Southern and eastern parts of the Deccan Plateau', 'Himalayan foothills', 'Coastal Gujarat'], answer: 1, explanation: 'Red soil is commonly found in the southern and eastern parts of the Deccan Plateau.' },

  // ===================== FORESTS =====================
  { id: 'forests-001', category: 'Forests', question: 'The Amazon Rainforest is the largest tropical rainforest in the world and is often referred to as "the lungs of the Earth" due to the vast amount of oxygen it produces. It is located primarily in which country?', options: ['Colombia', 'Peru', 'Brazil', 'Venezuela'], answer: 2, explanation: 'The majority of the Amazon Rainforest lies within Brazil.' },
  { id: 'forests-002', category: 'Forests', question: 'The Taiga, also known as the boreal forest, is the largest land biome on Earth, consisting mainly of coniferous trees. It stretches across the northern regions of which two continents?', options: ['Asia and Africa', 'North America and Europe/Asia (Eurasia)', 'South America and Africa', 'Australia and Antarctica'], answer: 1, explanation: 'The Taiga stretches across northern North America and Eurasia (including Siberia and Scandinavia).' },
  { id: 'forests-003', category: 'Forests', question: 'The Sundarbans is the largest mangrove forest in the world and is home to the Bengal tiger, spread across a river delta region. It is shared between India and which other country?', options: ['Myanmar', 'Bangladesh', 'Nepal', 'Bhutan'], answer: 1, explanation: 'The Sundarbans mangrove forest is shared between India and Bangladesh.' },
  { id: 'forests-004', category: 'Forests', question: 'Tropical deciduous forests, which shed their leaves during a particular season, cover large parts of India and are influenced heavily by the monsoon. What is the primary factor that causes trees in these forests to shed their leaves?', options: ['Excess rainfall', 'Seasonal dry period', 'Cold winters', 'Soil salinity'], answer: 1, explanation: 'Deciduous forests shed leaves during the dry season to conserve water.' },
  { id: 'forests-005', category: 'Forests', question: 'The Congo Rainforest is the second-largest tropical rainforest in the world after the Amazon and is home to immense biodiversity. On which continent is the Congo Rainforest located?', options: ['Asia', 'South America', 'Africa', 'Australia'], answer: 2, explanation: 'The Congo Rainforest is located in Central Africa.' },

  // ===================== AGRICULTURE =====================
  { id: 'agriculture-001', category: 'Agriculture', question: 'The Green Revolution significantly boosted food grain production in India during the 1960s through the use of high-yielding seed varieties and modern techniques. Which Indian state is most closely associated with the success of the Green Revolution?', options: ['Punjab', 'Bihar', 'West Bengal', 'Kerala'], answer: 0, explanation: 'Punjab was at the forefront of India\'s Green Revolution, especially in wheat production.' },
  { id: 'agriculture-002', category: 'Agriculture', question: 'Rice is a staple food crop for more than half of the world\'s population and requires abundant water and warm temperatures for cultivation. Which country is the largest producer of rice in the world?', options: ['India', 'China', 'Indonesia', 'Thailand'], answer: 1, explanation: 'China is the largest producer of rice in the world, followed closely by India.' },
  { id: 'agriculture-003', category: 'Agriculture', question: 'Wheat is a major Rabi crop in India, sown in winter and harvested in spring, requiring moderate rainfall and cool climate during growth. Which of the following is classified as a Rabi crop?', options: ['Rice', 'Cotton', 'Wheat', 'Sugarcane'], answer: 2, explanation: 'Wheat is a Rabi crop, sown in winter and harvested in spring.' },
  { id: 'agriculture-004', category: 'Agriculture', question: 'Jute, often called the "golden fiber," is used to make sacks, ropes, and other coarse fabrics, and requires high humidity and fertile alluvial soil. Which Indian state is the leading producer of jute?', options: ['Assam', 'West Bengal', 'Odisha', 'Bihar'], answer: 1, explanation: 'West Bengal is the leading producer of jute in India.' },
  { id: 'agriculture-005', category: 'Agriculture', question: 'Coffee cultivation in India is concentrated in the hilly regions of the south, where cool temperatures and well-drained soil favor the crop. Which Indian state is the largest producer of coffee?', options: ['Tamil Nadu', 'Kerala', 'Karnataka', 'Andhra Pradesh'], answer: 2, explanation: 'Karnataka is the largest coffee-producing state in India.' },

  // ===================== MINERALS =====================
  { id: 'minerals-001', category: 'Minerals', question: 'Iron ore is a fundamental raw material for the steel industry, and India possesses substantial reserves concentrated in a few mineral-rich states. Which Indian state holds the largest reserves of iron ore?', options: ['Jharkhand', 'Odisha', 'Chhattisgarh', 'Karnataka'], answer: 1, explanation: 'Odisha holds the largest reserves of iron ore in India.' },
  { id: 'minerals-002', category: 'Minerals', question: 'Coal remains one of the most important sources of energy worldwide, particularly for electricity generation and industrial use. Which country is the largest producer of coal in the world?', options: ['India', 'United States', 'China', 'Australia'], answer: 2, explanation: 'China is by far the largest producer of coal in the world.' },
  { id: 'minerals-003', category: 'Minerals', question: 'Bauxite is the primary ore from which aluminum is extracted, and its production requires specific tropical weathering conditions. Which of the following is the principal use of bauxite?', options: ['Steel production', 'Aluminum production', 'Cement production', 'Fertilizer production'], answer: 1, explanation: 'Bauxite is the primary ore used to produce aluminum.' },
  { id: 'minerals-004', category: 'Minerals', question: 'Petroleum, a fossil fuel formed from ancient marine organisms, is one of the most traded commodities in the world and is concentrated in certain sedimentary basins. Which country holds the largest proven reserves of petroleum in the world?', options: ['Saudi Arabia', 'Venezuela', 'Russia', 'United States'], answer: 1, explanation: 'Venezuela holds the largest proven oil reserves in the world.' },
  { id: 'minerals-005', category: 'Minerals', question: 'Gold is a precious metal that has been mined and valued by human civilizations for thousands of years, both for ornamentation and as a store of wealth. Which country has historically been the world\'s largest producer of gold?', options: ['South Africa', 'China', 'Australia', 'Russia'], answer: 1, explanation: "Historically largest/dominant gold producer → South Africa 🇿🇦\nCurrently largest gold-producing country → China 🇨🇳"},

  // ===================== EARTH =====================
  { id: 'earth-001', category: 'Earth', question: "The Earth's outermost solid layer, on which continents and oceans rest, is relatively thin compared to the layers beneath it. What is this outermost layer called?", options: ['Mantle', 'Crust', 'Outer core', 'Inner core'], answer: 1, explanation: "The crust is the Earth's outermost solid layer." },
  { id: 'earth-002', category: 'Earth', question: "The theory of plate tectonics explains the movement of large sections of the Earth's lithosphere, which causes earthquakes, volcanic activity, and the formation of mountain ranges. What are these large moving sections of the lithosphere called?", options: ['Fault lines', 'Tectonic plates', 'Continental shelves', 'Subduction zones'], answer: 1, explanation: "Tectonic plates are the large sections of the Earth's lithosphere that move over the mantle." },
  { id: 'earth-003', category: 'Earth', question: 'The rotation of the Earth on its own axis is responsible for the cycle of day and night. Approximately how long does one complete rotation of the Earth take?', options: ['12 hours', '24 hours', '365 days', '30 days'], answer: 1, explanation: 'The Earth takes approximately 24 hours to complete one full rotation on its axis.' },
  { id: 'earth-004', category: 'Earth', question: "The Earth's revolution around the Sun, combined with the tilt of its axis, is responsible for the changing seasons throughout the year. Approximately how long does one complete revolution around the Sun take?", options: ['24 hours', '30 days', '365.25 days', '100 days'], answer: 2, explanation: "The Earth takes approximately 365.25 days to complete one revolution around the Sun." },
  { id: 'earth-005', category: 'Earth', question: "The Earth's core is believed to be composed primarily of two metallic elements, with the inner core being solid due to immense pressure despite extremely high temperatures. What are these two primary elements?", options: ['Iron and Nickel', 'Silicon and Magnesium', 'Aluminum and Iron', 'Carbon and Sulfur'], answer: 0, explanation: "The Earth's core is composed primarily of iron and nickel." },

  // ===================== ATMOSPHERE =====================
  { id: 'atmosphere-001', category: 'Atmosphere', question: 'The ozone layer plays a crucial role in absorbing most of the Sun\'s harmful ultraviolet radiation, protecting life on Earth. In which layer of the atmosphere is the ozone layer located?', options: ['Troposphere', 'Stratosphere', 'Mesosphere', 'Thermosphere'], answer: 1, explanation: 'The ozone layer is located within the stratosphere.' },
  { id: 'atmosphere-002', category: 'Atmosphere', question: 'The troposphere is the lowest layer of Earth\'s atmosphere and is where nearly all weather phenomena, such as clouds and storms, occur. Approximately how far does the troposphere extend above the Earth\'s surface?', options: ['Up to 5 km', 'Up to 12-15 km', 'Up to 50 km', 'Up to 100 km'], answer: 1, explanation: 'The troposphere extends up to approximately 12-15 km above the Earth\'s surface (higher at the equator, lower at the poles).' },
  { id: 'atmosphere-003', category: 'Atmosphere', question: 'Greenhouse gases trap heat within Earth\'s atmosphere, contributing to the natural greenhouse effect that keeps the planet warm enough to support life, but excess amounts drive climate change. Which of the following is considered the most abundant greenhouse gas contributing to human-induced climate change?', options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'], answer: 1, explanation: 'Carbon dioxide is the most significant greenhouse gas contributing to human-induced climate change.' },
  { id: 'atmosphere-004', category: 'Atmosphere', question: "Earth's atmosphere is composed of a mixture of gases, with one gas making up the largest proportion by volume. Which gas is most abundant in the Earth's atmosphere?", options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Argon'], answer: 2, explanation: "Nitrogen makes up about 78% of the Earth's atmosphere by volume, the largest proportion of any gas." },
  { id: 'atmosphere-005', category: 'Atmosphere', question: "The ionosphere is a region of the Earth's upper atmosphere containing a high concentration of charged particles, and it plays a key role in radio communication. Why is the ionosphere significant for long-distance radio transmission?", options: ['It absorbs all radio waves', 'It reflects radio waves back to Earth', 'It blocks sunlight', 'It generates radio waves'], answer: 1, explanation: 'The ionosphere reflects radio waves back toward the Earth, enabling long-distance radio communication.' },

  // ===================== OCEANOGRAPHY =====================
  { id: 'oceanography-001', category: 'Oceanography', question: 'The Mariana Trench, located in the western Pacific Ocean, contains the deepest known point in any of the world\'s oceans. What is this deepest point called?', options: ['Puerto Rico Trench', 'Challenger Deep', 'Java Trench', 'Tonga Trench'], answer: 1, explanation: 'The Challenger Deep, within the Mariana Trench, is the deepest known point in the world\'s oceans.' },
  { id: 'oceanography-002', category: 'Oceanography', question: 'The continental shelf is a gently sloping underwater extension of a continent, typically rich in marine life and important for fishing and offshore drilling. What generally marks the outer boundary of the continental shelf?', options: ['A steep drop-off into deep ocean (continental slope)', 'The equator', 'The mid-ocean ridge', 'The Arctic Circle'], answer: 0, explanation: 'The continental shelf ends at the continental slope, where the seabed drops steeply toward the deep ocean floor.' },
  { id: 'oceanography-003', category: 'Oceanography', question: 'The Gulf Stream is a powerful, warm ocean current that significantly influences the climate of Western Europe by carrying warm water northward. In which ocean does the Gulf Stream primarily flow?', options: ['Pacific Ocean', 'Indian Ocean', 'Atlantic Ocean', 'Arctic Ocean'], answer: 2, explanation: 'The Gulf Stream is a warm current flowing through the Atlantic Ocean.' },
  { id: 'oceanography-004', category: 'Oceanography', question: 'Ocean tides are the periodic rise and fall of sea levels, caused primarily by the gravitational pull of a celestial body along with the Sun\'s influence. Which celestial body has the greatest influence on Earth\'s tides?', options: ['The Sun', 'The Moon', 'Mars', 'Venus'], answer: 1, explanation: "The Moon's gravitational pull is the primary driver of Earth's tides, with the Sun playing a secondary role." },
  { id: 'oceanography-005', category: 'Oceanography', question: 'Salinity refers to the concentration of dissolved salts in seawater and varies across different seas due to evaporation, precipitation, and freshwater inflow. Which of the following seas is known for having one of the highest salinity levels among the world\'s seas?', options: ['Baltic Sea', 'Red Sea', 'Black Sea', 'Bering Sea'], answer: 1, explanation: "Dead Sea\t~340‰\tJordan + Israel/West Bank region\nRed Sea\t~40–41‰\tAfrica + Arabian Peninsula ke beech"},

  // ===================== DAMS =====================
{ id: 'dams-001', category: 'Dams', question: 'A dam is a man-made structure built across a river or water stream to stop, control, divert, or regulate the flow of water. The water collected and stored behind such a structure is known by which term?', options: ['Canal', 'Reservoir', 'Barrage', 'Aqueduct'], answer: 1, explanation: 'A reservoir is the water body or storage area where water is collected behind a dam. A dam is the water-control structure, while the reservoir is the stored water body.' },
{ id: 'dams-002', category: 'Dams', question: 'A dam does not necessarily mean only a concrete wall. According to the material-based description in the notes, which set contains materials that can be used for dam construction?', options: ['Concrete, masonry, earth and rock-fill', 'Only concrete and steel', 'Wood, glass and plastic', 'Only compacted earth'], answer: 0, explanation: 'The notes list Concrete, Masonry, Earth and Rock-fill as dam-building materials. Therefore, a dam may be made from different materials and is not always simply a concrete wall.' },
{ id: 'dams-003', category: 'Dams', question: 'When the water level in a dam reservoir becomes too high, excess water must be released safely to protect the structure and regulate the flow. Which dam component is specially designed for this purpose?', options: ['Spillway', 'Reservoir', 'Penstock', 'Canal'], answer: 0, explanation: 'A spillway is a structure used to safely release excess water from a reservoir. It helps manage excess flow instead of allowing uncontrolled overflow.' },
{ id: 'dams-004', category: 'Dams', question: 'Dams are classified on more than one basis. Which combination correctly represents the major bases of classification highlighted in the notes?', options: ['Structure/material, purpose and height', 'River length, rainfall and population', 'District, state and language', 'Reservoir colour, width and depth only'], answer: 0, explanation: 'The notes classify dams by structure/material, purpose and height. A later section also discusses construction material/design as a basis of classification.' },
{ id: 'dams-005', category: 'Dams', question: 'Consider the following statements about dams: 1. A dam always refers only to a concrete or structural wall built to block water. 2. Spillways help regulate or release water flow. 3. Dams can be classified on the basis of structure, purpose and height. Which statements are correct?', options: ['1 and 2 only', '2 and 3 only', '1 and 3 only', '1, 2 and 3'], answer: 1, explanation: 'Statements 2 and 3 are correct. Statement 1 is incorrect because dams can be made from materials such as concrete, masonry, earth and rock-fill. The source presents a similar question as SSC CGL 2025 Tier-01, 14 September 2025, Shift 2.' },
{ id: 'dams-006', category: 'Dams', question: 'A dam constructed mainly using concrete or masonry materials is classified as a Concrete/Masonry Dam. Which dam is given in the notes as an example of this type?', options: ['Nagarjuna Sagar Dam', 'Pandoh Dam', 'Pong Dam', 'Tehri Dam'], answer: 0, explanation: 'Nagarjuna Sagar Dam is given as the example of a Concrete/Masonry Dam. This classification is based on construction material/design.' },
{ id: 'dams-007', category: 'Dams', question: 'Which option correctly matches the construction-based dam types described in the notes?', options: ['Earth Dam—compacted earth/soil; Rock-fill Dam—rocks with engineered fill; Composite Dam—combination of more than one material or dam type', 'Earth Dam—only concrete; Rock-fill Dam—only steel; Composite Dam—only soil', 'Earth Dam—water diversion only; Rock-fill Dam—flood control only; Composite Dam—hydropower only', 'All three are defined only by height'], answer: 0, explanation: 'An Earth Dam mainly uses compacted earth or soil, a Rock-fill Dam uses rocks with engineered fill materials, and a Composite Dam combines more than one construction material or dam type in the same project.' },
{ id: 'dams-008', category: 'Dams', question: 'Under classification by purpose, a Storage Dam stores water for later use, while a Detention/Flood-Control Structure temporarily stores or regulates flood flows. What is the main purpose of a Diversion Dam?', options: ['To permanently stop all river flow', 'To divert water toward a canal or another conveyance system', 'To generate electricity only', 'To increase the height of a reservoir'], answer: 1, explanation: 'A Diversion Dam is built to redirect water toward a canal or another conveyance system. The three purpose-based types highlighted are Storage Dam, Diversion Dam and Detention/Flood-Control Structure.' },
{ id: 'dams-009', category: 'Dams', question: 'Dams can store water and supply it to agricultural fields through canals, making irrigation possible even in the dry season and potentially increasing cultivated area. Which major purpose of dams is being described?', options: ['Irrigation', 'Navigation', 'Mining', 'Urban transport'], answer: 0, explanation: 'The described function is irrigation. Stored reservoir water can be supplied through canals to fields, supporting agriculture during dry periods and increasing the area under cultivation.' },
{ id: 'dams-010', category: 'Dams', question: 'Water stored at a height in a dam reservoir possesses potential energy. When released downward, it flows with force and rotates a turbine, which drives a generator. What is produced through this process?', options: ['Coal', 'Hydroelectric power', 'Natural gas', 'Solar energy'], answer: 1, explanation: 'The process produces hydroelectric power. Stored water has potential energy because of its height; flowing water turns the turbine, and the turbine drives the generator to produce electricity.' },
{ id: 'dams-011', category: 'Dams', question: 'The hydropower diagram in the notes shows water moving from the headpond/reservoir through an intake and penstock to a turbine, after which electrical equipment carries the generated power onward. Which sequence best matches the diagram?', options: ['Intake → Penstock → Turbine → Generator → Transformer → Transmission lines', 'Transformer → Reservoir → Generator → Penstock → Turbine', 'Turbine → Intake → Reservoir → Spillway → Generator', 'Transmission lines → Penstock → Turbine → Intake'], answer: 0, explanation: 'The diagram shows intake, penstock, turbine, generator, transformer and transmission lines in the power-generation path. It also labels the powerhouse, draft tube and tailrace on the downstream side.' },
{ id: 'dams-012', category: 'Dams', question: 'During heavy rainfall, a river may suddenly receive a very large quantity of water. A reservoir can temporarily store part of this excess water and reduce the peak flow downstream. Which purpose of a dam does this describe?', options: ['Flood control', 'Fishery', 'Tourism', 'Industrial transport'], answer: 0, explanation: 'This is flood control. Temporary storage of excess inflow in a reservoir can reduce the downstream peak flood flow; controlled release and spillway operation are also illustrated in the notes.' },
{ id: 'dams-013', category: 'Dams', question: 'Many multipurpose river valley projects provide large quantities of water needed for manufacturing and other industrial activities. Which benefit of dams is highlighted here?', options: ['Industrial water supply', 'Forest conservation only', 'Railway electrification only', 'Desert tourism'], answer: 0, explanation: 'The notes identify industrial water supply as an important benefit because industries require large quantities of water for different industrial activities.' },
{ id: 'dams-014', category: 'Dams', question: 'Reservoir water can be used during dry periods when natural water availability is low, making dams important for water storage and seasonal regulation. Which function is being described?', options: ['Drought management', 'Coastal erosion', 'Navigation control', 'Tidal power'], answer: 0, explanation: 'The function is drought management. Stored reservoir water can support water availability during dry periods, while dams help with seasonal regulation.' },
{ id: 'dams-015', category: 'Dams', question: 'Reservoirs may be used to develop fisheries, providing local communities with an additional source of livelihood and economic activity. Which dam-related benefit is described?', options: ['Fishery development', 'Flood forecasting', 'Road construction', 'Mineral extraction'], answer: 0, explanation: 'Fisheries can be developed in reservoirs. The notes connect this use with additional livelihood and economic opportunities for local communities.' },
{ id: 'dams-016', category: 'Dams', question: 'Large reservoirs can support boating, tourism, water sports and other recreational activities, which may also create additional economic opportunities. Which benefit of dams does this represent?', options: ['Recreation and tourism', 'Only irrigation', 'Only flood control', 'Only drinking-water treatment'], answer: 0, explanation: 'The notes identify recreation and tourism as reservoir-related benefits, including boating, water sports and other recreational activities that can promote tourism and economic opportunities.' },
{ id: 'dams-017', category: 'Dams', question: 'A visual in the notes highlights three characteristics of rainfall that create challenges for water availability and storage. Which set matches those characteristics?', options: ['Seasonal rainfall, spatially uneven rainfall and highly variable rainfall', 'Uniform rainfall, constant rainfall and no seasonal change', 'Only winter rainfall, only coastal rainfall and no variation', 'Daily rainfall, hourly rainfall and artificial rainfall'], answer: 0, explanation: 'The visual highlights seasonal rainfall, spatially uneven rainfall and highly variable rainfall, all of which make storage and regulation of water important.' },
{ id: 'dams-018', category: 'Dams', question: 'India has thousands of large and specified dams according to recent government records. Which institution maintains the National Register of Large Dams in India?', options: ['Central Water Commission (CWC)', 'Election Commission of India', 'NITI Aayog', 'National Highways Authority of India'], answer: 0, explanation: 'The Central Water Commission (CWC) maintains the National Register of Large Dams in India.' },
{ id: 'dams-019', category: 'Dams', question: 'The Dam Safety Act was enacted to create a comprehensive framework for surveillance, inspection, operation and maintenance of specified dams, while helping prevent dam-failure disasters and ensure safe functioning. In which year was this Act enacted?', options: ['2016', '2018', '2021', '2023'], answer: 2, explanation: 'The Dam Safety Act was enacted in 2021. Its framework covers surveillance, inspection, operation and maintenance of specified dams and aims to improve dam safety.' },
{ id: 'dams-020', category: 'Dams', question: 'Under India’s dam-safety framework, which national-level institution is responsible for coordinating and overseeing matters related to dam safety across the country?', options: ['National Dam Safety Authority (NDSA)', 'Central Electricity Authority only', 'National Disaster Response Force only', 'Geological Survey of India only'], answer: 0, explanation: 'The National Dam Safety Authority (NDSA) is the national-level institution responsible for coordination and oversight of dam-safety matters. The notes also state that India has continued strengthening its dam-safety infrastructure.' },
{ id: 'dams-021', category: 'Dams', question: 'The Dam Rehabilitation and Improvement Project, commonly called DRIP, focuses on existing dams in India. Which set best describes its major objectives?', options: ['Safety, rehabilitation, operational performance and institutional capacity', 'New railway construction and airport expansion', 'River pollution control only', 'Groundwater mapping only'], answer: 0, explanation: 'DRIP is being implemented to improve safety, rehabilitation, operational performance and institutional capacity related to existing dams in India.' },
{ id: 'dams-022', category: 'Dams', question: 'Under DRIP Phase II & III, 736 dams were identified for rehabilitation and safety enhancement. Which option correctly gives the project coverage, approved cost and implementation period stated in the notes?', options: ['19 States and 3 Central Agencies; ₹10,211 crore; 2021–2031', '10 States and 2 Central Agencies; ₹5,053 crore; 2025–2030', '19 States and 1 Central Agency; ₹736 crore; 2021–2026', '28 States and 8 Central Agencies; ₹10,211 crore; 2026–2036'], answer: 0, explanation: 'DRIP Phase II & III covers 19 States and 3 Central Agencies, has a total approved cost of ₹10,211 crore, and has an implementation period of 2021–2031. A total of 736 dams were identified under these phases.' },
{ id: 'dams-023', category: 'Dams', question: 'According to the 2026 government update cited in the notes, rehabilitation proposals under DRIP-II had been approved for a certain number of dams with an approximate financial involvement, and major physical works had been completed on another set of dams. Which figures are correct?', options: ['191 dams; about ₹5,053 crore; major works completed on 43 dams', '736 dams; about ₹10,211 crore; major works completed on 191 dams', '43 dams; about ₹736 crore; major works completed on 19 dams', '191 dams; about ₹10,211 crore; major works completed on 736 dams'], answer: 0, explanation: 'The 2026 update states that rehabilitation proposals for 191 dams under DRIP-II, involving approximately ₹5,053 crore, had been approved, while major physical rehabilitation works had been completed on 43 dams.' },
{ id: 'dams-024', category: 'Dams', question: 'The notes mention the proposed Daudhan Dam in connection with the Ken-Betwa project. This proposed dam is primarily associated with which larger type of project?', options: ['River linking', 'Coastal shipping', 'Inland fisheries only', 'Desert development'], answer: 0, explanation: 'In the source question, the proposed Daudhan Dam under the Ken-Betwa project is associated with river linking.' },
{ id: 'dams-025', category: 'Dams', question: 'The Sutlej is described as a major river of the Indus River System in Himachal Pradesh. Which pair is listed among its important tributaries in the notes?', options: ['Spiti and Baspa', 'Parvati and Sainj', 'Mandakini and Pindar', 'Tons and Ramganga'], answer: 0, explanation: 'Spiti and Baspa are listed as tributaries of the Sutlej. Several major Himachal projects in the notes, including Bhakra, Nathpa Jhakri, Koldam and Luhri Stage-I, are associated with the Sutlej.' },
{ id: 'dams-026', category: 'Dams', question: 'Bhakra Dam is a major component of the Bhakra-Nangal Multipurpose Project. It is described as a 225.55 m high Concrete Straight Gravity Dam in Bilaspur, Himachal Pradesh, and it forms the Gobind Sagar Reservoir. On which river is Bhakra Dam built?', options: ['Beas', 'Sutlej', 'Ravi', 'Chenab'], answer: 1, explanation: 'Bhakra Dam is built on the Sutlej River in Bilaspur. The notes describe it as 225.55 m high, Concrete Straight Gravity in type, forming Gobind Sagar Reservoir and forming a major component of the Bhakra-Nangal Multipurpose Project.' },
{ id: 'dams-027', category: 'Dams', question: 'Nathpa Jhakri is listed as a hydropower project in Himachal Pradesh. According to the summary table, it is located in Kinnaur district. On which river is this project situated?', options: ['Sutlej', 'Beas', 'Ravi', 'Yamuna'], answer: 0, explanation: 'Nathpa Jhakri is a hydropower project on the Sutlej River in Himachal Pradesh, and the summary table places it in Kinnaur.' },
{ id: 'dams-028', category: 'Dams', question: 'Koldam is described in the notes as an earthen hydropower dam in Himachal Pradesh, and the summary table places it in Mandi district. On which river is Koldam located?', options: ['Sutlej', 'Beas', 'Ravi', 'Chenab'], answer: 0, explanation: 'According to the PDF, Koldam is on the Sutlej River in Mandi and is described as a hydropower project and an earthen dam.' },
{ id: 'dams-029', category: 'Dams', question: 'Luhri Stage-I is described as an under-construction hydropower project in Himachal Pradesh, and the summary table places Luhri-I in Shimla. On which river is it being developed?', options: ['Sutlej', 'Beas', 'Ravi', 'Ramganga'], answer: 0, explanation: 'Luhri Stage-I is an under-construction hydropower project on the Sutlej River. The summary table lists Luhri-I under Shimla with the speciality “Under construction; hydropower.”' },
{ id: 'dams-030', category: 'Dams', question: 'The Beas is a major river of the Indus River System in Himachal Pradesh. Which group contains tributaries of the Beas listed in the notes?', options: ['Parvati, Sainj, Tirthan, Sarbari and Bakhli', 'Spiti, Baspa, Mandakini, Pindar and Tons', 'Bhagirathi, Alaknanda, Ramganga, Ravi and Chenab', 'Nandakini, Dhauliganga, Birahi Ganga, Tons and Baspa'], answer: 0, explanation: 'The notes list Parvati, Sainj, Tirthan, Sarbari and Bakhli as tributaries of the Beas River.' },
{ id: 'dams-031', category: 'Dams', question: 'Pandoh Dam is located in Mandi, Himachal Pradesh, and is mainly associated with water diversion and hydropower generation. It is also linked with the Beas-Sutlej Link in the summary table. Which description correctly identifies the dam and river?', options: ['Earth-cum-Rockfill diversion dam on the Beas River', 'Concrete gravity dam on the Ravi River', 'Earth Core Gravel Shell dam on the Sutlej River', 'Earth and Rockfill dam on the Bhagirathi River'], answer: 0, explanation: 'Pandoh Dam is an Earth-cum-Rockfill diversion dam on the Beas River in Mandi. It is mainly associated with water diversion and hydropower generation, and the table notes its Beas-Sutlej Link role.' },
{ id: 'dams-032', category: 'Dams', question: 'Pong Dam is located on the Beas River in Kangra, Himachal Pradesh. The notes describe it as an Earth Core Gravel Shell dam and the summary table associates it with Maharana Pratap Sagar and a multipurpose role. By what other name is Pong Dam known?', options: ['Beas Dam', 'Ravi Dam', 'Sutlej Dam', 'Kangra Dam'], answer: 0, explanation: 'Pong Dam is also called Beas Dam. It is on the Beas River in Kangra, is described as an Earth Core Gravel Shell dam, and is associated with Maharana Pratap Sagar.' },
{ id: 'dams-033', category: 'Dams', question: 'The Ravi is described as a major eastern river of the Indus River System, with Chamba as an important region in Himachal Pradesh. Which project is identified as a Concrete Gravity hydropower dam on the Ravi River in Chamba?', options: ['Chamera-I', 'Pandoh', 'Bhakra', 'Nathpa Jhakri'], answer: 0, explanation: 'Chamera-I is a Concrete Gravity hydropower dam on the Ravi River in Chamba, Himachal Pradesh.' },
{ id: 'dams-034', category: 'Dams', question: 'The Chamera hydropower projects are listed on the Ravi in Chamba. Which option correctly matches the installed capacities given in the notes?', options: ['Chamera-I—540 MW; Chamera-II—300 MW; Chamera-III—231 MW', 'Chamera-I—300 MW; Chamera-II—540 MW; Chamera-III—231 MW', 'Chamera-I—231 MW; Chamera-II—300 MW; Chamera-III—540 MW', 'All three—400 MW each'], answer: 0, explanation: 'The notes give Chamera-I as 540 MW, Chamera-II as 300 MW and Chamera-III as 231 MW. The summary table lists all three in Chamba on the Ravi.' },
{ id: 'dams-035', category: 'Dams', question: 'A project-status slide lists three under-construction projects in Himachal Pradesh: Luhri Stage-I on the Sutlej, Dhaulasidh Dam on the Beas, and Parbati-II on which stream?', options: ['Sainj Khad', 'Spiti', 'Baspa', 'Tons'], answer: 0, explanation: 'The project-status slide states that Parbati-II is an under-construction project on Sainj Khad. It also lists Luhri Stage-I on the Sutlej and Dhaulasidh Dam on the Beas as under construction.' },
{ id: 'dams-036', category: 'Dams', question: 'In the Himachal Pradesh summary table, which pairing is shown correctly for projects on Sainj Khad and the Beas?', options: ['Parbati-III—Sainj Khad, Kullu, Hydropower; Dhaulasidh—Beas, Hamirpur, Under construction', 'Parbati-III—Ravi, Chamba; Dhaulasidh—Sutlej, Kinnaur', 'Parbati-III—Beas, Kangra; Dhaulasidh—Ravi, Chamba', 'Parbati-III—Yamuna, Dehradun; Dhaulasidh—Ramganga, Pauri'], answer: 0, explanation: 'The summary table lists Parbati-III on Sainj Khad in Kullu as a hydropower project and Dhaulasidh on the Beas in Hamirpur as under construction. Note that an earlier slide in the same PDF refers to “Parbati-II” on Sainj Khad, while the summary table says “Parbati-III.”' },
{ id: 'dams-037', category: 'Dams', question: 'Uttarakhand is presented in the notes as having three major river systems. Which set correctly names all three?', options: ['Ganga, Yamuna and Ramganga', 'Indus, Narmada and Tapi', 'Godavari, Krishna and Kaveri', 'Mahanadi, Brahmaputra and Sabarmati'], answer: 0, explanation: 'The three major river systems listed for Uttarakhand are the Ganga, Yamuna and Ramganga systems.' },
{ id: 'dams-038', category: 'Dams', question: 'The notes distinguish major river-system components in Uttarakhand. Which option correctly matches the Ganga and Yamuna systems?', options: ['Ganga System—Bhagirathi, Alaknanda and tributaries; Yamuna System—Yamuna, Tons and other tributaries', 'Ganga System—Ravi and Beas; Yamuna System—Sutlej and Spiti', 'Ganga System—Ramganga only; Yamuna System—Alaknanda only', 'Ganga System—Pindar only; Yamuna System—Bhagirathi only'], answer: 0, explanation: 'The Ganga System includes Bhagirathi, Alaknanda and their tributaries, while the Yamuna System includes Yamuna, Tons and other tributaries. Ramganga is identified as another important river system of Uttarakhand.' },
{ id: 'dams-039', category: 'Dams', question: 'Bhagirathi is a major headstream of the Ganga and is associated with Tehri Dam. The dam is located in Tehri Garhwal, Uttarakhand, is 260.5 metres high and forms the Tehri Reservoir. Which type and river combination is correct for Tehri Dam?', options: ['Earth and Rockfill Dam on the Bhagirathi River', 'Concrete Gravity Dam on the Alaknanda River', 'Earth Core Gravel Shell Dam on the Yamuna River', 'Diversion Dam on the Ramganga River'], answer: 0, explanation: 'Tehri Dam is an Earth and Rockfill Dam on the Bhagirathi River in Tehri Garhwal. It is 260.5 metres high and forms the Tehri Reservoir.' },
{ id: 'dams-040', category: 'Dams', question: 'Koteshwar is identified in the notes as a 400 MW hydropower project in Uttarakhand. With which river is Koteshwar Hydroelectric Project associated?', options: ['Bhagirathi', 'Yamuna', 'Alaknanda', 'Ramganga'], answer: 0, explanation: 'Koteshwar is a 400 MW hydropower project on the Bhagirathi River in Uttarakhand.' },
{ id: 'dams-041', category: 'Dams', question: 'Alaknanda is described as another major headstream of the Ganga, with tributaries including Mandakini, Pindar, Nandakini, Dhauliganga and Birahi Ganga. Which hydropower project is listed on the Alaknanda River in Chamoli, Uttarakhand?', options: ['Vishnuprayag Hydropower Project', 'Nathpa Jhakri Project', 'Chamera-I Project', 'Pandoh Project'], answer: 0, explanation: 'Vishnuprayag Hydropower Project is on the Alaknanda River in Chamoli, Uttarakhand. The notes list Mandakini, Pindar, Nandakini, Dhauliganga and Birahi Ganga among Alaknanda’s important tributaries.' },
{ id: 'dams-042', category: 'Dams', question: 'The Panch Prayag infographic shows five sacred confluences in Uttarakhand. Which option gives all five river combinations correctly?', options: ['Vishnuprayag—Dhauliganga + Alaknanda; Nandprayag—Nandakini + Alaknanda; Karnaprayag—Pindar + Alaknanda; Rudraprayag—Mandakini + Alaknanda; Devprayag—Bhagirathi + Alaknanda', 'Vishnuprayag—Pindar + Alaknanda; Nandprayag—Mandakini + Alaknanda; Karnaprayag—Dhauliganga + Alaknanda; Rudraprayag—Nandakini + Alaknanda; Devprayag—Yamuna + Tons', 'Vishnuprayag—Bhagirathi + Alaknanda; Nandprayag—Pindar + Alaknanda; Karnaprayag—Mandakini + Alaknanda; Rudraprayag—Dhauliganga + Alaknanda; Devprayag—Ramganga + Ganga', 'All five Prayags are confluences of the Yamuna and Tons'], answer: 0, explanation: 'The infographic gives: Vishnuprayag = Dhauliganga + Alaknanda; Nandprayag = Nandakini + Alaknanda; Karnaprayag = Pindar + Alaknanda; Rudraprayag = Mandakini + Alaknanda; Devprayag = Bhagirathi + Alaknanda.' },
{ id: 'dams-043', category: 'Dams', question: 'At which Panch Prayag do the Alaknanda and Bhagirathi rivers meet, after which the river is identified as the Ganga in the infographic?', options: ['Rudraprayag', 'Karnaprayag', 'Devprayag', 'Nandprayag'], answer: 2, explanation: 'Alaknanda and Bhagirathi meet at Devprayag. The Panch Prayag visual shows their confluence leading onward as the Ganga.' },
{ id: 'dams-001', category: 'Dams', question: 'The Bhakra Nangal Dam is one of the highest gravity dams in India and plays a critical role in irrigation and power generation for northern India. On which river is the Bhakra Dam constructed?', options: ['Beas River', 'Sutlej River', 'Ravi River', 'Chenab River'], answer: 1, explanation: 'The Bhakra Dam is built on the Sutlej River.' },
{ id: 'dams-002', category: 'Dams', question: 'The Hoover Dam is a massive concrete arch-gravity dam that generates hydroelectric power and provides water storage for several southwestern US states. On which river is the Hoover Dam built?', options: ['Rio Grande', 'Colorado River', 'Columbia River', 'Missouri River'], answer: 1, explanation: 'The Hoover Dam is built on the Colorado River, on the border of Nevada and Arizona.' },
{ id: 'dams-003', category: 'Dams', question: 'The Three Gorges Dam is the largest hydroelectric power station in the world by installed capacity and spans one of Asia\'s major rivers. On which river is the Three Gorges Dam located?', options: ['Yellow River', 'Yangtze River', 'Mekong River', 'Pearl River'], answer: 1, explanation: 'The Three Gorges Dam is built on the Yangtze River in China.' },
{ id: 'dams-004', category: 'Dams', question: 'The Tehri Dam is the tallest dam in India and plays a significant role in irrigation, hydroelectric power, and water supply to northern India. On which river is the Tehri Dam constructed?', options: ['Alaknanda River', 'Bhagirathi River', 'Mandakini River', 'Yamuna River'], answer: 1, explanation: 'The Tehri Dam is built on the Bhagirathi River in Uttarakhand.' },
{ id: 'dams-005', category: 'Dams', question: 'The Aswan High Dam was constructed to control flooding, provide water storage, and generate electricity for a country long dependent on a single major river. On which river is the Aswan Dam built?', options: ['Congo River', 'Niger River', 'Nile River', 'Zambezi River'], answer: 2, explanation: 'The Aswan High Dam is built on the Nile River in Egypt.' },
 
  // ===================== GEOGRAPHICAL SUPERLATIVES =====================
  { id: 'superlatives-001', category: 'Geographical Superlatives', question: 'Standing at 8,849 meters above sea level, this peak is recognized as the highest point on Earth and attracts climbers from around the world despite the extreme dangers involved. Which mountain holds this distinction?', options: ['K2', 'Kangchenjunga', 'Mount Everest', 'Lhotse'], answer: 2, explanation: 'Mount Everest, at 8,849 meters, is the highest mountain on Earth above sea level.' },
  { id: 'superlatives-002', category: 'Geographical Superlatives', question: "Two rivers are often debated for the title of the world's longest river, with one traditionally credited due to its length through northeastern Africa. Which river is conventionally regarded as the world's longest?", options: ['Amazon River', 'Nile River', 'Yangtze River', 'Mississippi River'], answer: 1, explanation: "The Nile River is conventionally regarded as the world's longest river, though some measurements favor the Amazon." },
  { id: 'superlatives-003', category: 'Geographical Superlatives', question: "The Challenger Deep, located within a trench in the western Pacific Ocean, represents the deepest known point in any of the world's oceans, reaching depths of nearly 11,000 meters. In which trench is the Challenger Deep located?", options: ['Puerto Rico Trench', 'Java Trench', 'Mariana Trench', 'Tonga Trench'], answer: 2, explanation: 'The Challenger Deep is located in the Mariana Trench.' },
  { id: 'superlatives-004', category: 'Geographical Superlatives', question: 'Russia is the largest country in the world by total area, spanning across Eastern Europe and northern Asia. Approximately how many time zones does Russia span?', options: ['5', '7', '9', '11'], answer: 3, explanation: 'Russia spans 11 time zones, more than any other country in the world.' },
  { id: 'superlatives-005', category: 'Geographical Superlatives', question: "Antarctica, though covered largely by ice, is officially recognized as the world's largest desert due to its extremely low levels of precipitation. Which desert is the largest hot desert in the world, by contrast?", options: ['Sahara Desert', 'Gobi Desert', 'Kalahari Desert', 'Arabian Desert'], answer: 0, explanation: 'The Sahara Desert is the largest hot desert in the world, while Antarctica is the largest desert overall (including cold deserts).' },

  // ===================== ADDITIONAL QUESTIONS =====================
  { id: 'extra-001', category: 'Rivers', question: "The Nile River is one of the world's longest rivers and has played a crucial role in the development of ancient Egyptian civilization. It flows northward before emptying into the Mediterranean Sea. On which continent is the Nile River primarily located?", options: ['Asia', 'Africa', 'Europe', 'South America'], answer: 1, explanation: 'The Nile River flows through northeastern Africa, including Egypt and Sudan, before emptying into the Mediterranean Sea.' },
  { id: 'extra-002', category: 'Lakes', question: "Lake Baikal is the world's deepest freshwater lake and contains about one-fifth of the world's unfrozen surface freshwater. It is also one of the world's oldest lakes. In which country is Lake Baikal located?", options: ['Mongolia', 'Kazakhstan', 'Russia', 'China'], answer: 2, explanation: 'Lake Baikal is located in southern Siberia, Russia.' },
  { id: 'extra-003', category: 'Rivers', question: 'The Amazon River carries more water than any other river in the world and drains a vast basin covered largely by tropical rainforest. Into which ocean does the Amazon River empty?', options: ['Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'], answer: 1, explanation: 'The Amazon River empties into the Atlantic Ocean on the northeastern coast of Brazil.' },
  { id: 'extra-004', category: 'Mountains & Peaks', question: "Mount Kilimanjaro is Africa's highest mountain and is famous for its three volcanic cones—Kibo, Mawenzi and Shira. In which country is Mount Kilimanjaro located?", options: ['Kenya', 'Uganda', 'Tanzania', 'Ethiopia'], answer: 2, explanation: 'Mount Kilimanjaro is located in Tanzania, near the border with Kenya.' },
  { id: 'extra-005', category: 'Oceans & Seas', question: "The Great Barrier Reef is the world's largest coral reef system and consists of thousands of individual reefs and islands. It lies off the northeastern coast of which country?", options: ['Indonesia', 'Australia', 'Papua New Guinea', 'New Zealand'], answer: 1, explanation: 'The Great Barrier Reef lies off the northeastern coast of Australia, in the Coral Sea.' },
  { id: 'extra-006', category: 'Rivers', question: "The Danube is one of Europe's most important international rivers and flows through or along the borders of several countries before forming a large delta. Into which sea does the Danube River ultimately drain?", options: ['Baltic Sea', 'Adriatic Sea', 'Black Sea', 'Caspian Sea'], answer: 2, explanation: 'The Danube River drains into the Black Sea, forming a large delta in Romania.' },
  { id: 'extra-007', category: 'Deserts', question: 'The Atacama Desert is regarded as one of the driest non-polar regions on Earth. It stretches along the Pacific coast of South America and is particularly associated with which country?', options: ['Peru', 'Chile', 'Bolivia', 'Argentina'], answer: 1, explanation: 'The Atacama Desert stretches along the Pacific coast of Chile.' },
  { id: 'extra-008', category: 'Deserts', question: 'The Gobi Desert is a vast cold desert of Asia, known for its extreme temperatures and important fossil discoveries. It extends across southern Mongolia and the northern part of which country?', options: ['Kazakhstan', 'Russia', 'China', 'Uzbekistan'], answer: 2, explanation: 'The Gobi Desert extends across southern Mongolia and northern China.' },
  { id: 'extra-009', category: 'Straits & Gulfs', question: 'The Strait of Gibraltar is a strategically important narrow waterway separating Europe from Africa. It connects the Atlantic Ocean with which sea?', options: ['Red Sea', 'Mediterranean Sea', 'Black Sea', 'Adriatic Sea'], answer: 1, explanation: 'The Strait of Gibraltar connects the Atlantic Ocean with the Mediterranean Sea.' },
  { id: 'extra-010', category: 'Waterfalls', question: 'Victoria Falls is one of the world\'s most famous waterfalls and is formed by the Zambezi River. The falls lie on the international border between Zambia and which other African country?', options: ['Botswana', 'Namibia', 'Zimbabwe', 'Malawi'], answer: 2, explanation: "Victoria Falls → Zambezi River → Zambia + Zimbabwe → “Smoke That Thunders”"},
{ id: 'extra-011', category: 'All Straits', question: 'Gibraltar → Atlantic Ocean + Mediterranean Sea Hormuz → Persian Gulf + Gulf of Oman\n Bab-el-Mandeb → Red Sea + Gulf of Aden\n \n Malacca → Andaman Sea + South China Sea\n Bering → Bering Sea + Chukchi Sea\n Bosporus → Black Sea + Sea of Marmara\n Dardanelles → Sea of Marmara + Aegean Sea\n \n Dover → English Channel + North Sea\n Palk → Bay of Bengal + Gulf of Mannar\n Sunda → Java Sea + Indian Ocean\n Lombok → Bali Sea + Indian Ocean\n Makassar → Celebes Sea + Java Sea\n \n Taiwan (Formosa) → East China Sea + South China Sea\n Korea (Tsushima) → East China Sea + Sea of Japan\n Tsugaru → Sea of Japan + Pacific Ocean\n La Pérouse (Soya) → Sea of Japan + Sea of Okhotsk\n \n Torres → Arafura Sea + Coral Sea\n Bass → Indian Ocean region + Tasman Sea\n Cook → Tasman Sea + South Pacific Ocean\n \n Florida → Gulf of Mexico + Atlantic Ocean\n Yucatán → Caribbean Sea + Gulf of Mexico\n Davis → Baffin Bay + Labrador Sea\n Hudson → Hudson Bay + Labrador Sea\n \n Denmark → Greenland Sea + North Atlantic Ocean\n Fram → Arctic Ocean + Greenland Sea\n Vilkitsky → Kara Sea + Laptev Sea\n \n Messina → Tyrrhenian Sea + Ionian Sea\n Otranto → Adriatic Sea + Ionian Sea\n Bonifacio → Mediterranean Sea (between Corsica + Sardinia)\n \n Tiran → Gulf of Aqaba + Red Sea\n Kerch → Black Sea + Sea of Azov', options: ['Botswana', 'Namibia', 'Zimbabwe', 'Malawi'], answer: 2, explanation: 'Victoria Falls lies on the border between Zambia and Zimbabwe.' },

];
