const staticGeographyQuestions = [

  // ===================== RIVERS =====================
  { id: 'rivers-001', category: 'Rivers', question: "The Ganga River, considered sacred by millions and central to India's cultural and religious heritage, originates from a glacier in the Himalayas before flowing across the Indo-Gangetic Plain. In which Indian state does its source glacier lie?", options: ['Uttarakhand', 'Himachal Pradesh', 'Uttar Pradesh', 'Sikkim'], answer: 0, explanation: 'The Ganga originates from the Gangotri Glacier (Gaumukh) in Uttarakhand.' },
  { id: 'rivers-002', category: 'Rivers', question: 'The Yangtze River is the longest river in Asia and has historically supported dense agricultural settlement along its banks. It flows entirely within, and finally empties into the sea off the coast of, which country?', options: ['Japan', 'China', 'Vietnam', 'South Korea'], answer: 1, explanation: 'The Yangtze flows entirely within China and empties into the East China Sea.' },
  { id: 'rivers-003', category: 'Rivers', question: 'The Mississippi River, along with its tributary the Missouri, forms one of the largest river systems in the world and was historically vital for trade and transport in North America. Into which body of water does it empty?', options: ['Atlantic Ocean', 'Pacific Ocean', 'Gulf of Mexico', 'Hudson Bay'], answer: 1, explanation: 'The Mississippi River empties into the Gulf of Mexico.' },
  { id: 'rivers-004', category: 'Rivers', question: 'The Indus River gave its name to the Indian subcontinent and nurtured one of the earliest urban civilizations. Rising in Tibet and flowing largely through Pakistan, into which sea does it finally drain?', options: ['Arabian Sea', 'Bay of Bengal', 'Caspian Sea', 'Persian Gulf'], answer: 1, explanation: 'The Indus River empties into the Arabian Sea near Karachi.' },
  { id: 'rivers-005', category: 'Rivers', question: 'The Volga is the longest river in Europe and has long served as a major inland waterway for Russia. Into which body of water does the Volga eventually drain?', options: ['Black Sea', 'Baltic Sea', 'Caspian Sea', 'Sea of Azov'], answer: 0, explanation: 'The Volga River drains into the landlocked Caspian Sea.' },

  // ===================== MOUNTAINS & PEAKS =====================
  { id: 'mountains-001', category: 'Mountains & Peaks', question: "Mount Everest, the world's highest peak above sea level, straddles the border of Nepal and the Tibet Autonomous Region of China. It forms part of which major mountain range?", options: ['Karakoram', 'Himalayas', 'Hindu Kush', 'Pamirs'], answer: 1, explanation: 'Mount Everest is part of the Himalayan mountain range.' },
  { id: 'mountains-002', category: 'Mountains & Peaks', question: 'K2, the second-highest mountain on Earth, is notorious among climbers for its extreme difficulty and high fatality rate. It is located in which mountain range on the border of Pakistan and China?', options: ['Himalayas', 'Karakoram', 'Hindu Kush', 'Zagros'], answer: 1, explanation: 'K2 lies in the Karakoram range.' },
  { id: 'mountains-003', category: 'Mountains & Peaks', question: 'The Andes form the longest continental mountain range in the world, running along the western edge of a continent and influencing the climate and culture of many nations. On which continent are the Andes located?', options: ['North America', 'South America', 'Africa', 'Asia'], answer: 1, explanation: 'The Andes run along the western coast of South America.' },
  { id: 'mountains-004', category: 'Mountains & Peaks', question: 'The Alps are a major mountain range stretching across several European countries and are popular for both winter sports and mountaineering. What is the name of the highest peak of the Alps, located near the France-Italy border?', options: ['Matterhorn', 'Mont Blanc', 'Eiger', 'Zugspitze'], answer: 1, explanation: 'Mont Blanc, on the France-Italy border, is the highest peak of the Alps.' },
  { id: 'mountains-005', category: 'Mountains & Peaks', question: 'The Ural Mountains run in a roughly north-south direction and are traditionally regarded as a natural boundary. Which two continents do the Urals separate?', options: ['Asia and Africa', 'Europe and Asia', 'Europe and Africa', 'Asia and North America'], answer: 1, explanation: 'The Ural Mountains form part of the conventional boundary between Europe and Asia.' },

  // ===================== LAKES =====================
  { id: 'lakes-001', category: 'Lakes', question: 'The Caspian Sea, despite its name, is classified as the largest lake in the world by area and is bordered by five countries. Which of the following countries does NOT border the Caspian Sea?', options: ['Russia', 'Iran', 'Turkey', 'Kazakhstan'], answer: 2, explanation: 'The Caspian Sea is bordered by Russia, Kazakhstan, Turkmenistan, Iran, and Azerbaijan; Turkey does not border it.' },
  { id: 'lakes-002', category: 'Lakes', question: 'Lake Superior is the largest of the Great Lakes by surface area and is considered the largest freshwater lake in the world by area. It lies on the border between the United States and which other country?', options: ['Mexico', 'Canada', 'None, it is entirely in the USA', 'Greenland'], answer: 1, explanation: 'Lake Superior lies on the border between the USA and Canada.' },
  { id: 'lakes-003', category: 'Lakes', question: 'The Dead Sea is renowned for its extremely high salinity, which allows swimmers to float effortlessly, and for being the lowest point on the land surface of the Earth. It lies on the border between Jordan and which other country?', options: ['Israel', 'Syria', 'Lebanon', 'Egypt'], answer: 0, explanation: 'The Dead Sea lies on the border between Jordan and Israel.' },
  { id: 'lakes-004', category: 'Lakes', question: 'Lake Victoria is the largest lake in Africa by area and serves as a major source for one of the world\'s great rivers. Which river flows out of Lake Victoria?', options: ['Congo River', 'Niger River', 'Nile River', 'Zambezi River'], answer: 2, explanation: 'Lake Victoria is a principal source of the Nile River.' },
  { id: 'lakes-005', category: 'Lakes', question: 'Lake Titicaca, set high in the Andes, is often cited as the highest navigable lake in the world and holds deep cultural significance for Andean civilizations. It straddles the border between Peru and which other country?', options: ['Chile', 'Bolivia', 'Ecuador', 'Colombia'], answer: 1, explanation: 'Lake Titicaca lies on the border between Peru and Bolivia.' },

  // ===================== WATERFALLS =====================
  { id: 'waterfalls-001', category: 'Waterfalls', question: "Angel Falls is recognized as the world's tallest uninterrupted waterfall, plunging from the edge of a tabletop mountain in a remote rainforest region. In which country is Angel Falls located?", options: ['Brazil', 'Venezuela', 'Colombia', 'Guyana'], answer: 1, explanation: 'Angel Falls is located in Canaima National Park, Venezuela.' },
  { id: 'waterfalls-002', category: 'Waterfalls', question: 'Niagara Falls, a major tourist attraction and source of hydroelectric power, actually consists of three separate falls. It lies on the border between the United States and which other country?', options: ['Mexico', 'Canada', 'None, it is entirely in the USA', 'Cuba'], answer: 1, explanation: 'Niagara Falls straddles the border between the USA and Canada.' },
  { id: 'waterfalls-003', category: 'Waterfalls', question: 'Victoria Falls, known locally as "the Smoke that Thunders," is one of the largest waterfalls in the world by combined width and height. It is formed by which African river?', options: ['Congo River', 'Zambezi River', 'Limpopo River', 'Orange River'], answer: 1, explanation: 'Victoria Falls is formed by the Zambezi River.' },
  { id: 'waterfalls-004', category: 'Waterfalls', question: 'Iguazu Falls consists of a vast system of hundreds of individual waterfalls set within a lush subtropical rainforest and is a UNESCO World Heritage Site. It lies on the border between Brazil and which other country?', options: ['Uruguay', 'Paraguay', 'Argentina', 'Bolivia'], answer: 2, explanation: 'Iguazu Falls lies on the border of Brazil and Argentina (with Paraguay nearby).' },
  { id: 'waterfalls-005', category: 'Waterfalls', question: 'Yosemite Falls is the tallest waterfall in North America and is a centerpiece attraction of a famous national park known for its granite cliffs. In which US state is Yosemite Falls located?', options: ['Oregon', 'California', 'Washington', 'Nevada'], answer: 1, explanation: 'Yosemite Falls is located in Yosemite National Park, California.' },

  // ===================== DESERTS =====================
  { id: 'deserts-001', category: 'Deserts', question: 'The Sahara is the largest hot desert in the world, covering much of the northern part of a continent and experiencing extreme temperature variations between day and night. On which continent is the Sahara located?', options: ['Asia', 'Africa', 'Australia', 'South America'], answer: 1, explanation: 'The Sahara Desert spans much of North Africa.' },
  { id: 'deserts-002', category: 'Deserts', question: 'The Thar Desert, also known as the Great Indian Desert, is a large arid region characterized by sand dunes and sparse vegetation. It lies primarily in which Indian state, extending into Pakistan?', options: ['Gujarat', 'Rajasthan', 'Punjab', 'Haryana'], answer: 1, explanation: 'The Thar Desert lies mainly in Rajasthan, extending into Pakistan.' },
  { id: 'deserts-003', category: 'Deserts', question: 'The Kalahari Desert is a semi-arid sandy region in southern Africa known for its unique wildlife adapted to scarce water. Which of the following countries does the Kalahari NOT extend into?', options: ['Botswana', 'Namibia', 'South Africa', 'Kenya'], answer: 3, explanation: 'The Kalahari Desert spans Botswana, Namibia and South Africa, but not Kenya.' },
  { id: 'deserts-004', category: 'Deserts', question: 'The Arabian Desert covers most of the Arabian Peninsula and includes the Rub al Khali, one of the largest continuous sand deserts in the world. In which region of the world is it located?', options: ['East Asia', 'Middle East', 'Central Asia', 'North Africa'], answer: 1, explanation: 'The Arabian Desert lies in the Middle East, covering most of the Arabian Peninsula.' },
  { id: 'deserts-005', category: 'Deserts', question: 'Although often not pictured as a desert due to its ice cover, a continent qualifies as the largest desert in the world by area because of its extremely low precipitation. Which continent is this?', options: ['Africa', 'Asia', 'Antarctica', 'Australia'], answer: 2, explanation: 'Antarctica is classified as the largest desert in the world due to its minimal precipitation, despite being ice-covered.' },

  // ===================== GRASSLANDS =====================
  { id: 'grasslands-001', category: 'Grasslands', question: 'The Prairies are extensive temperate grasslands that historically supported vast herds of bison and later became a major agricultural region for wheat cultivation. On which continent are the Prairies located?', options: ['South America', 'North America', 'Africa', 'Europe'], answer: 1, explanation: 'The Prairies are temperate grasslands of North America, spanning the USA and Canada.' },
  { id: 'grasslands-002', category: 'Grasslands', question: 'The Steppes are vast, largely treeless grassland plains that historically served as migration routes for nomadic peoples. They stretch across which continent, from Eastern Europe into Central Asia?', options: ['Africa', 'Eurasia', 'South America', 'Australia'], answer: 1, explanation: 'The Steppes extend across Eurasia, from Eastern Europe through Central Asia.' },
  { id: 'grasslands-003', category: 'Grasslands', question: 'The Savanna is a tropical grassland ecosystem characterized by scattered trees and seasonal rainfall, and it supports large populations of grazing animals and predators. On which continent is the Savanna most extensively found?', options: ['Africa', 'Asia', 'South America', 'Europe'], answer: 0, explanation: 'The Savanna biome is most extensively found in Africa, though it also occurs elsewhere.' },
  { id: 'grasslands-004', category: 'Grasslands', question: 'The Pampas are fertile lowland grasslands renowned for cattle ranching and grain production, and they are strongly associated with a South American country. Which country?', options: ['Brazil', 'Chile', 'Argentina', 'Peru'], answer: 2, explanation: 'The Pampas are grasslands primarily located in Argentina, extending into Uruguay.' },
  { id: 'grasslands-005', category: 'Grasslands', question: 'The Veld refers to open, elevated grassland regions in a southern African country, used extensively for grazing and agriculture. In which country is the Veld located?', options: ['South Africa', 'Namibia', 'Zimbabwe', 'Botswana'], answer: 0, explanation: 'The Veld is a term used for grassland regions in South Africa.' },

  // ===================== OCEANS & SEAS =====================
  { id: 'oceans-001', category: 'Oceans & Seas', question: 'The Pacific Ocean is the largest and deepest of the world\'s oceanic divisions, extending from the Arctic in the north to the Southern Ocean in the south. Which ocean is the second largest in the world?', options: ['Indian Ocean', 'Atlantic Ocean', 'Arctic Ocean', 'Southern Ocean'], answer: 1, explanation: 'The Atlantic Ocean is the second-largest ocean after the Pacific.' },
  { id: 'oceans-002', category: 'Oceans & Seas', question: 'The Mediterranean Sea is an almost fully enclosed sea bordered by Europe, North Africa, and the Middle East, and it has been central to trade and civilization for millennia. Which ocean does the Mediterranean Sea connect to via the Strait of Gibraltar?', options: ['Indian Ocean', 'Pacific Ocean', 'Atlantic Ocean', 'Arctic Ocean'], answer: 2, explanation: 'The Mediterranean Sea connects to the Atlantic Ocean through the Strait of Gibraltar.' },
  { id: 'oceans-003', category: 'Oceans & Seas', question: 'The Red Sea is a narrow, elongated seawater body known for its high salinity and vibrant coral reefs. It separates the Arabian Peninsula from which continent?', options: ['Asia', 'Africa', 'Europe', 'Australia'], answer: 1, explanation: 'The Red Sea separates the Arabian Peninsula from Africa.' },
  { id: 'oceans-004', category: 'Oceans & Seas', question: 'The Arctic Ocean is the smallest and shallowest of the world\'s oceans, largely covered by sea ice for much of the year. It surrounds which geographic pole?', options: ['South Pole', 'North Pole', 'Equator', 'Tropic of Cancer'], answer: 1, explanation: 'The Arctic Ocean surrounds the North Pole.' },
  { id: 'oceans-005', category: 'Oceans & Seas', question: 'The Indian Ocean is the third-largest of the world\'s oceanic divisions and plays a critical role in global trade routes connecting Africa, Asia, and Australia. Which country lies at its northern boundary, giving it its name?', options: ['India', 'Sri Lanka', 'Indonesia', 'Pakistan'], answer: 0, explanation: 'The Indian Ocean is named after India, which lies along its northern edge.' },

  // ===================== STRAITS & GULFS =====================
  { id: 'straits-001', category: 'Straits & Gulfs', question: 'The Strait of Malacca is one of the busiest and most strategically important shipping lanes in the world, linking the Indian Ocean to the Pacific Ocean. It lies between Sumatra (Indonesia) and which country?', options: ['Thailand', 'Malaysia', 'Singapore only', 'Myanmar'], answer: 1, explanation: 'The Strait of Malacca lies between the Indonesian island of Sumatra and Malaysia (with Singapore at its southern end).' },
  { id: 'straits-002', category: 'Straits & Gulfs', question: 'The Palk Strait separates two South Asian nations and connects the Palk Bay with the Bay of Bengal. Which two countries does it lie between?', options: ['India and Bangladesh', 'India and Sri Lanka', 'India and Myanmar', 'Sri Lanka and Maldives'], answer: 1, explanation: 'The Palk Strait lies between India and Sri Lanka.' },
  { id: 'straits-003', category: 'Straits & Gulfs', question: 'The Persian Gulf is a vital waterway for global oil transport, bordered by Iran on one side and several Arab nations on the other. Which country lies to the north of the Persian Gulf?', options: ['Iran', 'Iraq', 'Saudi Arabia', 'Oman'], answer: 0, explanation: 'The Persian Gulf is bordered to the north and east by Iran.' },
  { id: 'straits-004', category: 'Straits & Gulfs', question: 'The Strait of Hormuz is one of the most strategically significant chokepoints in the world due to the volume of oil shipped through it daily. Which two water bodies does it connect?', options: ['Red Sea and Arabian Sea', 'Persian Gulf and Gulf of Oman', 'Persian Gulf and Red Sea', 'Arabian Sea and Gulf of Aden'], answer: 1, explanation: 'The Strait of Hormuz connects the Persian Gulf with the Gulf of Oman.' },
  { id: 'straits-005', category: 'Straits & Gulfs', question: 'The Gulf of Mexico is a large ocean basin bordered by the southeastern United States, eastern Mexico, and Cuba, and it is significant for oil production and fisheries. Which of the following countries does NOT border the Gulf of Mexico?', options: ['United States', 'Mexico', 'Cuba', 'Colombia'], answer: 3, explanation: 'The Gulf of Mexico is bordered by the USA, Mexico, and Cuba, but not Colombia.' },

  // ===================== ISLANDS =====================
  { id: 'islands-001', category: 'Islands', question: "Greenland, largely covered by an ice sheet, is recognized as the world's largest island (as Australia is classified as a continent rather than an island). It is an autonomous territory of which country?", options: ['Iceland', 'Norway', 'Denmark', 'Canada'], answer: 2, explanation: 'Greenland is an autonomous territory of Denmark.' },
  { id: 'islands-002', category: 'Islands', question: 'Madagascar, known for its exceptional biodiversity and many endemic species, is the largest island off the coast of Africa. It lies in which ocean?', options: ['Atlantic Ocean', 'Pacific Ocean', 'Indian Ocean', 'Southern Ocean'], answer: 2, explanation: 'Madagascar lies in the Indian Ocean, off the southeastern coast of Africa.' },
  { id: 'islands-003', category: 'Islands', question: "Borneo is the third-largest island in the world and is politically divided among three countries. Which of the following is NOT one of the countries that share Borneo?", options: ['Indonesia', 'Malaysia', 'Brunei', 'Philippines'], answer: 3, explanation: "Largest island → Greenland\n2nd largest → New Guinea\n3rd largest → Borneo\nLargest island in Africa → Madagascar\nLargest island of Japan → Honshu\nLargest island of Indonesia → Sumatra\nBorneo → shared by 3 countries: Indonesia + Malaysia + Brunei"},
  { id: 'islands-004', category: 'Islands', question: 'Sri Lanka is an island nation in the Indian Ocean, separated from the Indian subcontinent by the Palk Strait and known for its tea plantations. What is the capital city of Sri Lanka?', options: ['Colombo', 'Sri Jayawardenepura Kotte', 'Kandy', 'Galle'], answer: 1, explanation: 'Sri Jayawardenepura Kotte is the official administrative capital of Sri Lanka, though Colombo is the largest city and commercial hub.' },
  { id: 'islands-005', category: 'Islands', question: 'The Maldives is an island nation made up of a chain of atolls in the Indian Ocean and is known as the lowest-lying country in the world. It is located to the southwest of which larger South Asian country?', options: ['Sri Lanka', 'India', 'Pakistan', 'Bangladesh'], answer: 1, explanation: 'The Maldives lies to the southwest of India in the Indian Ocean.' },

  // ===================== INDIAN GEOGRAPHY =====================
  { id: 'india-001', category: 'Indian Geography', question: 'Kangchenjunga, the third-highest mountain in the world, is the highest peak located entirely within India. In which Indian state is Kangchenjunga situated?', options: ['Arunachal Pradesh', 'Sikkim', 'Himachal Pradesh', 'Uttarakhand'], answer: 1, explanation: 'Kangchenjunga is located on the border of Sikkim and Nepal, making it India\'s highest peak.' },
  { id: 'india-002', category: 'Indian Geography', question: 'The Godavari River, often referred to as the "Ganga of the South," is the longest river flowing entirely within peninsular India. In which Indian state does the Godavari originate?', options: ['Karnataka', 'Madhya Pradesh', 'Maharashtra', 'Chhattisgarh'], answer: 2, explanation: 'The Godavari originates near Trimbakeshwar in Maharashtra.' },
  { id: 'india-003', category: 'Indian Geography', question: 'Rajasthan is the largest Indian state by area and is home to much of the Thar Desert as well as the historic Aravalli Range. Which city serves as the capital of Rajasthan?', options: ['Jodhpur', 'Udaipur', 'Jaipur', 'Ajmer'], answer: 2, explanation: 'Jaipur is the capital of Rajasthan.' },
  { id: 'india-004', category: 'Indian Geography', question: "Indira Point, located in the Andaman and Nicobar Islands, is recognized as India's southernmost point. On which island is Indira Point situated?", options: ['Car Nicobar', 'Great Nicobar', 'Little Andaman', 'South Andaman'], answer: 1, explanation: 'Indira Point is located on Great Nicobar Island.' },
  { id: 'india-005', category: 'Indian Geography', question: "Sambhar Lake is India's largest saline (inland saltwater) lake and has historically been an important source of salt production. In which Indian state is Sambhar Lake located?", options: ['Gujarat', 'Rajasthan', 'Madhya Pradesh', 'Haryana'], answer: 1, explanation: 'Sambhar Lake is located in Rajasthan.' },

  // ===================== WORLD GEOGRAPHY =====================
  { id: 'world-001', category: 'World Geography', question: 'Russia spans two continents and is by far the largest country in the world by land area, stretching across eleven time zones. Which country is the second-largest in the world by area?', options: ['China', 'Canada', 'United States', 'Brazil'], answer: 1, explanation: 'Canada is the second-largest country in the world by land area, after Russia.' },
  { id: 'world-002', category: 'World Geography', question: 'Vatican City is an independent city-state entirely surrounded by the city of Rome and is recognized as the smallest country in the world by both area and population. Within which country is Vatican City enclaved?', options: ['France', 'Spain', 'Italy', 'Switzerland'], answer: 2, explanation: 'Vatican City is enclaved within Rome, Italy.' },
  { id: 'world-003', category: 'World Geography', question: 'Asia is the largest and most populous continent, covering roughly one-third of the Earth\'s land area. Which continent is the second-largest by area?', options: ['Africa', 'North America', 'South America', 'Europe'], answer: 0, explanation: 'Africa is the second-largest continent by area after Asia.' },
  { id: 'world-004', category: 'World Geography', question: 'The Equator is an imaginary line that divides the Earth into the Northern and Southern Hemispheres and passes through several countries and oceans. Through which of the following countries does the Equator pass?', options: ['Kenya', 'South Africa', 'Egypt', 'Morocco'], answer: 0, explanation: "South America\n\n🇪🇨 Ecuador\n🇨🇴 Colombia\n🇧🇷 Brazil\n\nAfrica\n\n🇸🇹 São Tomé and Príncipe\n🇬🇦 Gabon\n🇨🇬 Republic of the Congo\n🇨🇩 Democratic Republic of the Congo (DRC)\n🇺🇬 Uganda\n🇰🇪 Kenya\n🇸🇴 Somalia\n\nAsia / Indian & Pacific region\n\n🇲🇻 Maldives\n🇮🇩 Indonesia\n🇰🇮 Kiribati" ,
    notes: ["Tropic of Cancer → 23½° N ✅\n\nYe India ke 8 states se pass hota hai:\n\nGujarat → Rajasthan → Madhya Pradesh → Chhattisgarh → Jharkhand → West Bengal → Tripura → Mizoram"],},
  { id: 'world-005', category: 'World Geography', question: 'The Prime Meridian, which marks zero degrees longitude and is the reference for Greenwich Mean Time, passes through the Royal Observatory in which city?', options: ['Paris', 'London (Greenwich)', 'Edinburgh', 'Dublin'], answer: 1, explanation: 'The Prime Meridian passes through Greenwich, London.' },

  // ===================== CLIMATE =====================
  { id: 'climate-001', category: 'Climate', question: 'The Köppen climate classification system is the most widely used method for classifying the world\'s climates, based on temperature and precipitation patterns. Who developed this classification system?', options: ['Alfred Wegener', 'Wladimir Köppen', 'Alexander von Humboldt', 'Vidal de la Blache'], answer: 1, explanation: 'The Köppen climate classification system was developed by German climatologist Wladimir Köppen.' },
  { id: 'climate-002', category: 'Climate', question: 'The Indian monsoon is a seasonal reversal of wind direction that brings the bulk of India\'s annual rainfall between June and September. From which general direction do the monsoon winds primarily blow during this season?', options: ['Northeast', 'Southwest', 'Northwest', 'Southeast'], answer: 1, explanation: 'The southwest monsoon winds bring the majority of India\'s rainfall between June and September.' },
  { id: 'climate-003', category: 'Climate', question: 'El Niño is a climate pattern characterized by the periodic warming of sea surface temperatures, which affects weather patterns worldwide. In which ocean does El Niño primarily originate?', options: ['Atlantic Ocean', 'Indian Ocean', 'Pacific Ocean', 'Arctic Ocean'], answer: 2, explanation: 'El Niño originates in the equatorial Pacific Ocean.' },
  { id: 'climate-004', category: 'Climate', question: 'The Tropic of Cancer marks the northernmost point at which the sun can appear directly overhead and passes through several countries, including India. Through how many Indian states does the Tropic of Cancer pass?', options: ['6', '7', '8', '9'], answer: 2, explanation: 'The Tropic of Cancer passes through 8 Indian states, from Gujarat to Mizoram.' },
  { id: 'climate-005', category: 'Climate', question: 'A Mediterranean climate is characterized by hot, dry summers and mild, wet winters, and is found not only around the Mediterranean Sea but also in parts of California and Chile. Which of the following regions is famous for this type of climate?', options: ['Amazon Basin', 'California', 'Siberia', 'Sahel'], answer: 1, explanation: 'California experiences a Mediterranean-type climate with hot, dry summers and mild, wet winters.' },

  // ===================== SOILS =====================
  { id: 'soils-001', category: 'Soils', question: 'Black soil, also known as regur soil, is renowned for its high moisture retention and is particularly well-suited for growing cotton. It is predominantly found in which Indian plateau region?', options: ['Chota Nagpur Plateau', 'Deccan Plateau', 'Malwa Plateau', 'Shillong Plateau'], answer: 1, explanation: 'Black soil (regur) is predominantly found in the Deccan Plateau and is ideal for cotton cultivation.' },
  { id: 'soils-002', category: 'Soils', question: 'Alluvial soil is the most extensive and agriculturally important soil type in India, formed by sediment deposits from rivers. It is most extensively found in which region of India?', options: ['Deccan Plateau', 'Indo-Gangetic Plain', 'Western Ghats', 'Thar Desert'], answer: 1, explanation: 'Alluvial soil is most extensively found in the fertile Indo-Gangetic Plain.' },
  { id: 'soils-003', category: 'Soils', question: 'Laterite soil forms in regions with heavy rainfall and high temperatures, leading to leaching of soluble minerals, and it is generally less fertile. In which climatic zones is laterite soil typically found?', options: ['Arid zones', 'Tropical, high-rainfall zones', 'Polar zones', 'Temperate zones'], answer: 1, explanation: 'Laterite soil forms in tropical regions with heavy rainfall due to intense leaching.' },
  { id: 'soils-004', category: 'Soils', question: 'Desert soil is typically sandy, low in humus, and often high in soluble salts, making it generally unsuitable for agriculture without irrigation. In which Indian state is desert soil most predominant?', options: ['Punjab', 'Rajasthan', 'Bihar', 'Kerala'], answer: 1, explanation: 'Desert soil is most predominant in Rajasthan, especially in the Thar Desert region.' },
  { id: 'soils-005', category: 'Soils', question: 'Red soil develops from the weathering of ancient crystalline and metamorphic rocks and owes its color to iron oxide content. It is commonly found in which part of India?', options: ['Northern plains', 'Southern and eastern parts of the Deccan Plateau', 'Himalayan foothills', 'Coastal Gujarat'], answer: 1, explanation: 'Red soil is commonly found in the southern and eastern parts of the Deccan Plateau.' },

  // ===================== FORESTS =====================
  { id: 'forests-001', category: 'Forests', question: 'The Amazon Rainforest is the largest tropical rainforest in the world and is often referred to as "the lungs of the Earth" due to the vast amount of oxygen it produces. It is located primarily in which country?', options: ['Colombia', 'Peru', 'Brazil', 'Venezuela'], answer: 2, explanation: 'The majority of the Amazon Rainforest lies within Brazil.' },
  { id: 'forests-002', category: 'Forests', question: 'The Taiga, also known as the boreal forest, is the largest land biome on Earth, consisting mainly of coniferous trees. It stretches across the northern regions of which two continents?', options: ['Asia and Africa', 'North America and Europe/Asia (Eurasia)', 'South America and Africa', 'Australia and Antarctica'], answer: 1, explanation: 'The Taiga stretches across northern North America and Eurasia (including Siberia and Scandinavia).' },
  { id: 'forests-003', category: 'Forests', question: 'The Sundarbans is the largest mangrove forest in the world and is home to the Bengal tiger, spread across a river delta region. It is shared between India and which other country?', options: ['Myanmar', 'Bangladesh', 'Nepal', 'Bhutan'], answer: 1, explanation: 'The Sundarbans mangrove forest is shared between India and Bangladesh.' },
  { id: 'forests-004', category: 'Forests', question: 'Tropical deciduous forests, which shed their leaves during a particular season, cover large parts of India and are influenced heavily by the monsoon. What is the primary factor that causes trees in these forests to shed their leaves?', options: ['Excess rainfall', 'Seasonal dry period', 'Cold winters', 'Soil salinity'], answer: 1, explanation: 'Deciduous forests shed leaves during the dry season to conserve water.' },
  { id: 'forests-005', category: 'Forests', question: 'The Congo Rainforest is the second-largest tropical rainforest in the world after the Amazon and is home to immense biodiversity. On which continent is the Congo Rainforest located?', options: ['Asia', 'South America', 'Africa', 'Australia'], answer: 2, explanation: 'The Congo Rainforest is located in Central Africa.' },

  // ===================== AGRICULTURE =====================
  { id: 'agriculture-001', category: 'Agriculture', question: 'The Green Revolution significantly boosted food grain production in India during the 1960s through the use of high-yielding seed varieties and modern techniques. Which Indian state is most closely associated with the success of the Green Revolution?', options: ['Punjab', 'Bihar', 'West Bengal', 'Kerala'], answer: 0, explanation: 'Punjab was at the forefront of India\'s Green Revolution, especially in wheat production.' },
  { id: 'agriculture-002', category: 'Agriculture', question: 'Rice is a staple food crop for more than half of the world\'s population and requires abundant water and warm temperatures for cultivation. Which country is the largest producer of rice in the world?', options: ['India', 'China', 'Indonesia', 'Thailand'], answer: 1, explanation: 'China is the largest producer of rice in the world, followed closely by India.' },
  { id: 'agriculture-003', category: 'Agriculture', question: 'Wheat is a major Rabi crop in India, sown in winter and harvested in spring, requiring moderate rainfall and cool climate during growth. Which of the following is classified as a Rabi crop?', options: ['Rice', 'Cotton', 'Wheat', 'Sugarcane'], answer: 2, explanation: 'Wheat is a Rabi crop, sown in winter and harvested in spring.' },
  { id: 'agriculture-004', category: 'Agriculture', question: 'Jute, often called the "golden fiber," is used to make sacks, ropes, and other coarse fabrics, and requires high humidity and fertile alluvial soil. Which Indian state is the leading producer of jute?', options: ['Assam', 'West Bengal', 'Odisha', 'Bihar'], answer: 1, explanation: 'West Bengal is the leading producer of jute in India.' },
  { id: 'agriculture-005', category: 'Agriculture', question: 'Coffee cultivation in India is concentrated in the hilly regions of the south, where cool temperatures and well-drained soil favor the crop. Which Indian state is the largest producer of coffee?', options: ['Tamil Nadu', 'Kerala', 'Karnataka', 'Andhra Pradesh'], answer: 2, explanation: 'Karnataka is the largest coffee-producing state in India.' },

  // ===================== MINERALS =====================
  { id: 'minerals-001', category: 'Minerals', question: 'Iron ore is a fundamental raw material for the steel industry, and India possesses substantial reserves concentrated in a few mineral-rich states. Which Indian state holds the largest reserves of iron ore?', options: ['Jharkhand', 'Odisha', 'Chhattisgarh', 'Karnataka'], answer: 1, explanation: 'Odisha holds the largest reserves of iron ore in India.' },
  { id: 'minerals-002', category: 'Minerals', question: 'Coal remains one of the most important sources of energy worldwide, particularly for electricity generation and industrial use. Which country is the largest producer of coal in the world?', options: ['India', 'United States', 'China', 'Australia'], answer: 2, explanation: 'China is by far the largest producer of coal in the world.' },
  { id: 'minerals-003', category: 'Minerals', question: 'Bauxite is the primary ore from which aluminum is extracted, and its production requires specific tropical weathering conditions. Which of the following is the principal use of bauxite?', options: ['Steel production', 'Aluminum production', 'Cement production', 'Fertilizer production'], answer: 1, explanation: 'Bauxite is the primary ore used to produce aluminum.' },
  { id: 'minerals-004', category: 'Minerals', question: 'Petroleum, a fossil fuel formed from ancient marine organisms, is one of the most traded commodities in the world and is concentrated in certain sedimentary basins. Which country holds the largest proven reserves of petroleum in the world?', options: ['Saudi Arabia', 'Venezuela', 'Russia', 'United States'], answer: 1, explanation: 'Venezuela holds the largest proven oil reserves in the world.' },
  { id: 'minerals-005', category: 'Minerals', question: 'Gold is a precious metal that has been mined and valued by human civilizations for thousands of years, both for ornamentation and as a store of wealth. Which country has historically been the world\'s largest producer of gold?', options: ['South Africa', 'China', 'Australia', 'Russia'], answer: 1, explanation: "Historically largest/dominant gold producer → South Africa 🇿🇦\nCurrently largest gold-producing country → China 🇨🇳"},

  // ===================== EARTH =====================
  { id: 'earth-001', category: 'Earth', question: "The Earth's outermost solid layer, on which continents and oceans rest, is relatively thin compared to the layers beneath it. What is this outermost layer called?", options: ['Mantle', 'Crust', 'Outer core', 'Inner core'], answer: 1, explanation: "The crust is the Earth's outermost solid layer." },
  { id: 'earth-002', category: 'Earth', question: "The theory of plate tectonics explains the movement of large sections of the Earth's lithosphere, which causes earthquakes, volcanic activity, and the formation of mountain ranges. What are these large moving sections of the lithosphere called?", options: ['Fault lines', 'Tectonic plates', 'Continental shelves', 'Subduction zones'], answer: 1, explanation: "Tectonic plates are the large sections of the Earth's lithosphere that move over the mantle." },
  { id: 'earth-003', category: 'Earth', question: 'The rotation of the Earth on its own axis is responsible for the cycle of day and night. Approximately how long does one complete rotation of the Earth take?', options: ['12 hours', '24 hours', '365 days', '30 days'], answer: 1, explanation: 'The Earth takes approximately 24 hours to complete one full rotation on its axis.' },
  { id: 'earth-004', category: 'Earth', question: "The Earth's revolution around the Sun, combined with the tilt of its axis, is responsible for the changing seasons throughout the year. Approximately how long does one complete revolution around the Sun take?", options: ['24 hours', '30 days', '365.25 days', '100 days'], answer: 2, explanation: "The Earth takes approximately 365.25 days to complete one revolution around the Sun." },
  { id: 'earth-005', category: 'Earth', question: "The Earth's core is believed to be composed primarily of two metallic elements, with the inner core being solid due to immense pressure despite extremely high temperatures. What are these two primary elements?", options: ['Iron and Nickel', 'Silicon and Magnesium', 'Aluminum and Iron', 'Carbon and Sulfur'], answer: 0, explanation: "The Earth's core is composed primarily of iron and nickel." },

  // ===================== ATMOSPHERE =====================
  { id: 'atmosphere-001', category: 'Atmosphere', question: 'The ozone layer plays a crucial role in absorbing most of the Sun\'s harmful ultraviolet radiation, protecting life on Earth. In which layer of the atmosphere is the ozone layer located?', options: ['Troposphere', 'Stratosphere', 'Mesosphere', 'Thermosphere'], answer: 1, explanation: 'The ozone layer is located within the stratosphere.' },
  { id: 'atmosphere-002', category: 'Atmosphere', question: 'The troposphere is the lowest layer of Earth\'s atmosphere and is where nearly all weather phenomena, such as clouds and storms, occur. Approximately how far does the troposphere extend above the Earth\'s surface?', options: ['Up to 5 km', 'Up to 12-15 km', 'Up to 50 km', 'Up to 100 km'], answer: 1, explanation: 'The troposphere extends up to approximately 12-15 km above the Earth\'s surface (higher at the equator, lower at the poles).' },
  { id: 'atmosphere-003', category: 'Atmosphere', question: 'Greenhouse gases trap heat within Earth\'s atmosphere, contributing to the natural greenhouse effect that keeps the planet warm enough to support life, but excess amounts drive climate change. Which of the following is considered the most abundant greenhouse gas contributing to human-induced climate change?', options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'], answer: 1, explanation: 'Carbon dioxide is the most significant greenhouse gas contributing to human-induced climate change.' },
  { id: 'atmosphere-004', category: 'Atmosphere', question: "Earth's atmosphere is composed of a mixture of gases, with one gas making up the largest proportion by volume. Which gas is most abundant in the Earth's atmosphere?", options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Argon'], answer: 2, explanation: "Nitrogen makes up about 78% of the Earth's atmosphere by volume, the largest proportion of any gas." },
  { id: 'atmosphere-005', category: 'Atmosphere', question: "The ionosphere is a region of the Earth's upper atmosphere containing a high concentration of charged particles, and it plays a key role in radio communication. Why is the ionosphere significant for long-distance radio transmission?", options: ['It absorbs all radio waves', 'It reflects radio waves back to Earth', 'It blocks sunlight', 'It generates radio waves'], answer: 1, explanation: 'The ionosphere reflects radio waves back toward the Earth, enabling long-distance radio communication.' },

  // ===================== OCEANOGRAPHY =====================
  { id: 'oceanography-001', category: 'Oceanography', question: 'The Mariana Trench, located in the western Pacific Ocean, contains the deepest known point in any of the world\'s oceans. What is this deepest point called?', options: ['Puerto Rico Trench', 'Challenger Deep', 'Java Trench', 'Tonga Trench'], answer: 1, explanation: 'The Challenger Deep, within the Mariana Trench, is the deepest known point in the world\'s oceans.' },
  { id: 'oceanography-002', category: 'Oceanography', question: 'The continental shelf is a gently sloping underwater extension of a continent, typically rich in marine life and important for fishing and offshore drilling. What generally marks the outer boundary of the continental shelf?', options: ['A steep drop-off into deep ocean (continental slope)', 'The equator', 'The mid-ocean ridge', 'The Arctic Circle'], answer: 0, explanation: 'The continental shelf ends at the continental slope, where the seabed drops steeply toward the deep ocean floor.' },
  { id: 'oceanography-003', category: 'Oceanography', question: 'The Gulf Stream is a powerful, warm ocean current that significantly influences the climate of Western Europe by carrying warm water northward. In which ocean does the Gulf Stream primarily flow?', options: ['Pacific Ocean', 'Indian Ocean', 'Atlantic Ocean', 'Arctic Ocean'], answer: 2, explanation: 'The Gulf Stream is a warm current flowing through the Atlantic Ocean.' },
  { id: 'oceanography-004', category: 'Oceanography', question: 'Ocean tides are the periodic rise and fall of sea levels, caused primarily by the gravitational pull of a celestial body along with the Sun\'s influence. Which celestial body has the greatest influence on Earth\'s tides?', options: ['The Sun', 'The Moon', 'Mars', 'Venus'], answer: 1, explanation: "The Moon's gravitational pull is the primary driver of Earth's tides, with the Sun playing a secondary role." },
  { id: 'oceanography-005', category: 'Oceanography', question: 'Salinity refers to the concentration of dissolved salts in seawater and varies across different seas due to evaporation, precipitation, and freshwater inflow. Which of the following seas is known for having one of the highest salinity levels among the world\'s seas?', options: ['Baltic Sea', 'Red Sea', 'Black Sea', 'Bering Sea'], answer: 1, explanation: "Dead Sea\t~340‰\tJordan + Israel/West Bank region\nRed Sea\t~40–41‰\tAfrica + Arabian Peninsula ke beech"},

  // ===================== DAMS =====================
 
  // ===================== GEOGRAPHICAL SUPERLATIVES =====================
  { id: 'superlatives-001', category: 'Geographical Superlatives', question: 'Standing at 8,849 meters above sea level, this peak is recognized as the highest point on Earth and attracts climbers from around the world despite the extreme dangers involved. Which mountain holds this distinction?', options: ['K2', 'Kangchenjunga', 'Mount Everest', 'Lhotse'], answer: 2, explanation: 'Mount Everest, at 8,849 meters, is the highest mountain on Earth above sea level.' },
  { id: 'superlatives-002', category: 'Geographical Superlatives', question: "Two rivers are often debated for the title of the world's longest river, with one traditionally credited due to its length through northeastern Africa. Which river is conventionally regarded as the world's longest?", options: ['Amazon River', 'Nile River', 'Yangtze River', 'Mississippi River'], answer: 1, explanation: "The Nile River is conventionally regarded as the world's longest river, though some measurements favor the Amazon." },
  { id: 'superlatives-003', category: 'Geographical Superlatives', question: "The Challenger Deep, located within a trench in the western Pacific Ocean, represents the deepest known point in any of the world's oceans, reaching depths of nearly 11,000 meters. In which trench is the Challenger Deep located?", options: ['Puerto Rico Trench', 'Java Trench', 'Mariana Trench', 'Tonga Trench'], answer: 2, explanation: 'The Challenger Deep is located in the Mariana Trench.' },
  { id: 'superlatives-004', category: 'Geographical Superlatives', question: 'Russia is the largest country in the world by total area, spanning across Eastern Europe and northern Asia. Approximately how many time zones does Russia span?', options: ['5', '7', '9', '11'], answer: 3, explanation: 'Russia spans 11 time zones, more than any other country in the world.' },
  { id: 'superlatives-005', category: 'Geographical Superlatives', question: "Antarctica, though covered largely by ice, is officially recognized as the world's largest desert due to its extremely low levels of precipitation. Which desert is the largest hot desert in the world, by contrast?", options: ['Sahara Desert', 'Gobi Desert', 'Kalahari Desert', 'Arabian Desert'], answer: 0, explanation: 'The Sahara Desert is the largest hot desert in the world, while Antarctica is the largest desert overall (including cold deserts).' },

  // ===================== ADDITIONAL QUESTIONS =====================
  { id: 'extra-001', category: 'Rivers', question: "The Nile River is one of the world's longest rivers and has played a crucial role in the development of ancient Egyptian civilization. It flows northward before emptying into the Mediterranean Sea. On which continent is the Nile River primarily located?", options: ['Asia', 'Africa', 'Europe', 'South America'], answer: 1, explanation: 'The Nile River flows through northeastern Africa, including Egypt and Sudan, before emptying into the Mediterranean Sea.' },
  { id: 'extra-002', category: 'Lakes', question: "Lake Baikal is the world's deepest freshwater lake and contains about one-fifth of the world's unfrozen surface freshwater. It is also one of the world's oldest lakes. In which country is Lake Baikal located?", options: ['Mongolia', 'Kazakhstan', 'Russia', 'China'], answer: 2, explanation: 'Lake Baikal is located in southern Siberia, Russia.' },
  { id: 'extra-003', category: 'Rivers', question: 'The Amazon River carries more water than any other river in the world and drains a vast basin covered largely by tropical rainforest. Into which ocean does the Amazon River empty?', options: ['Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'], answer: 1, explanation: 'The Amazon River empties into the Atlantic Ocean on the northeastern coast of Brazil.' },
  { id: 'extra-004', category: 'Mountains & Peaks', question: "Mount Kilimanjaro is Africa's highest mountain and is famous for its three volcanic cones—Kibo, Mawenzi and Shira. In which country is Mount Kilimanjaro located?", options: ['Kenya', 'Uganda', 'Tanzania', 'Ethiopia'], answer: 2, explanation: 'Mount Kilimanjaro is located in Tanzania, near the border with Kenya.' },
  { id: 'extra-005', category: 'Oceans & Seas', question: "The Great Barrier Reef is the world's largest coral reef system and consists of thousands of individual reefs and islands. It lies off the northeastern coast of which country?", options: ['Indonesia', 'Australia', 'Papua New Guinea', 'New Zealand'], answer: 1, explanation: 'The Great Barrier Reef lies off the northeastern coast of Australia, in the Coral Sea.' },
  { id: 'extra-006', category: 'Rivers', question: "The Danube is one of Europe's most important international rivers and flows through or along the borders of several countries before forming a large delta. Into which sea does the Danube River ultimately drain?", options: ['Baltic Sea', 'Adriatic Sea', 'Black Sea', 'Caspian Sea'], answer: 2, explanation: 'The Danube River drains into the Black Sea, forming a large delta in Romania.' },
  { id: 'extra-007', category: 'Deserts', question: 'The Atacama Desert is regarded as one of the driest non-polar regions on Earth. It stretches along the Pacific coast of South America and is particularly associated with which country?', options: ['Peru', 'Chile', 'Bolivia', 'Argentina'], answer: 1, explanation: 'The Atacama Desert stretches along the Pacific coast of Chile.' },
  { id: 'extra-008', category: 'Deserts', question: 'The Gobi Desert is a vast cold desert of Asia, known for its extreme temperatures and important fossil discoveries. It extends across southern Mongolia and the northern part of which country?', options: ['Kazakhstan', 'Russia', 'China', 'Uzbekistan'], answer: 2, explanation: 'The Gobi Desert extends across southern Mongolia and northern China.' },
  { id: 'extra-009', category: 'Straits & Gulfs', question: 'The Strait of Gibraltar is a strategically important narrow waterway separating Europe from Africa. It connects the Atlantic Ocean with which sea?', options: ['Red Sea', 'Mediterranean Sea', 'Black Sea', 'Adriatic Sea'], answer: 1, explanation: 'The Strait of Gibraltar connects the Atlantic Ocean with the Mediterranean Sea.' },
  { id: 'extra-010', category: 'Waterfalls', question: 'Victoria Falls is one of the world\'s most famous waterfalls and is formed by the Zambezi River. The falls lie on the international border between Zambia and which other African country?', options: ['Botswana', 'Namibia', 'Zimbabwe', 'Malawi'], answer: 2, explanation: "Victoria Falls → Zambezi River → Zambia + Zimbabwe → “Smoke That Thunders”"},
{ id: 'extra-011', category: 'All Straits', question: 'Gibraltar → Atlantic Ocean + Mediterranean Sea Hormuz → Persian Gulf + Gulf of Oman\n Bab-el-Mandeb → Red Sea + Gulf of Aden\n \n Malacca → Andaman Sea + South China Sea\n Bering → Bering Sea + Chukchi Sea\n Bosporus → Black Sea + Sea of Marmara\n Dardanelles → Sea of Marmara + Aegean Sea\n \n Dover → English Channel + North Sea\n Palk → Bay of Bengal + Gulf of Mannar\n Sunda → Java Sea + Indian Ocean\n Lombok → Bali Sea + Indian Ocean\n Makassar → Celebes Sea + Java Sea\n \n Taiwan (Formosa) → East China Sea + South China Sea\n Korea (Tsushima) → East China Sea + Sea of Japan\n Tsugaru → Sea of Japan + Pacific Ocean\n La Pérouse (Soya) → Sea of Japan + Sea of Okhotsk\n \n Torres → Arafura Sea + Coral Sea\n Bass → Indian Ocean region + Tasman Sea\n Cook → Tasman Sea + South Pacific Ocean\n \n Florida → Gulf of Mexico + Atlantic Ocean\n Yucatán → Caribbean Sea + Gulf of Mexico\n Davis → Baffin Bay + Labrador Sea\n Hudson → Hudson Bay + Labrador Sea\n \n Denmark → Greenland Sea + North Atlantic Ocean\n Fram → Arctic Ocean + Greenland Sea\n Vilkitsky → Kara Sea + Laptev Sea\n \n Messina → Tyrrhenian Sea + Ionian Sea\n Otranto → Adriatic Sea + Ionian Sea\n Bonifacio → Mediterranean Sea (between Corsica + Sardinia)\n \n Tiran → Gulf of Aqaba + Red Sea\n Kerch → Black Sea + Sea of Azov', options: ['Botswana', 'Namibia', 'Zimbabwe', 'Malawi'], answer: 2, explanation: 'Victoria Falls lies on the border between Zambia and Zimbabwe.' },


 {"id": "static-dams-001", "category": "Dams", "question": "Which of the following statements about dams is/are correct?\n1. A dam always refers to a concrete or structural wall built to block water.\n2. Spillways help in safely releasing excess water from the reservoir.\n3. Dams can be classified based on structure, purpose and height.", "options": ["Both 1 and 2", "Both 2 and 3", "Both 1 and 3", "All 1, 2 and 3"], "answer": 1, "explanation": "Statement 1 is wrong (dams can be concrete, masonry, earth or rock-fill). 2 and 3 are correct.", "subQuestions": [{"question": "What is the water stored behind a dam called?", "options": ["Canal", "Reservoir", "Barrage", "Aqueduct"], "answer": 1, "explanation": "Reservoir."}, {"question": "What is the main function of a spillway?", "options": ["To store water", "To safely release excess water", "To generate electricity", "To divert water"], "answer": 1, "explanation": "To safely release excess water."}]},
  {"id": "static-dams-002", "category": "Dams", "question": "Dams are classified on the basis of construction material/design. Which types are correct?", "options": ["Gravity, Arch, Earth, Rock-fill", "Only Concrete and Earth", "Only Storage and Diversion", "Only High and Low"], "answer": 0, "explanation": "Gravity, Arch, Earth, Rock-fill and Composite dam.", "subQuestions": [{"question": "What type of dam is Nagarjuna Sagar Dam?", "options": ["Earth Dam", "Rock-fill Dam", "Concrete/Masonry Dam", "Arch Dam"], "answer": 2, "explanation": "An example of a Concrete/Masonry Dam."}, {"question": "What material is an Earth Dam mainly made of?", "options": ["Concrete", "Compacted earth/soil", "Rock only", "Steel"], "answer": 1, "explanation": "Compacted earth or soil."}]},
  {"id": "static-dams-003", "category": "Dams", "question": "When was the Dam Safety Act enacted?", "options": ["2016", "2018", "2021", "2023"], "answer": 2, "explanation": "Dam Safety Act, 2021 – for surveillance, inspection, operation & maintenance.", "subQuestions": [{"question": "What is the full form of DRIP?", "options": ["Dam River Improvement Project", "Dam Rehabilitation and Improvement Project", "Dam Reconstruction Project", "Dam Research Project"], "answer": 1, "explanation": "Dam Rehabilitation and Improvement Project."}, {"question": "How many dams were identified under DRIP Phase II & III?", "options": ["436", "536", "636", "736"], "answer": 3, "explanation": "736 dams, 19 States + 3 Central Agencies, cost ₹10,211 crore (2021-2031)."}]},
  {"id": "static-dams-004", "category": "Dams", "question": "Bhakra Dam is on which river?", "options": ["Beas", "Sutlej", "Ravi", "Chenab"], "answer": 1, "explanation": "225.55 m high Concrete Gravity Dam on Sutlej (Bilaspur, HP). Forms Gobind Sagar. Part of Bhakra-Nangal Project.", "subQuestions": [{"question": "Gobind Sagar is associated with which dam?", "options": ["Pong", "Bhakra", "Pandoh", "Chamera"], "answer": 1, "explanation": "Bhakra Dam."}, {"question": "Pandoh Dam is on which river and what is its nature?", "options": ["Sutlej – Storage", "Beas – Diversion", "Ravi – Hydropower only", "Chenab – Gravity"], "answer": 1, "explanation": "Beas river, Earth-cum-Rockfill diversion dam (Beas-Sutlej Link)."}]},
  {"id": "static-dams-005", "category": "Dams", "question": "Pong Dam (Beas Dam) is on which river?", "options": ["Sutlej", "Beas", "Ravi", "Chenab"], "answer": 1, "explanation": "Earth Core Gravel Shell dam on Beas (Kangra, HP). Forms Maharana Pratap Sagar.", "subQuestions": [{"question": "Maharana Pratap Sagar is related to which dam?", "options": ["Bhakra", "Pong", "Tehri", "Chamera"], "answer": 1, "explanation": "Pong Dam."}, {"question": "Chamera-I dam is on which river?", "options": ["Sutlej", "Beas", "Ravi", "Chenab"], "answer": 2, "explanation": "Ravi river, Chamba (HP). Capacity 540 MW."}]},
  {"id": "static-dams-006", "category": "Dams", "question": "Tehri Dam is on which river and what is its height?", "options": ["Alaknanda – 260.5 m", "Bhagirathi – 260.5 m", "Yamuna – 225 m", "Ramganga – 200 m"], "answer": 1, "explanation": "Earth & Rockfill Dam on Bhagirathi (Tehri Garhwal, Uttarakhand). 260.5 m – India’s one of the highest dams.", "subQuestions": [{"question": "Koteshwar HEP (400 MW) is on which river?", "options": ["Alaknanda", "Bhagirathi", "Yamuna", "Tons"], "answer": 1, "explanation": "Bhagirathi river."}, {"question": "Where do the Bhagirathi and Alaknanda meet to form the Ganga?", "options": ["Rudraprayag", "Karnaprayag", "Devprayag", "Nandprayag"], "answer": 2, "explanation": "Devprayag (Panch Prayag)."}]},
  {"id": "static-dams-007", "category": "Dams", "question": "Sardar Sarovar Dam is on which river?", "options": ["Tapi", "Narmada", "Sabarmati", "Mahi"], "answer": 1, "explanation": "Narmada river, Gujarat. Important multipurpose project.", "subQuestions": [{"question": "Ukai Dam is on which river?", "options": ["Narmada", "Tapi (Tapti)", "Sabarmati", "Mahi"], "answer": 1, "explanation": "Tapi river, Gujarat."}, {"question": "Indira Sagar Dam is in which state and on which river?", "options": ["Gujarat – Narmada", "Madhya Pradesh – Narmada", "Maharashtra – Godavari", "Rajasthan – Chambal"], "answer": 1, "explanation": "Madhya Pradesh, Narmada river."}]},
  {"id": "static-dams-008", "category": "Dams", "question": "Hirakud Dam is on which river?", "options": ["Godavari", "Mahanadi", "Brahmani", "Subarnarekha"], "answer": 1, "explanation": "Mahanadi river, Odisha. Asia’s one of the longest dams.", "subQuestions": [{"question": "Gandhi Sagar Dam is on which river?", "options": ["Narmada", "Chambal", "Betwa", "Sone"], "answer": 1, "explanation": "Chambal river, Madhya Pradesh."}, {"question": "Bansagar Dam is on which river?", "options": ["Narmada", "Sone", "Betwa", "Wainganga"], "answer": 1, "explanation": "Sone river (Ganga tributary)."}]},
  {"id": "static-dams-009", "category": "Dams", "question": "Koyna Dam is in which state?", "options": ["Karnataka", "Maharashtra", "Gujarat", "Madhya Pradesh"], "answer": 1, "explanation": "Maharashtra, Koyna river (Krishna tributary). Famous for hydropower.", "subQuestions": [{"question": "Almatti Dam is on which river?", "options": ["Cauvery", "Krishna", "Tungabhadra", "Godavari"], "answer": 1, "explanation": "Krishna river, Karnataka."}, {"question": "Tungabhadra Dam is in which state?", "options": ["Andhra Pradesh", "Karnataka", "Telangana", "Tamil Nadu"], "answer": 1, "explanation": "Karnataka (Tungabhadra river)."}]},
  {"id": "static-dams-010", "category": "Dams", "question": "Nagarjuna Sagar Dam is on which river?", "options": ["Godavari", "Krishna", "Pennar", "Tungabhadra"], "answer": 1, "explanation": "Krishna river (Telangana-Andhra Pradesh border). World’s largest masonry dam.", "subQuestions": [{"question": "Srisailam Dam is on which river?", "options": ["Godavari", "Krishna", "Pennar", "Musi"], "answer": 1, "explanation": "Krishna river (Telangana-Andhra)."}, {"question": "Polavaram Project is on which river?", "options": ["Krishna", "Godavari", "Pennar", "Vamsadhara"], "answer": 1, "explanation": "Godavari river, Andhra Pradesh."}]},
  {"id": "static-dams-011", "category": "Dams", "question": "Idukki Dam is in which state?", "options": ["Tamil Nadu", "Kerala", "Karnataka", "Andhra Pradesh"], "answer": 1, "explanation": "Kerala, Periyar river. Asia’s one of the highest arch dams.", "subQuestions": [{"question": "Mettur Dam (Stanley Reservoir) is on which river?", "options": ["Vaigai", "Cauvery", "Bhavani", "Thamirabarani"], "answer": 1, "explanation": "Cauvery river, Tamil Nadu."}, {"question": "Krishnaraja Sagar (KRS) Dam is on which river?", "options": ["Krishna", "Cauvery", "Tungabhadra", "Hemavathi"], "answer": 1, "explanation": "Cauvery river, Karnataka."}]},
  {"id": "static-dams-012", "category": "Dams", "question": "Pakal Dul Hydroelectric Project (1000 MW) is on which river?", "options": ["Jhelum", "Marusudar (Chenab tributary)", "Tawi", "Kishanganga"], "answer": 1, "explanation": "Marusudar river, Kishtwar, J&K.", "subQuestions": [{"question": "Salal Power Project is on which river?", "options": ["Jhelum", "Chenab", "Ravi", "Beas"], "answer": 1, "explanation": "Chenab river, Reasi, J&K (690 MW)."}, {"question": "Rihand Dam (Govind Ballabh Pant Sagar) is in which state?", "options": ["Bihar", "Uttar Pradesh", "Jharkhand", "Madhya Pradesh"], "answer": 1, "explanation": "Uttar Pradesh, Rihand river."}]},
  {"id": "static-dams-013", "category": "Dams", "question": "Rana Pratap Sagar Dam is on which river?", "options": ["Banas", "Chambal", "Mahi", "Luni"], "answer": 1, "explanation": "Chambal river, Rajasthan.", "subQuestions": [{"question": "Bisalpur Dam is on which river?", "options": ["Chambal", "Banas", "Mahi", "Luni"], "answer": 1, "explanation": "Banas river, Rajasthan."}, {"question": "Ranjit Sagar Dam (Thein Dam) is on which river?", "options": ["Sutlej", "Beas", "Ravi", "Chenab"], "answer": 2, "explanation": "Ravi river (Punjab)."}]},
  {"id": "static-dams-014", "category": "Dams", "question": "Farakka Barrage is on which river?", "options": ["Damodar", "Ganga", "Teesta", "Mahananda"], "answer": 1, "explanation": "Ganga river, West Bengal. Important for navigation & water sharing.", "subQuestions": [{"question": "Maithon Dam is on which river?", "options": ["Damodar", "Barakar (Damodar tributary)", "Subarnarekha", "Mayurakshi"], "answer": 1, "explanation": "Barakar river (Jharkhand) – Damodar Valley system."}, {"question": "Subansiri Lower HEP (2000 MW) is proposed/under construction in which state?", "options": ["Assam", "Arunachal Pradesh", "Sikkim", "Meghalaya"], "answer": 1, "explanation": "Arunachal Pradesh, Subansiri river."}]},
  {"id": "static-dams-015", "category": "Dams", "question": "According to the 2026 official update, rehabilitation proposals for how many dams were approved under DRIP-II?", "options": ["91", "143", "191", "236"], "answer": 2, "explanation": "191 dams, approx ₹5,053 crore. Major physical works completed on 43 dams.", "subQuestions": [{"question": "What is the function of the National Dam Safety Authority (NDSA)?", "options": ["To construct new dams", "To coordinate & oversee dam safety at the national level", "Only irrigation projects", "Only hydropower"], "answer": 1, "explanation": "National coordination under the dam safety framework."}, {"question": "What does the Central Water Commission (CWC) maintain?", "options": ["National Register of Large Dams", "National Register of Rivers", "National Register of Canals", "National Register of Barrages"], "answer": 0, "explanation": "National Register of Large Dams in India."}]}
,
  {"id": "static-dams-016", "category": "Dams", "question": "Which of the following statements about dams is/are correct?\n1. A dam always refers to a concrete or structural wall built to block water.\n2. Spillways in dams help in regulating water flow, either intermittently or continuously.\n3. Dams can be classified based on structure, purpose, and height.", "options": ["Both 1 and 2", "Both 2 and 3", "Both 1 and 3", "1, 2 and 3 all are correct"], "answer": 1, "explanation": "Statement 1 is incorrect because dams can be made of concrete, masonry, earth or rock-fill, not only concrete walls. Statements 2 and 3 are correct. (SSC CGL 2025 Tier-01 pattern)", "subQuestions": [{"question": "What is the main function of a Spillway?", "options": ["To store water permanently", "To safely release excess water from reservoir", "To generate electricity only", "To divert water permanently"], "answer": 1, "explanation": "Spillway safely releases excess water from the reservoir to prevent overtopping."}, {"question": "What is the water stored behind a dam called?", "options": ["Canal", "Reservoir", "Barrage", "Aqueduct"], "answer": 1, "explanation": "Water stored behind a dam is called a Reservoir."}]},
  {"id": "static-dams-017", "category": "Dams", "question": "Dams can be classified on the basis of construction material/design into which of the following?", "options": ["Gravity, Arch, Earth, Rock-fill", "Only Concrete and Earth", "Only Storage and Diversion", "Only High and Low"], "answer": 0, "explanation": "Based on Structure/Material: Gravity Dam, Arch Dam, Earth Dam, Rock-fill Dam. Composite Dam is also mentioned.", "subQuestions": [{"question": "Nagarjuna Sagar Dam is an example of which type of dam?", "options": ["Earth Dam", "Rock-fill Dam", "Concrete/Masonry Dam", "Arch Dam"], "answer": 2, "explanation": "Nagarjuna Sagar is a Concrete/Masonry Dam."}, {"question": "Which type of dam is constructed mainly using compacted earth or soil?", "options": ["Gravity Dam", "Earth Dam", "Arch Dam", "Rock-fill Dam"], "answer": 1, "explanation": "Earth Dam is made mainly of compacted earth/soil."}]},
  {"id": "static-dams-018", "category": "Dams", "question": "Which of the following is NOT a purpose for which dams are constructed?", "options": ["Irrigation", "Hydroelectric power", "Flood control", "Desertification"], "answer": 3, "explanation": "Dams are built for Irrigation, Hydroelectric power, Flood control, Water supply, Drought management, Fishery, Recreation & Tourism, Industrial water supply.", "subQuestions": [{"question": "In hydroelectric power generation, water stored in reservoir has which type of energy?", "options": ["Kinetic Energy", "Potential Energy", "Thermal Energy", "Chemical Energy"], "answer": 1, "explanation": "Water stored at height has Potential Energy. When released it rotates the turbine."}, {"question": "How does a dam help in flood control?", "options": ["By increasing river flow suddenly", "By temporarily storing excess water and reducing peak flood flow downstream", "By completely stopping the river", "By diverting all water permanently"], "answer": 1, "explanation": "Reservoir temporarily stores excess water during heavy rainfall, reducing peak flood downstream."}]},
  {"id": "static-dams-019", "category": "Dams", "question": "Dam Safety Act was enacted in which year?", "options": ["2016", "2018", "2021", "2023"], "answer": 2, "explanation": "Dam Safety Act, 2021 provides framework for surveillance, inspection, operation and maintenance of specified dams.", "subQuestions": [{"question": "What is the full form of DRIP?", "options": ["Dam River Improvement Project", "Dam Rehabilitation and Improvement Project", "Dam Reconstruction and Irrigation Project", "Dam Research and Infrastructure Project"], "answer": 1, "explanation": "DRIP – Dam Rehabilitation and Improvement Project."}, {"question": "Under DRIP Phase II & III, how many dams have been identified for rehabilitation?", "options": ["436", "536", "636", "736"], "answer": 3, "explanation": "736 dams identified under DRIP Phase II & III covering 19 States and 3 Central Agencies. Cost ₹10,211 crore (2021–2031)."}]},
  {"id": "static-dams-020", "category": "Dams", "question": "Bhakra Dam is constructed on which river?", "options": ["Beas", "Sutlej", "Ravi", "Chenab"], "answer": 1, "explanation": "Bhakra is a 225.55 m high Concrete Straight Gravity Dam on Sutlej in Bilaspur, Himachal Pradesh. It forms Gobind Sagar Reservoir and is part of Bhakra-Nangal Multipurpose Project.", "subQuestions": [{"question": "Gobind Sagar Reservoir is associated with which dam?", "options": ["Pong Dam", "Bhakra Dam", "Pandoh Dam", "Chamera Dam"], "answer": 1, "explanation": "Gobind Sagar is formed by Bhakra Dam."}, {"question": "Which dam is primarily a diversion dam on Beas River?", "options": ["Bhakra", "Pong", "Pandoh", "Chamera-I"], "answer": 2, "explanation": "Pandoh is Earth-cum-Rockfill diversion dam on Beas in Mandi (HP). Associated with Beas-Sutlej Link."}]},
  {"id": "static-dams-021", "category": "Dams", "question": "Pong Dam is also known as:", "options": ["Beas Dam", "Ravi Dam", "Sutlej Dam", "Kangra Dam"], "answer": 0, "explanation": "Pong Dam (also called Beas Dam) is Earth Core Gravel Shell dam on Beas in Kangra, HP. Forms Maharana Pratap Sagar Reservoir.", "subQuestions": [{"question": "Maharana Pratap Sagar is associated with:", "options": ["Bhakra Dam", "Pong Dam", "Tehri Dam", "Chamera Dam"], "answer": 1, "explanation": "Maharana Pratap Sagar is the reservoir of Pong Dam."}, {"question": "Chamera-I dam is located on which river?", "options": ["Sutlej", "Beas", "Ravi", "Chenab"], "answer": 2, "explanation": "Chamera-I (540 MW) is Concrete Gravity hydropower dam on Ravi in Chamba, HP. Chamera-II (300 MW), Chamera-III (231 MW)."}]},
  {"id": "static-dams-022", "category": "Dams", "question": "Tehri Dam is constructed on which river?", "options": ["Alaknanda", "Bhagirathi", "Yamuna", "Ramganga"], "answer": 1, "explanation": "Tehri is Earth and Rockfill Dam on Bhagirathi in Tehri Garhwal, Uttarakhand. Height 260.5 m – one of the highest dams in India. Forms Tehri Reservoir.", "subQuestions": [{"question": "Koteshwar HEP (400 MW) is associated with which river?", "options": ["Alaknanda", "Bhagirathi", "Yamuna", "Ramganga"], "answer": 1, "explanation": "Koteshwar is on Bhagirathi River, Uttarakhand."}, {"question": "Alaknanda and Bhagirathi meet at which place to form Ganga?", "options": ["Rudraprayag", "Karnaprayag", "Devprayag", "Nandprayag"], "answer": 2, "explanation": "Devprayag – confluence of Bhagirathi + Alaknanda → Ganga. Part of Panch Prayag."}]},
  {"id": "static-dams-023", "category": "Dams", "question": "Which of the following is correctly matched?", "options": ["Tehri Dam – Yamuna", "Pong Dam – Ravi", "Bhakra Dam – Sutlej", "Chamera – Beas"], "answer": 2, "explanation": "Bhakra – Sutlej is correct. Tehri is on Bhagirathi, Pong on Beas, Chamera on Ravi.", "subQuestions": [{"question": "Jamrani Dam Project is proposed across which river?", "options": ["Ganga", "Gola", "Tons", "Alaknanda"], "answer": 1, "explanation": "Jamrani Dam is on Gola River (tributary of Ramganga) for irrigation + drinking water + 14 MW."}, {"question": "Kishau Multipurpose Project is associated with which tributary of Yamuna?", "options": ["Mandakini", "Tons", "Pindar", "Dhauliganga"], "answer": 1, "explanation": "Kishau is on Tons (tributary of Yamuna)."}]},
  {"id": "static-dams-024", "category": "Dams", "question": "Pakal Dul Hydroelectric Project (1000 MW) is associated with which river?", "options": ["Jhelum", "Marusudar", "Tawi", "Kishanganga"], "answer": 1, "explanation": "Pakal Dul is on Marusudar River (tributary of Chenab) in Kishtwar, J&K.", "subQuestions": [{"question": "Salal Power Project is located on which river?", "options": ["Jhelum", "Chenab", "Ravi", "Beas"], "answer": 1, "explanation": "Salal (690 MW) is on Chenab in Reasi district, J&K."}, {"question": "Which of the following has the highest capacity among Chenab projects listed?", "options": ["Pakal Dul (1000 MW)", "Sawalkote (1856 MW)", "Kirthai-II (930 MW)", "Ratle (850 MW)"], "answer": 1, "explanation": "Sawalkote – 1856 MW is the highest among the listed Chenab projects."}]},
  {"id": "static-dams-025", "category": "Dams", "question": "According to 2026 update on DRIP-II, how many dams had rehabilitation proposals approved?", "options": ["91", "143", "191", "236"], "answer": 2, "explanation": "In 2026, rehabilitation proposals for 191 dams under DRIP-II (approx ₹5,053 crore) were approved. Major works completed on 43 dams.", "subQuestions": [{"question": "National Dam Safety Authority (NDSA) is responsible for:", "options": ["Only construction of new dams", "Coordinating and overseeing dam safety at national level", "Only irrigation projects", "Only hydropower generation"], "answer": 1, "explanation": "NDSA coordinates and oversees dam safety matters at the national level under Dam Safety Act framework."}, {"question": "Central Water Commission (CWC) maintains which important register?", "options": ["National Register of Large Dams", "National Register of Rivers", "National Register of Canals", "National Register of Barrages"], "answer": 0, "explanation": "CWC maintains the National Register of Large Dams in India."}]},
  {"id": "static-dams-026", "category": "Dams", "question": "Which of the following statements is correct regarding classification of dams based on purpose?", "options": ["Storage Dam – mainly stores water for later use", "Diversion Dam – mainly for flood control only", "Detention Structure – mainly for permanent storage", "All dams are only for hydropower"], "answer": 0, "explanation": "Storage Dam stores water for later use. Diversion Dam diverts water to canal. Detention/Flood-Control Structure temporarily stores/regulates flood flows.", "subQuestions": [{"question": "Which of the following is an example of multipurpose river valley project benefits?", "options": ["Only irrigation", "Irrigation + Power + Flood control + Water supply + Fishery + Tourism", "Only power generation", "Only flood control"], "answer": 1, "explanation": "Multipurpose projects provide irrigation, hydroelectric power, flood control, industrial & domestic water supply, fishery, recreation & tourism, drought management."}, {"question": "A dam does not mean only a concrete wall. Which materials can dams be made of?", "options": ["Only Concrete", "Concrete, Masonry, Earth, Rock-fill", "Only Earth and Rock", "Only Masonry"], "answer": 1, "explanation": "Dams can be made of Concrete, Masonry, Earth or Rock-fill materials."}]},
  {"id": "static-dams-027", "category": "Dams", "question": "Which dam is correctly matched with its state and river?", "options": ["Tehri – Himachal Pradesh – Sutlej", "Bhakra – Uttarakhand – Bhagirathi", "Pong – Himachal Pradesh – Beas", "Chamera – Uttarakhand – Alaknanda"], "answer": 2, "explanation": "Pong Dam is in Kangra, Himachal Pradesh on Beas River. Tehri is in Uttarakhand on Bhagirathi, Bhakra in HP on Sutlej, Chamera in HP on Ravi.", "subQuestions": [{"question": "Koldam is an earthen hydropower dam on which river?", "options": ["Beas", "Sutlej", "Ravi", "Chenab"], "answer": 1, "explanation": "Koldam is earthen hydropower dam on Sutlej in Mandi, Himachal Pradesh."}, {"question": "Luhri Stage-I is an under-construction project on:", "options": ["Beas", "Sutlej", "Ravi", "Chenab"], "answer": 1, "explanation": "Luhri Stage-I is under-construction hydropower project on Sutlej in Shimla region, HP."}]}
];
