// Indian Polity Question Bank - Part 1
// Topics: Preamble, Fundamental Duties, Articles 19/20/51, Bill Types, Motions,
// President & related Articles, Part VI Governor (152-161,170,175,200,201,213),
// Supreme Court (124-131,137,140-144), 139A, 42nd Amendment, National/State Emergency,
// Article 309-312, 324-329, 263, 239AA, Panchayat & Municipalities, 73rd Amendment,
// Parliamentary Committees, Grants-in-Aid (275), J&K (35A, 370),
// Amendments (4th, 52nd, 61st, 73rd, 86th, 99th, 100th, 102nd)

const staticPolityQuestions = [

  // ===================== PREAMBLE =====================
  { id: 'polity-preamble-001', category: 'Polity - Preamble', question: 'Which word was added to the Preamble of the Indian Constitution by the 42nd Amendment Act, 1976?', options: ['Sovereign', 'Socialist', 'Republic', 'Democratic'], answer: 1, explanation: 'The 42nd Amendment Act, 1976 added the words "Socialist", "Secular" and "Integrity" to the Preamble.' },
  { id: 'polity-preamble-002', category: 'Polity - Preamble', question: 'The Preamble of the Indian Constitution was amended how many times so far?', options: ['Never amended', 'Once', 'Twice', 'Thrice'], answer: 1, explanation: 'The Preamble has been amended only once, by the 42nd Constitutional Amendment Act, 1976.' },
  { id: 'polity-preamble-003', category: 'Polity - Preamble', question: 'Consider the following statements about the Preamble:\n1. The Preamble is enforceable in a court of law.\n2. The Preamble is not a part of the Constitution as held originally in Berubari Union case, but the Kesavananda Bharati case held it to be a part of the Constitution.\nWhich of the statements given above is/are correct?', options: ['1 only', '2 only', 'Both 1 and 2', 'Neither 1 nor 2'], answer: 1, explanation: "The Preamble is not directly enforceable, but the Kesavananda Bharati case (1973) held that the Preamble is part of the Constitution.\nAnwar Ali Sarkar (1952) → Article 14\nKesavananda Bharati (1973) → Basic Structure + Preamble part of Constitution\nBerubari Union (1960) → Preamble initially not considered part of Constitution."},
  { id: 'polity-preamble-004', category: 'Polity - Preamble', question: 'Which of the following ideals is NOT mentioned in the Preamble of the Indian Constitution?', options: ['Liberty', 'Equality', 'Fraternity', 'Federalism'], answer: 3, explanation: 'The Preamble mentions Justice, Liberty, Equality and Fraternity; "Federalism" is not explicitly mentioned.' },
  { id: 'polity-preamble-005', category: 'Polity - Preamble', question: 'The source of authority of the Indian Constitution, as stated in the Preamble, lies with:', options: ['The Parliament of India', 'The President of India', 'The People of India', 'The Supreme Court of India'], answer: 2, explanation: "“Indian Constitution ko power/authority kis se milti hai?”\nPreamble ki opening line hai:\n“We, the People of India…”"},

  // ===================== FUNDAMENTAL DUTIES =====================
  { id: 'polity-fd-001', category: 'Polity - Fundamental Duties', question: 'Fundamental Duties were added to the Indian Constitution by which amendment, based on the recommendations of which committee?', options: ['42nd Amendment; Swaran Singh Committee', '44th Amendment; Sarkaria Commission', '86th Amendment; Verma Committee', '52nd Amendment; Dinesh Goswami Committee'], answer: 0, explanation: "FD-> 42amd swaran committee\nDPSP -> sapru committee "},
  { id: 'polity-fd-002', category: 'Polity - Fundamental Duties', question: 'How many Fundamental Duties are currently listed under Article 51A of the Constitution?', options: ['10', '11', '12', '14'], answer: 1, explanation: 'Originally 10 duties were added in 1976; the 86th Amendment Act, 2002 added an 11th duty relating to education of children.' },
  { id: 'polity-fd-003', category: 'Polity - Fundamental Duties', question: 'The 11th Fundamental Duty, added by the 86th Constitutional Amendment Act, 2002, relates to:', options: ['Protecting the environment', 'Providing opportunities for education to a child/ward between 6-14 years', 'Safeguarding public property', 'Developing scientific temper'], answer: 1, explanation: 'The 86th Amendment added a duty on parents/guardians to provide opportunities for education to their child or ward between the ages of 6 and 14 years.' },
  { id: 'polity-fd-004', category: 'Polity - Fundamental Duties', question: 'Consider the following statements regarding Fundamental Duties:\n1. Fundamental Duties are enforceable by courts like Fundamental Rights.\n2. Fundamental Duties are confined only to citizens of India and do not apply to foreigners.\nWhich of the statements given above is/are correct?', options: ['1 only', '2 only', 'Both 1 and 2', 'Neither 1 nor 2'], answer: 1, explanation: 'Fundamental Duties are not directly enforceable by courts (non-justiciable), but they apply only to citizens, unlike Fundamental Rights which extend to foreigners too (with exceptions).' },
  { id: 'polity-fd-005', category: 'Polity - Fundamental Duties', question: 'Which article of the Indian Constitution deals with Fundamental Duties?', options: ['Article 48A', 'Article 51A', 'Article 21A', 'Article 39A'], answer: 1, explanation: "Constitution, National Flag aur National Anthem ka respect karna.\nFreedom Struggle ke ideals ko follow karna.\nIndia ki sovereignty, unity aur integrity ko protect karna.\nCountry ko defend karna aur national service dena jab required ho.\nBrotherhood aur harmony promote karna; women ki dignity ke against practices ko reject karna.\nIndia ki composite culture ko preserve karna.\nEnvironment — forests, lakes, rivers, wildlife ko protect karna aur living creatures ke liye compassion rakhna.\nScientific temper, humanism aur spirit of inquiry/reform develop karna.\nPublic property protect karna aur violence avoid karna.\nHar field mein excellence ki taraf strive karna.\n6–14 years ke children ko education ka opportunity dena — ye duty parents/guardians ki hai.", notes: ["42nd Amendment → 10 Duties\n86th Amendment → 11th Duty (Education)"],},
  { id: 'polity-fd-006', category: 'Polity - Fundamental Duties', question: 'Which of the following is a Fundamental Duty under Article 51A?', options: ['To vote in elections', 'To pay taxes honestly', 'To protect and improve the natural environment', 'To join the armed forces'], answer: 2, explanation: "(a) Constitution, National Flag & National Anthem ka respect karna.\n\n(b) Freedom struggle ke noble ideals ko cherish/follow karna.\n\n(c) India ki sovereignty, unity & integrity ko uphold/protect karna.\n\n(d) Country ko defend karna & national service dena when called upon.\n\n(e) Harmony & brotherhood promote karna; women ki dignity ke against practices ko renounce karna.\n\n(f) India's composite culture ki rich heritage preserve karna.\n\n(g) Natural environment protect/improve karna; forests, lakes, rivers, wildlife; living creatures ke liye compassion.\n\n(h) Scientific temper, humanism & spirit of inquiry/reform develop karna.\n\n(i) Public property safeguard karna & violence ko abjure karna.\n\n(j) Individual & collective activities mein excellence ki taraf strive karna.\n\n(k) Parent/guardian → 6–14 years ke child/ward ko education opportunities provide karna."},

  // ===================== ARTICLE 19, 20, 21 =====================
  { id: 'polity-art19-001', category: 'Polity - Fundamental Rights (Art 19,20)', question: 'Article 19(1) of the Indian Constitution guarantees how many freedoms to citizens?', options: ['Five', 'Six', 'Seven', 'Eight'], answer: 1, explanation: 'Article 19(1) originally guaranteed seven freedoms; after deletion of the right to property, six freedoms remain (speech, assembly, association, movement, residence, profession).' },
  { id: 'polity-art19-002', category: 'Polity - Fundamental Rights (Art 19,20)', question: 'Under Article 19(2), reasonable restrictions can be imposed on freedom of speech and expression on which of the following grounds?', options: ['Sovereignty and integrity of India', 'Personal enmity', 'Political rivalry', 'Business competition'], answer: 0, explanation: 'Article 19(2) allows reasonable restrictions on grounds such as sovereignty and integrity of India, security of the State, public order, decency, morality, contempt of court, defamation, and incitement to an offence.' },
  { id: 'polity-art19-003', category: 'Polity - Fundamental Rights (Art 19,20)', question: 'Consider the following statements regarding Article 20 of the Constitution:\n1. It provides protection against ex-post-facto laws.\n2. It provides protection against double jeopardy.\n3. It provides protection against self-incrimination.\nWhich of the statements given above is/are correct?', options: ['1 only', '1 and 2 only', '2 and 3 only', '1, 2 and 3'], answer: 3, explanation: 'Article 20 provides three protections: (1) no ex-post-facto conviction/punishment, (2) no double jeopardy, and (3) no compulsion to be a witness against oneself.' },
  { id: 'polity-art19-004', category: 'Polity - Fundamental Rights (Art 19,20)', question: 'The protection against double jeopardy under Article 20(2) means that no person shall be:', options: ['Prosecuted and punished for the same offence more than once', 'Punished with more than one type of punishment', 'Tried without a lawyer', 'Denied bail more than once'], answer: 0, explanation: 'Article 20(2) states that no person shall be prosecuted and punished for the same offence more than once.' },
  { id: 'polity-art19-005', category: 'Polity - Fundamental Rights (Art 19,20)', question: 'Unlike other Fundamental Rights, the protections under Article 20 and Article 21 continue to remain in force:', options: ['Only during a National Emergency', 'Even during a National Emergency', 'Only when Parliament permits', 'Only for citizens, not foreigners'], answer: 1, explanation: 'Articles 20 and 21 cannot be suspended even during a National Emergency, as per the 44th Amendment Act, 1978.' },
  { id: 'polity-art19-006', category: 'Polity - Fundamental Rights (Art 19,20)', question: 'Which of the following freedoms under Article 19(1) is available only to citizens and not to foreigners?', options: ['Right to life', 'Right to freedom of speech and expression', 'Right to constitutional remedies', 'Right against exploitation'], answer: 1, explanation: 'Article 19 freedoms, including freedom of speech and expression, are available only to citizens of India, unlike Articles 14, 20, 21, which extend to foreigners as well.' },

  // ===================== BILLS AND MOTIONS =====================
  { id: 'polity-bill-001', category: 'Polity - Bills & Legislative Procedure', question: 'Which of the following bills can be introduced only in the Lok Sabha and not in the Rajya Sabha?', options: ['Ordinary Bill', 'Money Bill', 'Constitutional Amendment Bill', 'Private Member Bill on any subject'], answer: 1, explanation: 'As per Article 110 read with Article 109, a Money Bill can be introduced only in the Lok Sabha, and that too on the recommendation of the President.'  ,notes: ["109 → Procedure → 14 days\n110 → Definition → Speaker"],},
  { id: 'polity-bill-002', category: 'Polity - Bills & Legislative Procedure', question: 'Consider the following statements regarding a Money Bill:\n1. It can be introduced only with prior recommendation of the President.\n2. The Rajya Sabha can reject or amend a Money Bill.\n3. The Rajya Sabha must return a Money Bill within 14 days, with or without recommendations.\nWhich of the statements given above is/are correct?', options: ['1 only', '1 and 3 only', '2 and 3 only', '1, 2 and 3'], answer: 1, explanation: 'A Money Bill needs the President\'s prior recommendation and must be introduced in the Lok Sabha. The Rajya Sabha cannot reject or amend it, only recommend changes, which the Lok Sabha may accept or reject; it must be returned within 14 days.' },
  { id: 'polity-bill-003', category: 'Polity - Bills & Legislative Procedure', question: 'A Financial Bill (Category I) under Article 117 differs from a Money Bill in that:', options: ['It can be introduced in either House', 'It can be introduced only in the Lok Sabha, but may contain other provisions besides those in Article 110', 'It does not require the President\'s recommendation at all', 'It can be introduced by any member without restriction'], answer: 1, explanation: "Feature\tMoney Bill\tFinancial Bill Cat. I\tFinancial Bill Cat. II\nArticle\t110\t117(1)\t117(3)\nIntroduced only in Lok Sabha?\t✅\t✅\t❌\nPresident recommendation\tIntroduction\tIntroduction\tConsideration\nRajya Sabha\tRecommendations only\tFull powers\tFull powers\n14-day rule\t✅\t❌\t❌\nJoint Sitting\t❌\t✅\t✅\nSpeaker certifies as Money Bill\t✅\t❌\t❌", notes: ["Money Bill = 110 only\nFinancial Bill I = 110 + Other matters"],},
  { id: 'polity-bill-004', category: 'Polity - Bills & Legislative Procedure', question: 'Which type of bill can be introduced in either House of Parliament and does not require the President\'s prior recommendation for introduction?', options: ['Money Bill', 'Financial Bill Category I', 'Financial Bill Category II', 'Constitutional Amendment Bill under Article 368'], answer: 2, explanation: 'A Financial Bill Category II (dealing with expenditure from the Consolidated Fund but not containing Article 110 matters) can be introduced in either House without the President\'s prior recommendation, though recommendation is needed before it can be passed.' },
  { id: 'polity-bill-005', category: 'Polity - Bills & Legislative Procedure', question: 'In case of a deadlock between the two Houses of Parliament over an ordinary bill, the resolution mechanism provided is:', options: ['Automatic lapse of the bill', 'A joint sitting under Article 108', 'Reference to the Supreme Court', 'Reference to the President for final decision'], answer: 1, explanation: 'Article 108 provides for a joint sitting of both Houses to resolve a deadlock over an ordinary bill (not applicable to Money Bills).' },
  { id: 'polity-bill-006', category: 'Polity - Bills & Legislative Procedure', question: 'Who decides whether a particular bill is a Money Bill or not?', options: ['The President of India', 'The Speaker of the Lok Sabha', 'The Chairman of the Rajya Sabha', 'The Supreme Court of India'], answer: 1, explanation: 'Under Article 110(3), the Speaker of the Lok Sabha\'s decision on whether a bill is a Money Bill is final.' },
  { id: 'polity-bill-007', category: 'Polity - Motions', question: 'Which motion is moved in the Lok Sabha to test the confidence of the Council of Ministers?', options: ['Adjournment Motion', 'No-Confidence Motion', 'Censure Motion', 'Calling Attention Motion'], answer: 1, explanation: 'A No-Confidence Motion is moved to remove the Council of Ministers from office by showing that it no longer enjoys the confidence of the Lok Sabha.' },
  { id: 'polity-bill-008', category: 'Polity - Motions', question: 'Which of the following statements about a Censure Motion is correct?', options: ['It can be moved only against the Prime Minister', 'It must state the reasons for its motion and, if passed, does not require the Council of Ministers to resign', 'It can be moved in the Rajya Sabha only', 'It automatically dissolves the Lok Sabha'], answer: 1, explanation: 'A Censure Motion must state specific reasons and, unlike a No-Confidence Motion, does not require the resignation of the Council of Ministers even if passed, though it usually does.' },
  { id: 'polity-bill-009', category: 'Polity - Motions', question: "An Adjournment Motion is used to:\nQ-2 1.A No-Confidence Motion can be introduced only in the Lok Sabha.\n2.A No-Confidence Motion must specify the reasons for lack of confidence in the Council of Ministers.\n3.At least 50 members must support the motion for it to be admitted.\nAnswer: Only two. ✅\n\n1 ✅ Lok Sabha only\n2 ❌ Reasons specify karna necessary nahi\n3 ✅ 50 members required", options: ['Draw the attention of the House to a definite matter of urgent public importance', 'Approve the annual budget', 'Amend the Constitution', 'Elect the Speaker'], answer: 0, explanation: "| Motion      | Purpose                             |\n| ----------- | ----------------------------------- |\n| Policy Cut  | Reduce demand to ₹1                 |\n| Token Cut   | Reduce demand by ₹100               |\n| Economy Cut | Reduce demand by a specified amount |\n"},
  { id: 'polity-bill-010', category: 'Polity - Motions', question: 'Which of the following motions can be moved only in the Lok Sabha and not in the Rajya Sabha?', options: ['Calling Attention Motion', 'No-Confidence Motion', 'Privilege Motion', 'Motion of Thanks'], answer: 1, explanation: 'A No-Confidence Motion can be moved only in the Lok Sabha since the Council of Ministers is collectively responsible only to the Lok Sabha (Article 75(3)).' },

  // ===================== PRESIDENT AND OTHER ARTICLES =====================
  { id: 'polity-pres-001', category: 'Polity - President', question: 'Which article of the Constitution provides for the impeachment of the President of India?', options: ['Article 56', 'Article 61', 'Article 72', 'Article 111'], answer: 1, explanation: 'Article 61 lays down the procedure for impeachment of the President for "violation of the Constitution".' },
  { id: 'polity-pres-002', category: 'Polity - President', question: 'Consider the following statements regarding the election of the President of India:\n1. The President is elected by an electoral college consisting of elected members of both Houses of Parliament and elected members of the Legislative Assemblies of States and UTs of Delhi and Puducherry.\n2. Nominated members of Parliament and State Legislatures also participate in the election.\nWhich of the statements given above is correct?', options: ['1 only', '2 only', 'Both 1 and 2', 'Neither 1 nor 2'], answer: 0, explanation: 'Only elected members participate in the President\'s election; nominated members of Parliament and Legislative Assemblies do not have voting rights in this election (Article 54).' },
  { id: 'polity-pres-003', category: 'Polity - President', question: 'Under Article 72, the pardoning power of the President extends to cases involving:', options: ['Only civil offences', 'Punishment or sentence by court martial, and death sentence cases, among others', 'Only offences against State law', 'Cases pending before the Supreme Court only'], answer: 1, explanation: 'Article 72 empowers the President to grant pardons in cases of punishment/sentence by court martial, offences against Union law, and all death sentence cases.' },
  { id: 'polity-pres-004', category: 'Polity - President', question: 'The Ordinance-making power of the President is provided under which article?', options: ['Article 121', 'Article 123', 'Article 143', 'Article 356'], answer: 1, explanation: 'Article 123 empowers the President to promulgate ordinances when Parliament is not in session.' },
  { id: 'polity-pres-005', category: 'Polity - President', question: 'An Ordinance promulgated by the President under Article 123 must be laid before Parliament and will cease to operate if not approved within how many weeks of Parliament reassembling?', options: ['4 weeks', '6 weeks', '8 weeks', '12 weeks'], answer: 1, explanation: 'An ordinance ceases to operate at the expiry of six weeks from the reassembly of Parliament unless approved by resolutions of both Houses.' },
  { id: 'polity-pres-006', category: 'Polity - President', question: 'Article 74 of the Constitution deals with:', options: ['Council of Ministers to aid and advise the President', 'Qualifications for the office of President', 'Impeachment of President', 'Emergency powers of President'], answer: 0, explanation: 'Article 74 provides for a Council of Ministers with the Prime Minister at the head to aid and advise the President, who acts in accordance with such advice.' },
  { id: 'polity-pres-007', category: 'Polity - President', question: 'Which article empowers the President to seek the opinion of the Supreme Court on questions of law or fact?', options: ['Article 131', 'Article 137', 'Article 143', 'Article 145'], answer: 2, explanation: 'Article 143 provides for the President\'s power to consult the Supreme Court on questions of law or fact of public importance (advisory jurisdiction).' },
  { id: 'polity-pres-008', category: 'Polity - President', question: 'The minimum age prescribed for a person to be eligible for election as President of India is:', options: ['25 years', '30 years', '35 years', '40 years'], answer: 2, explanation: 'Article 58 lays down that a candidate must have completed 35 years of age to be eligible for the office of President.' },
  { id: 'polity-pres-009', category: 'Polity - President', question: 'Disputes regarding the election of the President are inquired into and decided by:', options: ['The Election Commission of India', 'The Supreme Court of India', 'A Joint Sitting of Parliament', 'The Chief Justice of India alone'], answer: 1, explanation: 'Article 71 provides that all doubts and disputes arising out of the President\'s (or Vice-President\'s) election are decided by the Supreme Court, whose decision is final.' },
  { id: 'polity-pres-010', category: 'Polity - President', question: 'Consider the following statements about the President\'s veto power over ordinary bills:\n1. The President can exercise an absolute veto by withholding assent.\n2. The President can exercise a suspensive veto by returning the bill for reconsideration.\n3. If Parliament passes the bill again with or without amendments, the President must give assent.\nWhich of the statements given above is/are correct?', options: ['1 only', '1 and 2 only', '2 and 3 only', '1, 2 and 3'], answer: 3, explanation: "The President has absolute veto (withholding assent), suspensive veto (returning for reconsideration once), and must assent if Parliament re-passes the bill; the pocket veto (taking no action) is also available for ordinary bills but not explicitly listed here.\nArticle 111 + President ke veto powers", notes: ["Trick → Absolute = Approval se inkaar | Suspensive = Dobara socho | Repassed Bill = Assent zaroori."],},

  // ===================== PART VI - GOVERNOR (Articles 152-161, 170, 175, 200, 201, 213) =====================
  { id: 'polity-gov-001', category: 'Polity - Governor (Part VI)', question: 'Which article of the Constitution provides that there shall be a Governor for each State?', options: ['Article 152', 'Article 153', 'Article 154', 'Article 155'], answer: 1, explanation: 'Article 153 states that there shall be a Governor for each State; the same person can be appointed Governor for two or more States (post-7th Amendment).' },
  { id: 'polity-gov-002', category: 'Polity - Governor (Part VI)', question: 'The Governor of a State is appointed by the President under which article, and holds office during his:', options: ['Article 154; own discretion', 'Article 155; pleasure of the President', 'Article 156; pleasure of the Chief Minister', 'Article 157; fixed 5-year term without removal'], answer: 1, explanation: 'Article 155 provides for appointment of the Governor by the President; Article 156 says the Governor holds office during the pleasure of the President.' },
  { id: 'polity-gov-003', category: 'Polity - Governor (Part VI)', question: 'Article 157 of the Constitution prescribes which of the following qualifications for the Governor?', options: ['Must be a member of the State Legislature', 'Must be a citizen of India and have completed 35 years of age', 'Must have completed 25 years of age', 'Must be domiciled in the State concerned'], answer: 1, explanation: 'Article 157 requires that a person be a citizen of India and have completed the age of 35 years to be eligible for appointment as Governor.' },
  { id: 'polity-gov-004', category: 'Polity - Governor (Part VI)', question: 'Article 161 empowers the Governor to grant pardons, reprieves, respites or remissions of punishment. However, this power does NOT extend to:', options: ['Offences against State law', 'Death sentence cases', 'Sentences by a court martial', 'Both death sentence cases and court martial sentences'], answer: 3, explanation: 'Unlike the President under Article 72, the Governor under Article 161 cannot pardon a death sentence or a sentence given by a court martial.' },
  { id: 'polity-gov-005', category: 'Polity - Governor (Part VI)', question: 'Article 170 of the Constitution deals with:', options: ['Composition of the Legislative Assemblies of States', 'Composition of Legislative Councils', 'Governor\'s power to summon the legislature', 'Governor\'s discretionary powers'], answer: 0, explanation: 'Article 170 provides for the composition of the Legislative Assemblies of the States, fixing the number of seats subject to a minimum and maximum.' },
  { id: 'polity-gov-006', category: 'Polity - Governor (Part VI)', question: 'The minimum age required to be a member of a State Legislative Assembly, as per Article 173, is:', options: ['21 years', '25 years', '30 years', '35 years'], answer: 1, explanation: 'Article 173 prescribes a minimum age of 25 years for membership of the Legislative Assembly of a State.' },
  { id: 'polity-gov-007', category: 'Polity - Governor (Part VI)', question: 'Under Article 175, the Governor has the power to:', options: ['Address and send messages to the House or Houses of the State Legislature', 'Dissolve the Lok Sabha', 'Appoint the Chief Justice of the High Court', 'Remove the Speaker of the Assembly'], answer: 0, explanation: 'Article 175 empowers the Governor to address the House(s) of the State Legislature and send messages to it regarding a pending bill or otherwise.' },
  { id: 'polity-gov-008', category: 'Polity - Governor (Part VI)', question: 'Consider the following statements regarding Article 200 of the Constitution:\n1. The Governor may give assent to a bill, withhold assent, or return it (if not a Money Bill) for reconsideration.\n2. The Governor may reserve a bill for the consideration of the President.\n3. If the State Legislature re-passes the bill, the Governor is bound to give assent.\nWhich of the statements given above is/are correct?', options: ['1 only', '1 and 2 only', '2 and 3 only', '1, 2 and 3'], answer: 3, explanation: 'Article 200 gives the Governor options of assent, withholding assent, returning for reconsideration (except Money Bills), or reserving for the President; if re-passed, the Governor cannot withhold assent again, though reservation for the President remains an option under proviso.' },
  { id: 'polity-gov-009', category: 'Polity - Governor (Part VI)', question: 'Article 201 of the Constitution deals with:', options: ['Bills reserved by the Governor for the consideration of the President', 'The Governor\'s ordinance-making power', 'The appointment of the Advocate General of the State', 'The State Public Service Commission'], answer: 0, explanation: 'Article 201 provides that when a bill is reserved by the Governor for the President\'s consideration, the President may either give assent, withhold assent, or (if not a Money Bill) direct the Governor to return it for reconsideration.' },
  { id: 'polity-gov-010', category: 'Polity - Governor (Part VI)', question: 'Article 213 of the Constitution empowers the Governor to:', options: ['Promulgate Ordinances during recess of the State Legislature', 'Appoint the Chief Minister only from the ruling party', 'Nominate the Speaker of the Assembly', 'Dismiss the Chief Justice of the High Court'], answer: 0, explanation: 'Article 213 empowers the Governor to promulgate Ordinances when the State Legislature (or one House in a bicameral State) is not in session, subject to similar conditions as the President\'s ordinance power.' },
  { id: 'polity-gov-011', category: 'Polity - Governor (Part VI)', question: 'Which of the following is a discretionary power of the Governor, exercised without the aid and advice of the Council of Ministers?', options: ['Appointing the Advocate General', 'Reserving certain bills for the President\'s consideration', 'Summoning the Assembly', 'Presenting the budget'], answer: 1, explanation: 'Reserving certain bills for the President\'s consideration is one of the situations in which the Governor can act in his discretion under the proviso to Article 200.' },

  // ===================== SUPREME COURT (Articles 124-131, 137, 140-144, 139A) =====================
  { id: 'polity-sc-001', category: 'Polity - Supreme Court', question: 'Article 124 of the Constitution provides for:', options: ['Establishment and constitution of the Supreme Court', 'Jurisdiction of the Supreme Court', 'Appointment of the Attorney General', 'Advisory jurisdiction of the Supreme Court'], answer: 0, explanation: 'Article 124 establishes the Supreme Court of India and lays down provisions regarding appointment, qualification and removal of judges.' },
  { id: 'polity-sc-002', category: 'Polity - Supreme Court', question: 'A Judge of the Supreme Court can be removed from office by an order of the President, passed after an address by each House of Parliament, on the ground of:', options: ['Proved misbehaviour or incapacity', 'Political disagreement with the government', 'Reaching the age of 65 years', 'Loss of confidence of the Bar Council'], answer: 0, explanation: 'Article 124(4) provides for removal of a Supreme Court judge only on the ground of proved misbehaviour or incapacity, through a motion passed by special majority in each House.' },
  { id: 'polity-sc-003', category: 'Polity - Supreme Court', question: 'Article 131 of the Constitution deals with which jurisdiction of the Supreme Court?', options: ['Appellate jurisdiction', 'Original jurisdiction in disputes between Government of India and States/States inter se', 'Advisory jurisdiction', 'Writ jurisdiction'], answer: 1, explanation: 'Article 131 gives the Supreme Court exclusive original jurisdiction in disputes between the Government of India and one or more States, or between States.' },
  { id: 'polity-sc-004', category: 'Polity - Supreme Court', question: 'Article 137 of the Constitution empowers the Supreme Court to:', options: ['Review its own judgments or orders', 'Transfer cases from one High Court to another', 'Appoint judges of High Courts', 'Advise the President on questions of law'], answer: 0, explanation: 'Article 137 gives the Supreme Court power to review any judgment or order made by it, subject to law made by Parliament or rules made under Article 145.' },
  { id: 'polity-sc-005', category: 'Polity - Supreme Court', question: 'Under Article 141, the law declared by the Supreme Court is:', options: ['Binding only on the parties to the case', 'Binding on all courts within the territory of India', 'Advisory in nature only', 'Binding only on High Courts, not subordinate courts'], answer: 1, explanation: 'Article 141 makes the law declared by the Supreme Court binding on all courts within the territory of India.' },
  { id: 'polity-sc-006', category: 'Polity - Supreme Court', question: 'Article 143 of the Constitution provides for which power of the Supreme Court?', options: ['Original jurisdiction in Centre-State disputes', 'Advisory jurisdiction on a reference made by the President', 'Power to punish for contempt of court', 'Power to transfer cases between High Courts'], answer: 1, explanation: 'Article 143 empowers the President to refer questions of law or fact of public importance to the Supreme Court for its advisory opinion; the opinion given is not binding on the President.' },
  { id: 'polity-sc-007', category: 'Polity - Supreme Court', question: 'Article 144 of the Constitution requires:', options: ['All courts, civil and judicial, to act in aid of the Supreme Court', 'The Supreme Court to obey the Parliament', 'The President to act on Supreme Court advice', 'The Governor to follow High Court orders'], answer: 0, explanation: 'Article 144 mandates that all authorities, civil and judicial, in the territory of India shall act in aid of the Supreme Court.' },
  { id: 'polity-sc-008', category: 'Polity - Supreme Court', question: 'Article 139A, inserted by the 42nd Amendment Act, 1976, deals with:', options: ['Transfer of certain cases from High Courts to the Supreme Court', 'Establishment of a National Judicial Commission', 'Advisory jurisdiction of the Supreme Court', 'Contempt of court powers'], answer: 0, explanation: 'Article 139A empowers the Supreme Court to transfer or withdraw cases involving substantially the same questions of law pending before two or more High Courts, to itself.' },
  { id: 'polity-sc-009', category: 'Polity - Supreme Court', question: 'Consider the following statements regarding the strength of the Supreme Court:\n1. The original Constitution provided for a Chief Justice and 7 other judges.\n2. Parliament has, from time to time, increased the sanctioned strength of judges by law.\n3. Currently, the sanctioned strength of the Supreme Court (including CJI) is 34.\nWhich of the statements given above is/are correct?', options: ['1 only', '1 and 2 only', '2 and 3 only', '1, 2 and 3'], answer: 3, explanation: 'The original strength was 8 (CJI + 7 judges); Parliament raised it periodically under Article 124(1), and since the 2019 amendment the sanctioned strength is 34 (CJI + 33 judges).' },
  { id: 'polity-sc-010', category: 'Polity - Supreme Court', question: 'Which article empowers Parliament to increase the number of judges of the Supreme Court by law?', options: ['Article 124(1)', 'Article 128', 'Article 130', 'Article 146'], answer: 0, explanation: 'Article 124(1) provides that the Supreme Court shall consist of the Chief Justice and other judges as Parliament may by law prescribe.' },

  // ===================== NATIONAL EMERGENCY (Article 352) =====================
  { id: 'polity-nemg-001', category: 'Polity - National Emergency', question: 'Under Article 352, what legislative consequence follows a Proclamation of National Emergency in India?', options: ['States retain exclusive control over the State List', 'Parliament can legislate on any matter in the State List', 'Rajya Sabha\'s approval is required for all State Bills', 'President dissolves all State Legislative Assemblies'], answer: 1, explanation: "During a National Emergency, Parliament becomes empowered under Article 250 to make laws on any subject in the State List, even though the State Legislatures continue to function.\n\nArticle 352 se Emergency declare hoti hai → Article 250 Parliament ko State List par law banane ki power deta hai"},
  { id: 'polity-nemg-002', category: 'Polity - National Emergency', question: 'A Proclamation of National Emergency under Article 352 can be issued on grounds of:', options: ['War, external aggression or armed rebellion', 'Failure of constitutional machinery in a State', 'Financial instability of the Union', 'Communal riots in a State'], answer: 0, explanation: 'Article 352 allows the President to proclaim a National Emergency on grounds of war, external aggression or armed rebellion (the term "internal disturbance" was replaced by "armed rebellion" by the 44th Amendment).' },
  { id: 'polity-nemg-003', category: 'Polity - National Emergency', question: 'A Proclamation of National Emergency must be approved by both Houses of Parliament within how many months, and by what majority?', options: ['1 month, simple majority', '2 months, simple majority', '1 month, special majority', '2 months, special majority'], answer: 2, explanation: 'As per the 44th Amendment, a National Emergency proclamation must be approved by both Houses within one month by a special majority (majority of total membership and 2/3rd of members present and voting).' },
  { id: 'polity-nemg-004', category: 'Polity - National Emergency', question: 'Which Fundamental Right(s) cannot be suspended even during a National Emergency, as per the 44th Amendment Act?', options: ['Article 19 rights', 'Articles 20 and 21', 'Right to property', 'Right to equality under Article 14'], answer: 1, explanation: 'The 44th Amendment Act, 1978 ensured that Articles 20 and 21 cannot be suspended even during a National Emergency.' },
  { id: 'polity-nemg-005', category: 'Polity - National Emergency', question: 'Consider the following statements regarding National Emergency under Article 352:\n1. Article 19 freedoms are automatically suspended only when the Emergency is declared on the ground of war or external aggression, not armed rebellion.\n2. The Proclamation of Emergency can be revoked by the President at any time by a subsequent proclamation.\nWhich of the statements given above is/are correct?', options: ['1 only', '2 only', 'Both 1 and 2', 'Neither 1 nor 2'], answer: 2, explanation: 'As per the 44th Amendment, Article 19 rights are automatically suspended only for war/external aggression emergencies, not for armed rebellion; also, the President can revoke the proclamation at any time.' },
  { id: 'polity-nemg-006', category: 'Polity - National Emergency', question: 'How many times has a National Emergency under Article 352 been proclaimed in India so far?', options: ['Once', 'Twice', 'Thrice', 'Four times'], answer: 2, explanation: 'National Emergency has been proclaimed three times: 1962 (China war), 1971 (Pakistan war), and 1975 (internal disturbance).' },

  // ===================== STATE EMERGENCY / PRESIDENT'S RULE (Article 356) =====================
  { id: 'polity-semg-001', category: 'Polity - State Emergency (President\'s Rule)', question: 'Which article of the Constitution provides for the imposition of President\'s Rule in a State due to failure of constitutional machinery?', options: ['Article 352', 'Article 356', 'Article 360', 'Article 365'], answer: 1, explanation: 'Article 356 provides for President\'s Rule when the President is satisfied that the government of a State cannot be carried on in accordance with the Constitution.' },
  { id: 'polity-semg-002', category: 'Polity - State Emergency (President\'s Rule)', question: 'A Proclamation under Article 356 must be approved by Parliament within how many months of its issue?', options: ['One month', 'Two months', 'Three months', 'Six months'], answer: 1, explanation: 'A Proclamation under Article 356 must be approved by both Houses of Parliament within two months, else it ceases to operate.' },
  { id: 'polity-semg-003', category: 'Polity - State Emergency (President\'s Rule)', question: 'Which of the following statements is/are correct regarding the extension of President\'s Rule beyond one year?', options: ['It can never be extended beyond one year under any circumstances', 'It can be extended beyond one year only if a National Emergency is in operation or the Election Commission certifies that elections cannot be held', 'It can be extended indefinitely without any condition', 'Only the Supreme Court can approve extension beyond one year'], answer: 1, explanation: 'As per the 44th Amendment, President\'s Rule can be extended beyond one year (up to 3 years total) only if a National Emergency is in operation, or the Election Commission certifies difficulty in holding State elections.' },
  { id: 'polity-semg-004', category: 'Polity - State Emergency (President\'s Rule)', question: 'The maximum period for which President\'s Rule can continue in a State, in total, is:', options: ['1 year', '2 years', '3 years', '5 years'], answer: 2, explanation: 'President\'s Rule can be extended for a maximum period of 3 years, through six-monthly extensions, subject to conditions laid down by the 44th Amendment.' },
  { id: 'polity-semg-005', category: 'Polity - State Emergency (President\'s Rule)', question: 'The Supreme Court, in the S.R. Bommai case (1994), held that:', options: ['Article 356 is not subject to judicial review at all', 'The proclamation under Article 356 is subject to judicial review and floor test is the true measure of majority', 'Only the Governor can decide on President\'s Rule finally', 'President\'s Rule cannot ever be revoked'], answer: 1, explanation: 'The S.R. Bommai case held that the exercise of power under Article 356 is subject to judicial review and that the majority of a government should be tested on the floor of the House.' },

  // ===================== FINANCIAL EMERGENCY (Article 360) =====================
  { id: 'polity-femg-001', category: 'Polity - Financial Emergency', question: 'Which of the following accurately reflects the constitutional provisions and historical application of Financial Emergency under Article 360?', options: ['No Financial Emergency has ever been declared in India', 'A Financial Emergency was declared during the 1991 economic crisis', 'Article 360 allows States to withhold salaries of central employees', 'During a Financial Emergency, only the President can dismiss the Union Cabinet'], answer: 0, explanation: 'Article 360 provides for Financial Emergency, but it has never been declared in India, including during the 1991 balance of payments crisis.' },
  { id: 'polity-femg-002', category: 'Polity - Financial Emergency', question: 'During a Financial Emergency under Article 360, the President can direct:', options: ['Reduction of salaries and allowances of persons serving the Union or a State, including judges of the Supreme Court and High Courts', 'Dissolution of the Supreme Court', 'Suspension of the Right to Vote', 'Automatic dismissal of all State Governors'], answer: 0, explanation: 'Article 360 empowers the President to direct reduction in salaries/allowances of all or any class of persons serving the Union and the States, including judges of the Supreme Court and High Courts.' },
  { id: 'polity-femg-003', category: 'Polity - Financial Emergency', question: 'A Proclamation of Financial Emergency, once approved by Parliament, remains in operation for:', options: ['A maximum of six months and cannot be extended', 'Indefinitely until revoked by the President; no maximum period is specified in the Constitution', 'A maximum of one year only', 'A maximum of three years only'], answer: 1, explanation: 'Unlike President\'s Rule under Article 356, the Constitution does not prescribe a maximum period for Financial Emergency; it continues indefinitely until revoked.' },

  // ===================== ARTICLES 309-312 (Services) =====================
  { id: 'polity-service-001', category: 'Polity - Services (Art 309-312)', question: 'Article 309 of the Constitution deals with:', options: ['Recruitment and conditions of service of persons serving the Union or a State', 'Formation of All India Services', 'Constitution of Public Service Commissions', 'Tenure of office of civil servants'], answer: 0, explanation: 'Article 309 empowers the appropriate legislature to regulate recruitment and conditions of service of persons appointed to public services under the Union or a State.' },
  { id: 'polity-service-002', category: 'Polity - Services (Art 309-312)', question: 'The "doctrine of pleasure" regarding tenure of civil servants, subject to certain safeguards, is provided under which article?', options: ['Article 309', 'Article 310', 'Article 311', 'Article 312'], answer: 1, explanation: 'Article 310 lays down that civil servants of the Union and States hold office during the pleasure of the President or Governor respectively.' },
  { id: 'polity-service-003', category: 'Polity - Services (Art 309-312)', question: 'Article 311 provides constitutional safeguards to civil servants regarding:', options: ['Dismissal, removal or reduction in rank', 'Salary increments only', 'Transfer to another department', 'Promotion criteria'], answer: 0, explanation: 'Article 311 provides that no civil servant can be dismissed, removed, or reduced in rank without an inquiry giving a reasonable opportunity of being heard, subject to certain exceptions.' },
  { id: 'polity-service-004', category: 'Polity - Services (Art 309-312)', question: 'Article 312 empowers the creation of All India Services. Consider the following statements:\n1. All India Services are common to both the Union and the States.\n2. New All India Services can be created only if the Rajya Sabha passes a resolution by a special majority declaring it necessary in the national interest.\nWhich of the statements given above is/are correct?', options: ['1 only', '2 only', 'Both 1 and 2', 'Neither 1 nor 2'], answer: 2, explanation: 'Article 312 provides that new All India Services can be created if the Rajya Sabha declares by a resolution (supported by not less than two-thirds of members present and voting) that it is necessary in the national interest; these services are common to the Union and States.' },
  { id: 'polity-service-005', category: 'Polity - Services (Art 309-312)', question: 'Which of the following are recognised as the original All India Services under the Constitution?', options: ['IAS and IPS only', 'IAS, IPS and IFoS (Indian Forest Service)', 'IAS, IPS, IRS and IFS', 'Only IAS'], answer: 1, explanation: 'The IAS and IPS existed since before the Constitution; the Indian Forest Service (IFoS) was created later in 1966 as the third All India Service under Article 312.' },

  // ===================== ARTICLES 324-329 (Elections) =====================
  { id: 'polity-elec-001', category: 'Polity - Elections (Art 324-329)', question: 'Article 324 of the Constitution vests the power of superintendence, direction and control of elections in:', options: ['The Parliament of India', 'The Election Commission of India', 'The President of India', 'The Supreme Court of India'], answer: 1, explanation: 'Article 324 vests the superintendence, direction and control of elections to Parliament, State Legislatures, and the offices of President and Vice-President in the Election Commission of India.' },
  { id: 'polity-elec-002', category: 'Polity - Elections (Art 324-329)', question: 'Article 325 provides that:', options: ['No person shall be ineligible for inclusion in an electoral roll on grounds of religion, race, caste or sex', 'Only literate persons can vote', 'Elections must be held every three years', 'Voting is compulsory for all citizens'], answer: 0, explanation: "Har territorial constituency ke liye one general electoral roll hoga.\n→ Kisi person ko religion, race, caste ya sex ke basis par electoral roll mein include hone se exclude nahi kiya ja sakta.\n→ Inhi grounds par kisi ke liye special/separate electoral roll ki demand nahi ki ja sakti."},
  { id: 'polity-elec-003', category: 'Polity - Elections (Art 324-329)', question: 'Article 326 of the Constitution establishes which principle for elections to the Lok Sabha and State Assemblies?', options: ['Adult suffrage (universal adult franchise)', 'Proportional representation', 'Indirect election', 'Reserved constituencies only for minorities'], answer: 0, explanation: 'Article 326 provides for elections on the basis of adult suffrage, with the minimum voting age fixed at 18 years (reduced from 21 by the 61st Amendment).' },
  { id: 'polity-elec-004', category: 'Polity - Elections (Art 324-329)', question: 'Article 329 bars courts from interfering in electoral matters, providing that election disputes can be raised only through:', options: ['A writ petition in the Supreme Court', 'An election petition presented to an authority as provided by law made by Parliament', 'A complaint to the President', 'A resolution in Parliament'], answer: 1, explanation: 'Article 329(b) bars courts from questioning elections except through an election petition presented to the authority and in the manner prescribed by law made by the appropriate legislature.',  notes: ["Election chalne do → baad mein Election Petition."],},
  { id: 'polity-elec-005', category: 'Polity - Elections (Art 324-329)', question: 'Which article of the Constitution provides that the validity of laws relating to delimitation of constituencies cannot be questioned in any court?', options: ['Article 324', 'Article 327', 'Article 328', 'Article 329'], answer: 3, explanation: 'Article 329(a) bars questioning the validity of any law relating to the delimitation of constituencies or the allotment of seats made under Article 327 or 328.' },
  { id: 'polity-elec-006', category: 'Polity - Elections (Art 324-329)', question: 'The reduction of the voting age from 21 years to 18 years was brought about by which constitutional amendment?', options: ['52nd Amendment', '61st Amendment', '73rd Amendment', '86th Amendment'], answer: 1, explanation: 'The 61st Constitutional Amendment Act, 1988 reduced the voting age from 21 to 18 years for elections to the Lok Sabha and State Legislative Assemblies.' },

  // ===================== ARTICLE 263 - INTER-STATE COUNCIL =====================
  { id: 'polity-263-001', category: 'Polity - Article 263 (Inter-State Council)', question: 'Article 263 of the Constitution provides for the establishment of:', options: ['An Inter-State Council to inquire into and advise upon disputes between States', 'A National Development Council', 'The Finance Commission', 'The Zonal Councils'], answer: 0, explanation: 'Article 263 empowers the President to establish an Inter-State Council if it appears that public interest would be served by it, to inquire into and advise on inter-State disputes and coordination.' },
  { id: 'polity-263-002', category: 'Polity - Article 263 (Inter-State Council)', question: 'Consider the following statements:\n1. Article 262 empowers Parliament to make laws for adjudication of disputes relating to inter-State rivers or river valleys.\n2. The Supreme Court has appellate jurisdiction over such disputes.\nWhich of the statements given above is/are correct?', options: ['1 only', '2 only', 'Both 1 and 2', 'Neither 1 nor 2'], answer: 0, explanation: "Article 262(1):\nParliament law bana sakti hai for adjudication of disputes relating to the use, distribution or control of waters of an inter-State river or river valley.\n\nArticle 262(2):\nParliament law ke through Supreme Court aur other courts ki jurisdiction ko exclude kar sakti hai in such disputes.\n\n🧠 Easy Trick\n\n262 = River Water Dispute"},
  { id: 'polity-263-003', category: 'Polity - Article 263 (Inter-State Council)', question: 'The Inter-State Council established under Article 263 in 1990 was set up on the recommendation of which commission?', options: ['Sarkaria Commission', 'Punchhi Commission', 'Rajamannar Committee', 'National Commission to Review the Working of the Constitution'], answer: 0, explanation: 'The Inter-State Council was set up in 1990 by a Presidential Order, following the recommendations of the Sarkaria Commission on Centre-State relations.' },

  // ===================== ARTICLE 239AA - DELHI =====================
  { id: 'polity-239aa-001', category: 'Polity - Article 239AA (Delhi)', question: 'Article 239AA of the Constitution, inserted by the 69th Amendment Act, 1991, provides for:', options: ['Special provisions for the National Capital Territory of Delhi', 'Special provisions for Jammu and Kashmir', 'Special provisions for Puducherry', 'Special provisions for the North-Eastern States'], answer: 0, explanation: 'Article 239AA was inserted by the 69th Constitutional Amendment Act, 1991, giving Delhi a Legislative Assembly and a Council of Ministers with special status as the National Capital Territory (NCT).' },
  { id: 'polity-239aa-002', category: 'Polity - Article 239AA (Delhi)', question: 'Why is the legislative power of the Delhi Legislative Assembly different from that of other Union Territories with Assemblies?', options: ['The Delhi Assembly has no Speaker', 'The Delhi Legislative Assembly has power to legislate over subjects in the State List and Concurrent List, except for police, public order and land', 'The Delhi Assembly cannot pass laws on any subject', 'The Delhi Assembly is directly controlled by the Supreme Court of India'], answer: 1, explanation: "Article 239 → Union Territories administration\nArticle 239A → Certain UTs के लिए Legislature/Council of Ministers\nArticle 239AA → Special provisions for Delhi ⭐\nArticle 239AB → Failure of constitutional machinery in Delhi"},
  { id: 'polity-239aa-003', category: 'Polity - Article 239AA (Delhi)', question: 'Consider the following statements regarding the NCT of Delhi:\n1. In case of a difference of opinion between the Lieutenant Governor and Council of Ministers, the matter is referred to the President.\n2. The Lieutenant Governor is bound by the aid and advice of the Council of Ministers on all subjects without exception.\nWhich of the statements given above is/are correct?', options: ['1 only', '2 only', 'Both 1 and 2', 'Neither 1 nor 2'], answer: 0, explanation: "Article 239AA(4) ke according, agar LG aur Council of Ministers ke beech kisi matter par disagreement ho, to LG matter ko President ke consideration ke liye refer kar sakta hai.\n\n⚠️ Lekin ek important exception hai: agar matter urgent hai, to LG immediate action bhi le sakta hai, subject to constitutional provisions."},

  // ===================== PANCHAYATS AND MUNICIPALITIES (73rd & 74th Amendments) =====================
  { id: 'polity-73rd-001', category: 'Polity - 73rd Amendment / Panchayati Raj', question: 'The 73rd Constitutional Amendment Act, 1992, added which Part and Schedule to the Constitution?', options: ['Part IX and Eleventh Schedule', 'Part IXA and Twelfth Schedule', 'Part X and Fifth Schedule', 'Part XIV and Ninth Schedule'], answer: 0, explanation: 'The 73rd Amendment Act, 1992 inserted Part IX (Articles 243-243O) dealing with Panchayats, and the Eleventh Schedule listing 29 subjects for Panchayats.' },
  { id: 'polity-73rd-002', category: 'Polity - 73rd Amendment / Panchayati Raj', question: 'Which of the following provisions was NOT mandatory (i.e., was left to the discretion of States) under the 73rd Constitutional Amendment Act?', options: ['Not less than one-third of the seats reserved for women in every Panchayat', 'Establishment of a three-tier structure in every State', 'Reservation of seats for SCs and STs in proportion to their population in every Panchayat', 'Regular elections to be held every five years'], answer: 1, explanation: 'The three-tier structure (village, intermediate, district level) is not mandatory for smaller States with population below 2 million, which may not have an intermediate level; reservation for women, SC/ST, and regular five-yearly elections are mandatory provisions.' },
  { id: 'polity-73rd-003', category: 'Polity - 73rd Amendment / Panchayati Raj', question: 'Under the 73rd Amendment Act, the tenure of a Panchayat at any level is:', options: ['3 years', '5 years', '6 years', 'No fixed term'], answer: 1, explanation: 'The 73rd Amendment fixed the term of a Panchayat at 5 years from the date of its first meeting, unless dissolved earlier.' },
  { id: 'polity-73rd-004', category: 'Polity - 73rd Amendment / Panchayati Raj', question: 'Consider the following statements about the 73rd Amendment Act:\n1. It provides for a State Election Commission to conduct elections to Panchayats.\n2. It provides for a State Finance Commission to review the financial position of Panchayats.\n3. Fresh elections must be conducted before the expiry of the Panchayat\'s term or within six months of its dissolution.\nWhich of the statements given above is/are correct?', options: ['1 only', '1 and 2 only', '2 and 3 only', '1, 2 and 3'], answer: 3, explanation: 'The 73rd Amendment provides for a State Election Commission (Article 243K), a State Finance Commission (Article 243I), and mandates fresh elections before term expiry or within six months of dissolution.' },
  { id: 'polity-73rd-005', category: 'Polity - 73rd Amendment / Panchayati Raj', question: 'The Gram Sabha, as provided under Article 243A, is:', options: ['A body consisting of persons registered in the electoral rolls of a village comprised within a Panchayat', 'The apex body of the three-tier Panchayat system', 'A nominated body of experts', 'Same as the Zila Parishad'], answer: 0, explanation: 'Article 243A defines the Gram Sabha as a body consisting of persons registered in the electoral rolls of a village within the area of a Panchayat at the village level.' },
  { id: 'polity-74th-001', category: 'Polity - 74th Amendment / Municipalities', question: 'The 74th Constitutional Amendment Act, 1992, dealing with Municipalities, added which Part and Schedule?', options: ['Part IX and Eleventh Schedule', 'Part IXA and Twelfth Schedule', 'Part IXB and Thirteenth Schedule', 'Part X and Sixth Schedule'], answer: 1, explanation: 'The 74th Amendment Act, 1992 inserted Part IXA (Articles 243P-243ZG) on Municipalities and the Twelfth Schedule listing 18 functional items for them.' },
  { id: 'polity-74th-002', category: 'Polity - 74th Amendment / Municipalities', question: 'As per the 74th Amendment Act, how many types of Municipalities are constituted based on the size and nature of the area?', options: ['Two: Nagar Panchayat and Municipal Corporation', 'Three: Nagar Panchayat, Municipal Council, Municipal Corporation', 'Four types including Cantonment Board', 'Only one type of Municipality for all urban areas'], answer: 1, explanation: 'Article 243Q provides for three types of Municipalities: Nagar Panchayat (transitional area), Municipal Council (smaller urban area), and Municipal Corporation (larger urban area).' },
  { id: 'polity-74th-003', category: 'Polity - 74th Amendment / Municipalities', question: 'The Metropolitan Planning Committee, provided under Article 243ZE, is constituted for areas with a population of:', options: ['5 lakh or more', '10 lakh or more', '20 lakh or more', '50 lakh or more'], answer: 1, explanation: 'Article 243ZE mandates the constitution of a Metropolitan Planning Committee for every metropolitan area having a population of ten lakh or more.' },

  // ===================== PARLIAMENTARY COMMITTEES =====================
  { id: 'polity-comm-001', category: 'Polity - Parliamentary Committees', question: 'Why are Parliamentary Committees considered essential for Indian democracy?', options: ['They allow detailed, technical scrutiny of legislation, budgets and administration that the full House cannot undertake, ensuring accountability of the executive to Parliament', 'They replace the need for floor debates entirely', 'They are directly elected by the people', 'They have the power to dissolve the Council of Ministers'], answer: 0, explanation: 'Parliamentary Committees enable focused, expert, non-partisan scrutiny of bills, budgetary demands, and government functioning in ways plenary sessions cannot, strengthening legislative oversight and executive accountability while easing the burden on the full House.' },
  { id: 'polity-comm-002', category: 'Polity - Parliamentary Committees', question: 'Which is the largest Parliamentary Committee in terms of membership?', options: ['Public Accounts Committee', 'Estimates Committee', 'Committee on Public Undertakings', 'Business Advisory Committee'], answer: 1, explanation: "The Estimates Committee is the largest Parliamentary Committee, with 30 members, all from the Lok Sabha.\no → Estimates = Estimated expenditure ki scrutiny + Economy + Efficiency → 30 members, only Lok Sabha."},
  { id: 'polity-comm-003', category: 'Polity - Parliamentary Committees', question: 'The Public Accounts Committee (PAC) and the Estimates Committee are often referred to as "twin sister committees" because:', options: ['Both examine government expenditure — PAC scrutinises expenditure already incurred based on the CAG\'s report, while the Estimates Committee examines estimates in the budget for economy', 'Both have identical membership', 'Both are chaired by the Speaker', 'Both are constitutional bodies'], answer: 0, explanation: "The PAC and Estimates Committee are called twin sister committees because they both deal with financial control over the executive — PAC examines actual expenditure via CAG reports, while the Estimates Committee examines budget estimates for efficiency and economy.\n\nExample → Schools ke liye ₹1,000 crore ka budget:\n→ Estimates Committee: Cost kam karke achhe schools kaise banayein?\n→ PAC: Jo paisa kharch hua, kya woh approved purpose aur rules ke according tha?\n\nIsliye “Twin Sisters” → Dono ka common goal: Public money ka sahi use aur government ki financial accountability.\nTrick → Estimates = Kharch ki planning ki jaanch | PAC = Hue kharch ka hisaab."},
  { id: 'polity-comm-004', category: 'Polity - Parliamentary Committees', question: 'The Public Accounts Committee examines the accounts of the Government of India based on the report submitted by:', options: ['The Finance Minister', 'The Comptroller and Auditor General (CAG)', 'The Reserve Bank of India', 'The Finance Commission'], answer: 1, explanation: "→ CAG government ke accounts ka audit karta hai—kharch aur financial records ki jaanch.\n→ PAC, CAG ki reports ke basis par government expenditure examine karti hai.\n\nProcess → CAG report → President → Parliament ke saamne rakhi jati hai → PAC examination.\n\nTrick → CAG = Audit karta hai | PAC = Audit report examine karti hai."},
  { id: 'polity-comm-005', category: 'Polity - Parliamentary Committees', question: 'Which of the following statements about the Committee on Public Undertakings is correct?', options: ['It examines the reports and accounts of Public Sector Undertakings and reports whether they are managed efficiently', 'It only oversees private sector companies', 'It has the power to appoint CEOs of PSUs', 'It was established by a constitutional amendment'], answer: 0, explanation: 'The Committee on Public Undertakings examines reports/accounts of PSUs and their functioning, checking whether they are managed in accordance with sound business principles.' },
  { id: 'polity-comm-006', category: 'Polity - Parliamentary Committees', question: 'Consider the following statements regarding Departmentally Related Standing Committees (DRSCs):\n1. They were constituted in 1993 to increase parliamentary scrutiny of government departments.\n2. There are currently 24 DRSCs, each covering one or more ministries/departments.\n3. Their reports are binding on the government.\nWhich of the statements given above is/are correct?', options: ['1 only', '1 and 2 only', '2 and 3 only', '1, 2 and 3'], answer: 1, explanation: 'DRSCs were constituted in 1993 and currently number 24, covering all ministries; however, their recommendations are advisory in nature and not binding on the government.' },
  { id: 'polity-comm-007', category: 'Polity - Parliamentary Committees', question: 'The Business Advisory Committee of the Lok Sabha is chaired by:', options: ['The Prime Minister', 'The Speaker of the Lok Sabha', 'The Leader of the Opposition', 'The Deputy Speaker'], answer: 1, explanation: 'The Business Advisory Committee, which regulates the time-table of business in the House, is chaired by the Speaker of the Lok Sabha.' },
  { id: 'polity-comm-008', category: 'Polity - Parliamentary Committees', question: 'Which committee scrutinizes delegated legislation, i.e., rules and regulations framed by the executive under powers delegated by Parliament?', options: ['Committee on Subordinate Legislation', 'Committee on Government Assurances', 'Rules Committee', 'Committee of Privileges'], answer: 0, explanation: 'The Committee on Subordinate Legislation examines whether the powers to make rules, regulations, bye-laws conferred by the Constitution or statutes are being properly exercised by the executive.' },
  { id: 'polity-comm-009', category: 'Polity - Parliamentary Committees', question: 'The Chairman of the Public Accounts Committee, by convention, is a member of:', options: ['The ruling party only', 'The Opposition', 'The Rajya Sabha only', 'A judicial appointee, not an MP'], answer: 1, explanation: 'By convention since 1967, the Chairman of the Public Accounts Committee is a member of the Opposition, appointed by the Speaker.' },
  { id: 'polity-comm-010', category: 'Polity - Parliamentary Committees', question: 'Ad hoc Committees of Parliament differ from Standing Committees in that:', options: ['Ad hoc Committees are permanent bodies, while Standing Committees are temporary', 'Ad hoc Committees are created for a specific purpose and cease to exist once that purpose is fulfilled, unlike Standing Committees which are permanent', 'Ad hoc Committees can only be formed by the President', 'There is no difference between them'], answer: 1, explanation: 'Ad hoc Committees (e.g., Select/Joint Committees on Bills) are constituted for a specific purpose and dissolve after completing their task, unlike Standing Committees, which are permanent and reconstituted periodically.' },

  // ===================== ZONAL COUNCILS AND IMPORTANT COMMISSIONS =====================
  { id: 'polity-zonal-001', category: 'Polity - Zonal Councils & Commissions', question: 'Zonal Councils in India were established under which act?', options: ['States Reorganisation Act, 1956', 'Government of India Act, 1935', 'North-Eastern Council Act, 1971', 'Constitution (7th Amendment) Act, 1956'], answer: 0, explanation: 'Zonal Councils are statutory (not constitutional) bodies set up under the States Reorganisation Act, 1956, on the recommendation of the States Reorganisation Commission.' },
  { id: 'polity-zonal-002', category: 'Polity - Zonal Councils & Commissions', question: 'How many Zonal Councils have been established in India, and who is the ex-officio Chairman of each?', options: ['5 Zonal Councils; Union Home Minister', '6 Zonal Councils; Prime Minister', '4 Zonal Councils; President', '5 Zonal Councils; Vice-President'], answer: 0, explanation: 'There are five Zonal Councils (Northern, Central, Eastern, Western, Southern), each with the Union Home Minister as the ex-officio Chairman.' },
  { id: 'polity-zonal-003', category: 'Polity - Zonal Councils & Commissions', question: 'The North Eastern Council, covering the North-Eastern States, was established under:', options: ['States Reorganisation Act, 1956', 'North Eastern Council Act, 1971', 'Constitution (73rd Amendment) Act', 'Government of India Act, 1935'], answer: 1, explanation: 'The North Eastern Council was constituted under the North Eastern Council Act, 1971, and is a separate statutory body from the five zonal councils.' },
  { id: 'polity-comm2-001', category: 'Polity - Zonal Councils & Commissions', question: 'The University Grants Commission (UGC) is a body established by:', options: ['A provision of the Constitution', 'An Act of Parliament (UGC Act, 1956)', 'An Executive Order of the President', 'A Supreme Court judgment'], answer: 1, explanation: 'The UGC is a statutory body established under the University Grants Commission Act, 1956, and is not a constitutional body.' },
  { id: 'polity-comm2-002', category: 'Polity - Zonal Councils & Commissions', question: 'Which of the following is a constitutional body, unlike the UGC and Planning Commission (now NITI Aayog)?', options: ['Finance Commission', 'National Human Rights Commission', 'Central Vigilance Commission', 'Law Commission of India'], answer: 0, explanation: 'The Finance Commission is a constitutional body established under Article 280; UGC, CVC, Law Commission and NHRC are statutory bodies, not created directly by the Constitution.' },

  // ===================== CAG-RELATED (Comptroller and Auditor General) =====================
  { id: 'polity-cag-001', category: 'Polity - CAG', question: 'Read the following statements regarding the Comptroller and Auditor General (CAG) of India:\n1. The CAG is a constitutional office, appointed by the President under Article 148 of the Constitution.\n2. The CAG\'s term is six years or until the age of 65 years, whichever is earlier, and is not renewable.\n3. The CAG can be removed only in the manner similar to a Supreme Court judge.\nWhich of the statements given above is/are correct?', options: ['1 only', '1 and 3 only', '2 and 3 only', '1, 2 and 3'], answer: 3, explanation: 'The CAG is appointed by the President under Article 148, holds office for 6 years or till 65 years of age (whichever is earlier), the term is not renewable, and removal follows the same process as a Supreme Court judge (Article 148(1)).' },
  { id: 'polity-cag-002', category: 'Polity - CAG', question: 'The CAG submits its audit reports relating to the accounts of the Union to:', options: ['The Prime Minister, who places it before the Cabinet', 'The President, who causes them to be laid before Parliament', 'The Finance Minister directly', 'The Chief Justice of India'], answer: 1, explanation: 'Article 151 provides that the reports of the CAG relating to the accounts of the Union are submitted to the President, who causes them to be laid before each House of Parliament.' },
  { id: 'polity-cag-003', category: 'Polity - CAG', question: 'Which article of the Constitution provides for the office of the Comptroller and Auditor General of India?', options: ['Article 143', 'Article 148', 'Article 150', 'Article 324'], answer: 1, explanation: 'Article 148 establishes the office of the Comptroller and Auditor General of India (CAG).' },
  { id: 'polity-cag-004', category: 'Polity - CAG', question: 'The form in which the accounts of the Union and States are kept is prescribed by the President on the advice of:', options: ['The CAG', 'The Finance Commission', 'The Finance Minister', 'NITI Aayog'], answer: 0, explanation: 'Article 150 provides that the accounts of the Union and States shall be kept in the form prescribed by the President on the advice of the CAG.' },

  // ===================== RAJYA SABHA SPECIAL POWERS (Art 249, 312) =====================
  { id: 'polity-rs-001', category: 'Polity - Rajya Sabha Special Powers', question: 'Under Article 249, a Rajya Sabha resolution empowering Parliament to legislate on a State List subject in national interest remains in force for:', options: ['Six months', 'One year, and can be renewed for further periods of one year', 'Two years', 'Five years'], answer: 1, explanation: 'A resolution under Article 249, passed by a two-thirds majority of members present and voting in the Rajya Sabha, remains valid for one year, and can be renewed any number of times for a further one year each.' },
  { id: 'polity-rs-002', category: 'Polity - Rajya Sabha Special Powers', question: 'Which article allows Parliament to legislate on a subject in the State List during a National Emergency?', options: ['Article 249', 'Article 250', 'Article 252', 'Article 253'], answer: 1, explanation: 'Article 250 empowers Parliament to legislate on any matter in the State List while a Proclamation of National Emergency is in operation.' },
  { id: 'polity-rs-003', category: 'Polity - Rajya Sabha Special Powers', question: 'Consider the following statements regarding the role of the Rajya Sabha in special legislative and emergency situations:\n1. Under Article 249, a Rajya Sabha resolution allowing Parliament to legislate on State List subjects remains valid for one year.\n2. The Parliament can extend a proclamation of President\'s Rule beyond one year only with the concurrence of, among other conditions, an operative National Emergency or Election Commission certification, and this needs approval of both Houses.\nWhich of the statements given above is/are correct?', options: ['1 only', '2 only', 'Both 1 and 2', 'Neither 1 nor 2'], answer: 2, explanation: 'Statement 1 correctly describes Article 249\'s one-year validity; Statement 2 correctly reflects the 44th Amendment\'s conditions for extending President\'s Rule beyond one year, requiring parliamentary approval.' },
  { id: 'polity-rs-004', category: 'Polity - Rajya Sabha Special Powers', question: 'The Rajya Sabha has a special power, not shared with the Lok Sabha, to authorize Parliament to create new All India Services. This is provided under:', options: ['Article 249', 'Article 312', 'Article 368', 'Article 371'], answer: 1, explanation: 'Article 312 gives the Rajya Sabha the exclusive power to pass a resolution (by 2/3rd majority) declaring it necessary in the national interest to create a new All India Service.' },

  // ===================== ARTICLE 300, 262 =====================
  { id: 'polity-300-001', category: 'Polity - Article 300 & Miscellaneous', question: 'Consider the following statements:\n1. Article 300 allows legal suits to be filed by or against the Government of India or a State Government.\n2. The term "Government of India" is treated as a legal entity capable of suing and being sued under Article 300.\nWhich of the statements given above is/are correct?', options: ['1 only', '2 only', 'Both 1 and 2', 'Neither 1 nor 2'], answer: 2, explanation: "Article 300 बताता है कि Union और States sue (case कर सकते हैं) और be sued (उनके खिलाफ case हो सकता है)।\n\nUnion → Union of India\nState → State के नाम से\nArticle 300 के तहत Union of India एक legal entity के रूप में suits/proceedings में party हो सकता है।\n299 → Government Contracts\n300 → Suits & Proceedings\n300A → Right to Property"},
  { id: 'polity-300-002', category: 'Polity - Article 300 & Miscellaneous', question: 'Article 262 empowers Parliament to make laws regarding:', options: ['Adjudication of disputes relating to waters of inter-State rivers or river valleys', 'Disputes between the Union and States over taxation', 'Boundary disputes between States', 'Disputes relating to Panchayat elections'], answer: 0, explanation: 'Article 262 empowers Parliament to provide by law for the adjudication of any dispute relating to the use, distribution or control of waters of inter-State rivers or river valleys.' },

  // ===================== GRANTS-IN-AID: ARTICLE 275 =====================
  { id: 'polity-275-001', category: 'Polity - Article 275 (Grants-in-Aid)', question: 'Article 275 of the Constitution provides for:', options: ['Statutory grants-in-aid from the Consolidated Fund of India to States in need of assistance, especially for welfare of Scheduled Tribes', 'Discretionary grants given by the President without Parliament\'s sanction', 'Loans to States from the Reserve Bank of India', 'Grants given only for disaster relief'], answer: 0, explanation: "Article 275 → Grants provided by Parliament/Union to States under constitutional provision.\n\nArticle 282 → Union ya State public purpose ke liye grants de sakta hai, even if the purpose is outside its legislative competence.\n\n🔥 Article 275 vs 270\nArticle 270 → Taxes/duties ka distribution between Centre & States\nArticle 275 → Grants-in-aid\nArticle 280 → Finance Commission, jo grants-in-aid ke principles recommend karta hai\n🧠 Super-short trick\n\n270 = Tax sharing 💰\n275 = Grant 💵\n280 = Finance Commission 📊"},
  { id: 'polity-275-002', category: 'Polity - Article 275 (Grants-in-Aid)', question: 'How does Article 275 differ from Article 282 with respect to Union grants to States?', options: ['Article 275 grants are statutory/mandatory and recommended by the Finance Commission, while Article 282 allows discretionary grants for any public purpose even outside the Union or State\'s legislative competence', 'Article 282 grants are only for Scheduled Tribes', 'Article 275 grants require State consent while Article 282 does not', 'There is no real difference between the two'], answer: 0, explanation: 'Article 275 provides statutory grants determined by Parliament (on Finance Commission\'s recommendation) to specific needy States; Article 282 gives the Union (and States) discretionary power to make grants for any public purpose, even if outside their normal legislative competence.' },
  { id: 'polity-275-003', category: 'Polity - Article 275 (Grants-in-Aid)', question: 'The grants-in-aid under Article 275 are charged on which fund?', options: ['Consolidated Fund of India', 'Contingency Fund of India', 'Public Account of India', 'Consolidated Fund of the concerned State'], answer: 0, explanation: 'Grants-in-aid under Article 275 are charged on and paid out of the Consolidated Fund of India each year.' },

  // ===================== JAMMU & KASHMIR: Article 370, 35A =====================
  { id: 'polity-jk-001', category: 'Polity - J&K (Article 370, 35A)', question: 'Article 370 of the Constitution, before its effective abrogation in 2019, provided:', options: ['Special autonomous status to the State of Jammu and Kashmir', 'Special status to the State of Punjab', 'Reservation for J&K residents in central services', 'A separate judiciary for J&K independent of the Supreme Court'], answer: 0, explanation: 'Article 370 (a "temporary provision") granted special autonomous status to Jammu and Kashmir, limiting the applicability of the Indian Constitution and requiring State concurrence for extension of central laws on many subjects.' },
  { id: 'polity-jk-002', category: 'Polity - J&K (Article 370, 35A)', question: 'Article 35A, which empowered the J&K legislature to define "permanent residents" and their special rights, was inserted into the Constitution through which method?', options: ['A regular Constitutional Amendment under Article 368', 'A Presidential Order under Article 370, without being placed before Parliament', 'A Supreme Court judgment', 'A State legislature resolution'], answer: 1, explanation: 'Article 35A was added via a Presidential Order (Constitution Application to Jammu and Kashmir Order, 1954) issued under Article 370, without going through the Article 368 amendment procedure or parliamentary approval as a formal amendment.' },
  { id: 'polity-jk-003', category: 'Polity - J&K (Article 370, 35A)', question: 'In August 2019, the special status under Article 370 was effectively abrogated through:', options: ['A Presidential Order under Article 370(1) read with a resolution of Parliament, followed by reorganisation of the State into two Union Territories', 'A unilateral decision of the Governor of J&K', 'A referendum held in J&K', 'A judgment of the High Court of J&K'], answer: 0, explanation: 'In August 2019, a Presidential Order under Article 370(1) applied the entire Constitution to J&K, and Parliament passed a resolution recommending revocation of special status; the J&K Reorganisation Act, 2019 then bifurcated the State into two Union Territories: J&K and Ladakh.' },
  { id: 'polity-jk-004', category: 'Polity - J&K (Article 370, 35A)', question: 'Consider the following statements about Article 370:\n1. It was placed under Part XXI of the Constitution, titled "Temporary, Transitional and Special Provisions".\n2. It required the "concurrence" of the State Government for the President to extend Union laws on subjects not in the Instrument of Accession.\nWhich of the statements given above is/are correct?', options: ['1 only', '2 only', 'Both 1 and 2', 'Neither 1 nor 2'], answer: 2, explanation: 'Article 370 was placed in Part XXI (Temporary, Transitional and Special Provisions), and required State Government concurrence for extending Union laws on matters beyond Defence, External Affairs and Communications covered by the Instrument of Accession.' },

  // ===================== IMPORTANT CONSTITUTIONAL AMENDMENTS =====================
  { id: 'polity-amend-001', category: 'Polity - Amendments', question: 'The 4th Constitutional Amendment Act, 1955, primarily dealt with:', options: ['Curtailment of the right to property and validation of certain land reform laws', 'Reorganisation of States', 'Insertion of Fundamental Duties', 'Reduction of voting age'], answer: 0, explanation: 'The 4th Amendment Act, 1955 amended Article 31 to curtail the right to property and validated certain zamindari abolition/land reform laws by adding them to the Ninth Schedule.' },
  { id: 'polity-amend-002', category: 'Polity - Amendments', question: 'The 52nd Constitutional Amendment Act, 1985, is significant for introducing:', options: ['The Anti-Defection Law via the Tenth Schedule', 'Fundamental Duties', 'Panchayati Raj institutions', 'The National Emergency provisions'], answer: 0, explanation: 'The 52nd Amendment Act, 1985 inserted the Tenth Schedule to the Constitution, laying down provisions on disqualification of members on grounds of defection.' },
  { id: 'polity-amend-003', category: 'Polity - Amendments', question: 'The 73rd Constitutional Amendment Act, 1992, primarily relates to:', options: ['Panchayati Raj institutions', 'Municipalities', 'Right to Education', 'Goods and Services Tax'], answer: 0, explanation: 'The 73rd Amendment Act gave constitutional status to Panchayati Raj institutions by inserting Part IX and the Eleventh Schedule.' },
  { id: 'polity-amend-004', category: 'Polity - Amendments', question: 'The 86th Constitutional Amendment Act, 2002, made which right a Fundamental Right?', options: ['Right to Education (Article 21A) for children aged 6-14 years', 'Right to Property', 'Right to Information', 'Right to Clean Environment'], answer: 0, explanation: 'The 86th Amendment Act, 2002 inserted Article 21A, making free and compulsory education for children aged 6-14 years a Fundamental Right, and also added the corresponding Fundamental Duty under Article 51A.' },
  { id: 'polity-amend-005', category: 'Polity - Amendments', question: 'The 99th Constitutional Amendment Act, 2014, sought to establish which body for appointment of judges, which was later struck down by the Supreme Court?', options: ['National Judicial Appointments Commission (NJAC)', 'National Human Rights Commission', 'Collegium 2.0', 'Law Commission of India'], answer: 0, explanation: 'The 99th Amendment Act, 2014 sought to replace the collegium system with the National Judicial Appointments Commission (NJAC) for appointment of judges, but it was struck down as unconstitutional by the Supreme Court in 2015 for violating judicial independence, a basic feature of the Constitution.' },
  { id: 'polity-amend-006', category: 'Polity - Amendments', question: 'The 100th Constitutional Amendment Act, 2015, gave effect to which agreement?', options: ['Land Boundary Agreement between India and Bangladesh', 'GST implementation agreement', 'J&K special status modification', 'Indo-Nepal border agreement'], answer: 0, explanation: 'The 100th Amendment Act, 2015 implemented the Land Boundary Agreement (LBA) between India and Bangladesh, involving exchange of certain enclaves between the two countries.' },
  { id: 'polity-amend-007', category: 'Polity - Amendments', question: 'The 102nd Constitutional Amendment Act, 2018, granted constitutional status to which body?', options: ['National Commission for Backward Classes (NCBC)', 'National Human Rights Commission', 'National Commission for Women', 'Central Vigilance Commission'], answer: 0, explanation: 'The 102nd Amendment Act, 2018 gave constitutional status to the National Commission for Backward Classes (NCBC), inserting Article 338B.' },
  { id: 'polity-amend-008', category: 'Polity - Amendments', question: 'Which amendment is known for inserting Articles 15(5) and 15(6), and also amending Article 19, to provide for reservations in educational institutions?', options: ['93rd Amendment (Art 15(5) for OBC reservation) and 103rd Amendment (Art 15(6) for EWS reservation)', '86th and 93rd Amendments', '99th and 101st Amendments', '73rd and 74th Amendments'], answer: 0, explanation: 'The 93rd Amendment Act, 2005 inserted Article 15(5) enabling reservation for OBCs/SC/ST in educational institutions including private ones; the 103rd Amendment Act, 2019 inserted Article 15(6) and 16(6) providing 10% EWS reservation.' },
  { id: 'polity-amend-009', category: 'Polity - Amendments', question: 'The 61st Constitutional Amendment Act, 1988, is associated with:', options: ['Reduction of voting age from 21 to 18 years', 'Introduction of GST', 'Anti-defection law', '73rd Amendment on Panchayats'], answer: 0, explanation: 'The 61st Amendment Act, 1988 amended Article 326 to reduce the voting age for Lok Sabha and Assembly elections from 21 to 18 years.' },
  { id: 'polity-amend-010', category: 'Polity - Amendments', question: 'Which amendment act is often called the "Mini Constitution" due to the extensive number of changes it made?', options: ['42nd Amendment Act, 1976', '44th Amendment Act, 1978', '52nd Amendment Act, 1985', '73rd Amendment Act, 1992'], answer: 0, explanation: 'The 42nd Amendment Act, 1976 made sweeping changes across the Constitution (Preamble, Fundamental Duties, judicial review restrictions, etc.), earning it the label "Mini Constitution".' },
  { id: 'polity-amend-011', category: 'Polity - Amendments', question: 'The 44th Constitutional Amendment Act, 1978, is significant because it:', options: ['Reversed several undemocratic changes made by the 42nd Amendment and removed the Right to Property from Part III as a Fundamental Right', 'Introduced Fundamental Duties for the first time', 'Established the Panchayati Raj system', 'Created the NCBC'], answer: 0, explanation: 'The 44th Amendment Act, 1978 undid several 42nd Amendment changes (e.g., restored judicial review, reduced Emergency duration for approval), and removed the Right to Property from Fundamental Rights, making it a legal right under Article 300A.' },

];
