// Static GK: Rivers
const staticRiversQuestions = [
 // ===================== RIVERS =====================

{ id: 'rivers-001', category: 'Rivers', question: "The Ganga is one of India's most important Himalayan rivers and is central to the drainage system of the northern plains. Its headstream, the Bhagirathi, originates from the Gangotri Glacier at Gaumukh. In which Indian state is this source located?", options: ['Uttarakhand', 'Himachal Pradesh', 'Sikkim', 'Arunachal Pradesh'], answer: 0, explanation: 'The Bhagirathi, the principal headstream of the Ganga, originates from the Gangotri Glacier at Gaumukh in Uttarakhand. It meets the Alaknanda at Devprayag, after which the combined river is known as the Ganga.' },

{ id: 'rivers-002', category: 'Rivers', question: "The Bhagirathi and Alaknanda are the two important headstreams associated with the Ganga river system. At which place in Uttarakhand do these two rivers meet, after which the combined stream is known as the Ganga?", options: ['Rudraprayag', 'Devprayag', 'Karnaprayag', 'Vishnuprayag'], answer: 1, explanation: 'The Bhagirathi and Alaknanda meet at Devprayag in Uttarakhand. From Devprayag onward, their combined stream is known as the Ganga.' },

{ id: 'rivers-003', category: 'Rivers', question: "The Ganga and Brahmaputra river systems carry enormous quantities of water and sediment from the Himalayas and together create a vast delta before reaching the sea. Into which water body does this river system ultimately drain?", options: ['Arabian Sea', 'Bay of Bengal', 'Indian Ocean near Kerala', 'Gulf of Kutch'], answer: 1, explanation: 'The Ganga and Brahmaputra together form the Sundarbans Delta and ultimately drain into the Bay of Bengal.' },

{ id: 'rivers-004', category: 'Rivers', question: "The Yamuna is the longest tributary of the Ganga and passes through important parts of northern India before meeting the Ganga at Prayagraj. From which glacier does the Yamuna originate?", options: ['Gangotri Glacier', 'Yamunotri Glacier', 'Pindari Glacier', 'Siachen Glacier'], answer: 1, explanation: 'The Yamuna originates from the Yamunotri Glacier near the Banderpoonch peak in Uttarakhand and ultimately joins the Ganga at Prayagraj.' },

{ id: 'rivers-005', category: 'Rivers', question: "Several important Peninsular rivers flow northward and join the Yamuna, making its drainage system much larger than its Himalayan headwaters alone. Which of the following is a major Peninsular tributary of the Yamuna?", options: ['Chambal', 'Gandak', 'Kosi', 'Ghaghara'], answer: 0, explanation: 'The Chambal is a major Peninsular tributary of the Yamuna. Other important Peninsular tributaries include the Betwa and Ken.' },

{ id: 'rivers-006', category: 'Rivers', question: "The Brahmaputra originates in Tibet and travels eastward before taking a major bend around the eastern Himalayas and entering India through Arunachal Pradesh. By which name is the river known in Tibet?", options: ['Jamuna', 'Yarlung Tsangpo', 'Karnali', 'Narayani'], answer: 1, explanation: 'The Brahmaputra is known as the Yarlung Tsangpo in Tibet. It later enters India through Arunachal Pradesh and is known as the Jamuna after entering Bangladesh.' },

{ id: 'rivers-007', category: 'Rivers', question: "The Brahmaputra follows an unusual course around the eastern Himalayas, taking a sharp turn before entering India through Arunachal Pradesh. Near which prominent Himalayan peak does this major bend occur?", options: ['Nanda Devi', 'Kanchenjunga', 'Namcha Barwa', 'Nanga Parbat'], answer: 2, explanation: 'The Brahmaputra, known as the Yarlung Tsangpo in Tibet, takes a sharp turn near Namcha Barwa before entering India through Arunachal Pradesh.' },

{ id: 'rivers-008', category: 'Rivers', question: "After flowing through Tibet and India, the Brahmaputra enters Bangladesh, where it eventually joins the Ganga river system. By which name is the main Brahmaputra channel commonly known in Bangladesh?", options: ['Padma', 'Jamuna', 'Meghna', 'Teesta'], answer: 1, explanation: 'The Brahmaputra is commonly known as the Jamuna in Bangladesh before joining the Ganga system.' },

{ id: 'rivers-009', category: 'Rivers', question: "The Indus is one of Asia's major river systems and follows an antecedent course through the Himalayan region before flowing through Ladakh and Pakistan. Near which geographical feature does the Indus originate?", options: ['Lake Mansarovar region in Tibet', 'Gangotri Glacier in Uttarakhand', 'Amarkantak Plateau', 'Western Ghats'], answer: 0, explanation: 'The Indus originates in Tibet near the Lake Mansarovar and Mount Kailash region before flowing through Ladakh and then Pakistan.' },

{ id: 'rivers-010', category: 'Rivers', question: "The five historic rivers of Punjab—Jhelum, Chenab, Ravi, Beas and Sutlej—form part of the larger Indus drainage system. Their combined waters ultimately join the Indus through which river system in Pakistan?", options: ['Panjnad', 'Ghaghara', 'Padma', 'Teesta'], answer: 0, explanation: "The waters of the five Punjab rivers ultimately combine through the Panjnad system in Pakistan before joining the Indus.\nJhelum -> Vitasta: Think of Jhelum flowing like a\nVista (Vitasta). (Also famous for the Battle of the\nHydaspes in Greek).\n\nChenab -> Asikni: Chenab starts with 'C', Asikni\nstarts with 'A' (ABC).\n\nRavi -> Parushni / Iravati: Associated with the\nhistoric Battle of Ten Kings (Dasrajna War) fought\non the banks of Parushni.\n\nBeas -> Vipasa: Beas -> Vipasa (B and V sound\nsimilar).\n\nSatluj -> Sutudri: Both start with 'S' (Satluj ->\nSutudri). "},

{ id: 'rivers-011', category: 'Rivers', question: "The Sutlej is the easternmost of the five historic rivers of Punjab and originates in the Tibetan region near Mansarovar. Which major multipurpose dam project is constructed on the Sutlej River?", options: ['Hirakud Dam', 'Bhakra Nangal Dam', 'Tehri Dam', 'Sardar Sarovar Dam'], answer: 1, explanation: 'The Bhakra Nangal project is constructed on the Sutlej River. The Sutlej originates near Rakas Lake in the Mansarovar region of Tibet.' },

{ id: 'rivers-012', category: 'Rivers', question: "The Kosi frequently changes its course and has historically caused devastating floods across the plains of northern Bihar. Due to this destructive flooding behaviour, by which popular name is the Kosi known?", options: ['Sorrow of Bengal', 'Sorrow of Bihar', 'Dakshin Ganga', 'River of Punjab'], answer: 1, explanation: 'The Kosi is popularly called the Sorrow of Bihar because of its frequent course changes and destructive floods.' },

{ id: 'rivers-013', category: 'Rivers', question: "The Gandak is an important Himalayan tributary of the Ganga. It originates in the Himalayan region of Nepal before entering the plains of India. By which name is the Gandak commonly known in Nepal?", options: ['Karnali', 'Narayani', 'Jamuna', 'Tsangpo'], answer: 1, explanation: 'The Gandak is known as the Narayani in Nepal. It later enters India and joins the Ganga as a left-bank tributary.' },

{ id: 'rivers-014', category: 'Rivers', question: "The Chambal originates near Mhow in the Malwa Plateau of Madhya Pradesh and flows through the ravine-dominated landscape of central and north-western India. The Chambal is a major tributary of which river?", options: ['Ganga', 'Yamuna', 'Narmada', 'Godavari'], answer: 1, explanation: 'The Chambal is a major tributary of the Yamuna. It flows through or along Madhya Pradesh, Rajasthan and Uttar Pradesh before meeting the Yamuna.' },

{ id: 'rivers-015', category: 'Rivers', question: "The National Chambal region is particularly important for riverine biodiversity and is known for relatively clean stretches of river habitat. Which endangered reptile is especially associated with the Chambal River ecosystem?", options: ['Gharial', 'Komodo dragon', 'Marine iguana', 'Saltwater crocodile'], answer: 0, explanation: 'The endangered gharial is strongly associated with the Chambal River ecosystem. The river also provides habitat for the Ganges river dolphin.' },];
